Repository pytorch/vision, pull requests merged in 2020-10, with the labels that each got.

#2683 (WIP) Initial implementation of the new videoReader API
  .travis.yml
  setup.py
  test/test_video.py
  torchvision/csrc/cpu/video/Video.cpp
  torchvision/csrc/cpu/video/Video.h
  torchvision/csrc/cpu/video/register.cpp
Labels: topic: video

#2826 [release/0.8] .cirlceci: Be specific about CU_VERSION for pytorch
  packaging/pkg_helpers.bash
Labels: module: ci

#2913 [release/0.8] packaging: Add version suffix to build version
  packaging/pkg_helpers.bash
Labels: topic: binaries, topic: build

#2914 packaging: Add version suffix to build version
  packaging/pkg_helpers.bash
Labels: topic: binaries, topic: build
