Repository pytorch/vision, pull requests merged in 2021-03, with the labels that each got.

#3448 separate caching logic from download for PhotoTour dataset
  torchvision/datasets/phototour.py
Labels: cla signed

#3455 make LSUN OS agnostic
  torchvision/datasets/lsun.py
Labels: cla signed

#3454 add tests for LSUN
  test/test_datasets.py
Labels: cla signed

#3453 include intended structure of root directory in docstring of Kinetics400
  torchvision/datasets/kinetics.py
Labels: cla signed

#3447 remove old CIFAR tests and fake data generation
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed

#3457 add tests for Kinetics400
  test/test_datasets.py
Labels: cla signed

#3458 add tests for HMDB51 dataset
  test/test_datasets.py
Labels: cla signed

#3461 add tests for Omniglot dataset
  test/test_datasets.py
Labels: cla signed

#3464 add tests for SBU dataset
  test/test_datasets.py
Labels: cla signed

#3465 add tests for SEMEION dataset
  test/test_datasets.py
Labels: cla signed

#3466 add tests for USPS dataset
  test/test_datasets.py
Labels: cla signed

#3474 set empty cxx flags as default during setup
  setup.py
Labels: cla signed

#3467 add tests for SBDataset
  test/datasets_utils.py
  test/test_datasets.py
Labels: cla signed

#3445 Run CI unittests in parallel
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/linux/scripts/run_test.sh
  .circleci/unittest/windows/scripts/environment.yml
  .circleci/unittest/windows/scripts/run_test.sh
Labels: cla signed

#3468 add tests for FakeData dataset
  test/test_datasets.py
Labels: cla signed

#3480 Revert "Run CI unittests in parallel"
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/linux/scripts/run_test.sh
  .circleci/unittest/windows/scripts/environment.yml
  .circleci/unittest/windows/scripts/run_test.sh
Labels: cla signed

#3479 Increase tolerance in scripted models
  test/common_utils.py
Labels: cla signed

#3481 Fix lazy importing for dataset tests
  test/datasets_utils.py
Labels: cla signed

#3486 Add tests for the PhotoTour dataset
  test/datasets_utils.py
  test/test_datasets.py
  torchvision/datasets/phototour.py
Labels: cla signed

#3472 fixed Gamma casting
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#3492 [FBcode->GH] change image type for LSUN tests
  test/test_datasets.py
Labels: cla signed

#3491 Add __repr__ for transforms.RandomErasing
  test/test_transforms.py
  torchvision/transforms/transforms.py
Labels: cla signed

#3498 add custom user agent for download_url
  .github/workflows/tests-schedule.yml
  test/test_datasets_download.py
  torchvision/datasets/utils.py
Labels: cla signed

#3499 add custom user agent for download_url
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
  .github/workflows/tests-schedule.yml
  test/test_datasets_download.py
  torchvision/datasets/utils.py
Labels: cla signed

#3494 [TRANS, IMP] Add new max_size parameter to Resize
  test/test_functional_tensor.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/functional_tensor.py
  torchvision/transforms/transforms.py
Labels: cla signed

#3503 [FBcode->GH] Add back cifar_root
  test/fakedata_generation.py
Labels: cla signed

#3483 [OPS, TEST] Add onnx test for batched_nms
  test/test_onnx.py
Labels: cla signed

#3507 update stable to point to 0.9
  stable
  versions.html
Labels: cla signed

#3426 [OPS, IMP] New batched_nms implementation
  test/test_onnx.py
  test/test_ops.py
  torchvision/ops/boxes.py
Labels: cla signed

#3516 rename version 'master (0.9.0+cu111 )' -> '0.9.0'
  0.9/datasets.html
  0.9/genindex.html
  0.9/index.html
  0.9/io.html
  0.9/models.html
  0.9/ops.html
  0.9/py-modindex.html
  0.9/search.html
  0.9/transforms.html
  0.9/utils.html
Labels: cla signed

#3493 Speed up equalize transform: use bincount instead of histc
  test/test_functional_tensor.py
  torchvision/transforms/functional_tensor.py
Labels: cla signed, improvement, module: transforms

#3530 add 0.9.0 to compatibility table
  README.rst
Labels: cla signed

#3513 Updated the outdated copyright
  docs/source/conf.py
Labels: cla signed

#3490 feat(docs): navigate with left/right arrow keys
  docs/source/conf.py
Labels: cla signed

#3533 Use ternary if in resize
  torchvision/transforms/functional_tensor.py
Labels: cla signed, module: transforms, refactoring

#3539 Use pytorch smooth_l1_loss and remove private custom implem
  torchvision/models/detection/_utils.py
  torchvision/models/detection/roi_heads.py
  torchvision/models/detection/rpn.py
Labels: cla signed, module: models, refactoring

#3529 [DOC] Adds Documentation for AutoAugmentation
  docs/source/transforms.rst
  torchvision/transforms/autoaugment.py
Labels: cla signed, improvement, module: documentation, module: transforms

#3489 add tests for Flickr(8|30)k datasets
  test/test_datasets.py
Labels: cla signed

#3540 Added test for RoiAlign with aligned=True
  test/test_ops.py
Labels: cla signed, improvement, module: ops, module: tests

#3545 remove redundant path.join in Places365
  torchvision/datasets/places365.py
Labels: cla signed

#3542 fix test_extract_(zip|tar|tar_xz|gzip) on windows
  test/test_datasets_utils.py
Labels: cla signed

#3488 remove imprecise error handling in PhotoTour dataset
  torchvision/datasets/phototour.py
Labels: cla signed

#3544 datasets: Fallback to our own mirrors for mnist
  torchvision/datasets/mnist.py
Labels: cla signed, module: datasets

#3543 New tests for ImageNet dataset
  test/datasets_utils.py
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed, improvement, module: datasets, module: tests

#3557 Fix (Fashion|K)MNIST download and MNIST download test
  test/test_datasets_download.py
  torchvision/datasets/mnist.py
Labels: cla signed

#3548 Fix test skipping for windows platform and avoid skipping MacOS
  test/test_datasets.py
  test/test_utils.py
Labels: cla signed, improvement, module: tests

#3536 [DOC] Add docs for missing datasets
  docs/source/datasets.rst
  torchvision/datasets/kinetics.py
  torchvision/datasets/semeion.py
  torchvision/datasets/widerface.py
Labels: cla signed

#3553 Fix ternary operator to decide to store an image in Grayscale or RGB
  torchvision/csrc/io/image/cpu/encode_png.cpp
Labels: cla signed, fix, module: io

#3355 [ONNX] Fix roi_align ONNX export
  test/test_onnx.py
  torchvision/ops/_register_onnx_ops.py
Labels: cla signed

#3559 Fix MNIST download for minor release
  test/test_datasets_download.py
  torchvision/datasets/mnist.py
Labels: cla signed

#3551 [android] gradle wrapper
  android/.gitignore
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
Labels: cla signed

#3552 [android] publishing to maven central
  android/build.gradle
  android/gradle.properties
  android/gradle_scripts/android_maven_install.gradle
  android/gradle_scripts/android_tasks.gradle
  android/gradle_scripts/bintray.gradle
  android/gradle_scripts/gradle_maven_push.gradle
  android/gradle_scripts/release.gradle
  android/gradle_scripts/release_bintray.gradle
Labels: cla signed

#3561 [android] gradle wrapper + publish to maven central
  android/.gitignore
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradle_scripts/android_maven_install.gradle
  android/gradle_scripts/android_tasks.gradle
  android/gradle_scripts/bintray.gradle
  android/gradle_scripts/gradle_maven_push.gradle
  android/gradle_scripts/release.gradle
  android/gradle_scripts/release_bintray.gradle
  android/gradlew
  android/gradlew.bat
Labels: cla signed

#3564 Fix redirect behavior of datasets.utils.download_url
  torchvision/datasets/utils.py
Labels: cla signed

#3443 Separate extraction and decompression logic in datasets.utils.extract_archive
  test/common_utils.py
  test/test_datasets_utils.py
  torchvision/datasets/utils.py
Labels: WIP, cla signed

#3566 Fix redirect behavior of datasets.utils.download_url (#3564)
  torchvision/datasets/utils.py
Labels: cla signed

#3550 New tests for WIDERFace dataset
  test/datasets_utils.py
  test/test_datasets.py
Labels: cla signed, improvement, module: datasets, module: tests

#3567 update EMNIST url
  torchvision/datasets/mnist.py
Labels: cla signed

#3570 update EMNIST url (#3567)
  torchvision/datasets/mnist.py
Labels: cla signed

#3537 Fixed typo on line 12
  torchvision/transforms/_functional_video.py
Labels: cla signed

#3576 Add explanation for injected fake data in dataset tests
  test/datasets_utils.py
Labels: cla signed, module: documentation, module: tests

#3420 Remove caching from MNIST and variants
  test/test_datasets.py
  torchvision/datasets/mnist.py
Labels: cla signed

#3579 Move internet tests in single file
  CONTRIBUTING.md
  test/test_datasets_utils.py
  test/test_internet.py
Labels: cla signed, module: tests

#3568 fix redirection in download tests
  test/test_datasets_download.py
Labels: cla signed

#3572 fix VOC datasets for 2007
  torchvision/datasets/voc.py
Labels: cla signed

#3580 fix VOC datasets for 2007 (#3572)
  torchvision/datasets/voc.py
Labels: bug, cla signed, module: datasets

#3584 Clarify docstring of RandomResizedCrop
  torchvision/transforms/transforms.py
Labels: cla signed, module: documentation, module: transforms

#3589 enable tests for WIDERFace on Windows
  test/test_datasets.py
Labels: cla signed, module: datasets, module: tests

#3586 Clarify docstring of RandomResizedCrop -- ctnd
  torchvision/transforms/transforms.py
Labels: cla signed, module: documentation, module: transforms

#3591 removed duplicate as
  torchvision/models/detection/transform.py
Labels: cla signed

#3587 .item() added to the 'target' variable in fakedataset.py
  test/test_datasets.py
  torchvision/datasets/fakedata.py
Labels: cla signed

#3581 Update squeezenet weights urls
  torchvision/models/squeezenet.py
Labels: cla signed, fix, module: datasets

#3592 [v0.9.1] .circleci: Bump versions to 1.8.1, 0.9.1
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#3578 Enable custom default config for dataset tests
  test/datasets_utils.py
  test/test_datasets.py
Labels: cla signed, module: datasets, module: tests

#3575 add ROCm binary wheels
  .circleci/config.yml
  .circleci/regenerate.py
  packaging/pkg_helpers.bash
Labels: cla signed, module: rocm

#3330 Added utility to draw segmentation masks
  docs/source/utils.rst
  test/assets/fakedata/draw_segm_masks_colors_util.png
  test/assets/fakedata/draw_segm_masks_no_colors_util.png
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#3496 Improve error handling in make_dataset
  test/test_datasets.py
  torchvision/datasets/folder.py
  torchvision/datasets/hmdb51.py
  torchvision/datasets/kinetics.py
  torchvision/datasets/ucf101.py
Labels: cla signed

#3423 add tests for MNIST and variants
  test/test_datasets.py
Labels: cla signed

#3599 Bump nightlies to 0.10.0
  android/gradle.properties
  packaging/build_cmake.sh
  packaging/build_conda.sh
  packaging/build_wheel.sh
  packaging/windows/internal/nightly_defaults.bat
  version.txt
Labels: cla signed

#3389 Implementing multithreaded video decoding
  torchvision/csrc/io/decoder/decoder.cpp
  torchvision/csrc/io/decoder/defs.h
  torchvision/csrc/io/decoder/stream.cpp
  torchvision/csrc/io/decoder/stream.h
  torchvision/csrc/io/video/video.cpp
  torchvision/csrc/io/video/video.h
  torchvision/io/__init__.py
Labels: cla signed

#3603 [v0.9.1] Remove special versioning suffix rules for CUDA 10.2
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/scripts/vs_install_cmath.ps1
  packaging/pkg_helpers.bash
Labels: cla signed

#3605 Put back skip windows decorator for cityscape dataset
  test/test_datasets.py
Labels: cla signed, module: datasets, module: tests

#3609 .circleci: Fix windows cmath issues
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/scripts/vs_install_cmath.ps1
Labels: cla signed, module: ci

#3601 Add quantized version of nms
  setup.py
  test/test_ops.py
  torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp
Labels: cla signed, improvement, module: models.quantization, module: ops

#3595 New tests for CityScapes dataset
  test/datasets_utils.py
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed, improvement, module: datasets, module: tests

#3582 [iOS] added workflows for libtorchvision_ops.a binary build
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .circleci/unittest/ios/scripts/binary_ios_build.sh
  .circleci/unittest/ios/scripts/binary_ios_upload.sh
  cmake/iOS.cmake
  ios/CMakeLists.txt
  ios/build_ios.sh
Labels: cla signed, topic: binaries, topic: mobile

#3604 and ROCm 4.1 nightly wheels
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#3477 add tests for (Dataset|Image)Folder
  test/test_datasets.py
  torchvision/datasets/folder.py
Labels: cla signed

#3399 Use TORCH_CUDA_ARCH_LIST to specify which CUDA architectures to build for
  packaging/pkg_helpers.bash
  packaging/torchvision/meta.yaml
Labels: cla signed, topic: build

#3621 [BC-breaking] Ensure the input tensor of normalize is float
  test/test_transforms_tensor.py
  torchvision/transforms/functional.py
Labels: bc-breaking, bug

#3622 [iOS] Remove the context for building jobs, only keep it for nightly build uploading
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed, topic: build, topic: mobile

#3618 Remove unneeded packaging files
  packaging/conda/build_vision.sh
  packaging/conda/install_conda.bat
  packaging/conda/switch_cuda_version.sh
  packaging/windows/azure-pipelines-ci.yml
  packaging/windows/azure-pipelines.yml
  packaging/windows/build_vision.bat
  packaging/windows/cpu.bat
  packaging/windows/cuda101.bat
  packaging/windows/cuda102.bat
  packaging/windows/cuda92.bat
  packaging/windows/internal/auth.bat
  packaging/windows/internal/build_conda.bat
  packaging/windows/internal/build_wheels.bat
  packaging/windows/internal/check_deps.bat
  packaging/windows/internal/check_opts.bat
  packaging/windows/internal/clean.bat
  packaging/windows/internal/clone.bat
  packaging/windows/internal/copy.bat
  packaging/windows/internal/copy_cpu.bat
  packaging/windows/internal/dep_install.bat
  packaging/windows/internal/env_fix.bat
  packaging/windows/internal/nightly_defaults.bat
  packaging/windows/internal/publish.bat
  packaging/windows/internal/setup.bat
  packaging/windows/internal/test.bat
  packaging/windows/internal/upload.bat
  packaging/windows/internal/vs_install.bat
  packaging/windows/old/cuda100.bat
  packaging/windows/old/cuda90.bat
  packaging/windows/templates/auth_task.yml
  packaging/windows/templates/build_conda.yml
  packaging/windows/templates/build_task.yml
  packaging/windows/templates/build_wheels.yml
  packaging/windows/templates/linux_build_task.yml
  packaging/windows/templates/override_pytorch_version.yml
  packaging/windows/templates/publish_packages.yml
  packaging/windows/templates/publish_test_results.yml
  packaging/windows/templates/setup_env_for_msagent.yml
  packaging/windows/templates/setup_nightly_variables.yml
  packaging/windows/templates/upload_to_conda.yml
  packaging/windows/templates/upload_to_s3.yml
  packaging/windows/templates/vsts_auth.yml
Labels: cla signed, topic: build

#3620 Update weights of classification models to allow proper unpickling
  torchvision/models/alexnet.py
  torchvision/models/resnet.py
Labels: cla signed, fix, module: models

#3615 Add warning in docs of Resize about different results for PIL and tensors
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: cla signed, module: documentation, module: transforms

#3619 Minor cleanup of roi_align_forward_kernel_impl
  torchvision/csrc/ops/cpu/ps_roi_align_kernel.cpp
  torchvision/csrc/ops/cpu/roi_align_kernel.cpp
Labels: code quality, module: ops

#3623 [FBcode->GH] Revert "Implementing multithreaded video decoding"
  torchvision/csrc/io/decoder/decoder.cpp
  torchvision/csrc/io/decoder/defs.h
  torchvision/csrc/io/decoder/stream.cpp
  torchvision/csrc/io/decoder/stream.h
  torchvision/csrc/io/video/video.cpp
  torchvision/csrc/io/video/video.h
  torchvision/io/__init__.py
Labels: cla signed
