Repository pytorch/vision, pull requests merged in 2021-10, with the labels that each got.

#4418 Improve FX node naming
  docs/source/feature_extraction.rst
  test/test_backbone_utils.py
  torchvision/models/feature_extraction.py
Labels: cla signed

#4520 Minor typo fixes
  gallery/plot_visualization_utils.py
  torchvision/models/detection/rpn.py
  torchvision/models/feature_extraction.py
Labels: cla signed, code quality

#4522 Tweak docs for better understanding of what spatial_scale does
  torchvision/ops/ps_roi_align.py
  torchvision/ops/ps_roi_pool.py
  torchvision/ops/roi_align.py
  torchvision/ops/roi_pool.py
Labels: cla signed

#4517 enable Shuffler in Caltech prototype
  torchvision/prototype/datasets/_builtin/caltech.py
Labels: module: datasets, cla signed, prototype

#4524 Remove prototype folder from release
  torchvision/prototype/__init__.py
  torchvision/prototype/datasets/__init__.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_builtin/caltech101.categories
  torchvision/prototype/datasets/_builtin/caltech256.categories
  torchvision/prototype/datasets/_folder.py
  torchvision/prototype/datasets/_home.py
  torchvision/prototype/datasets/decoder.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_internal.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: cla signed

#4533 Relative import for roi_align
  torchvision/ops/poolers.py
Labels: cla signed, code quality, ciflow/default

#4516 add rocm4.3.1 to nightly wheel builds
  .circleci/config.yml
  .circleci/regenerate.py
Labels: module: rocm, cla signed, ciflow/default

#4530 Update Regnet model weights
  docs/source/models.rst
  torchvision/models/regnet.py
Labels: module: models, cla signed, ciflow/default

#4538 fix import order for torchvision.prototype.datasets
  torchvision/prototype/datasets/__init__.py
Labels: bug, cla signed, code quality, ciflow/default

#4531 Set allow_redefinition = True for mypy
  mypy.ini
  torchvision/datasets/celeba.py
  torchvision/datasets/imagenet.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_folder.py
Labels: cla signed, code quality, ciflow/default

#4534 Use enumerate to get index of ModuleList
  torchvision/models/detection/ssd.py
  torchvision/ops/feature_pyramid_network.py
Labels: cla signed, ciflow/default

#4527 Fix annotation of draw_segmentation_masks
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed, ciflow/default

#4511 add prototype for CIFAR datasets
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_builtin/cifar.py
  torchvision/prototype/datasets/_builtin/cifar10.categories
  torchvision/prototype/datasets/_builtin/cifar100.categories
  torchvision/prototype/datasets/decoder.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_internal.py
Labels: module: datasets, cla signed, ciflow/default, prototype

#4536 More instructions in contributing guide regarding formatting
  CONTRIBUTING.md
Labels: module: documentation, cla signed, ciflow/default

#4496 Switch testing to torch_test rather than torch_nightly
  .circleci/config.yml
  .circleci/config.yml.in
  packaging/pkg_helpers.bash
Labels: cla signed, ciflow/default

#4525 add prototype for VOC dataset
  torchvision/datasets/voc.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/voc.py
  torchvision/prototype/datasets/utils/_internal.py
Labels: module: datasets, cla signed, ciflow/default, prototype

#4537 add prototype for SBD dataset
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/sbd.categories
  torchvision/prototype/datasets/_builtin/sbd.py
  torchvision/prototype/datasets/utils/_internal.py
Labels: module: datasets, cla signed, ciflow/default, prototype

#4514 add prototype dataset for CelebA
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/celeba.py
Labels: module: datasets, cla signed, ciflow/default, prototype

#4544 Fix bug on EMA n_averaged estimation
  references/classification/utils.py
Labels: bug, module: reference scripts, cla signed, ciflow/default

#4545 Fix bug on EMA n_averaged estimation. (#4544)
  references/classification/utils.py
Labels: bug, module: reference scripts, ciflow/default

#4799 Add logging to torchvision ops
  torchvision/ops/boxes.py
  torchvision/ops/deform_conv.py
  torchvision/ops/feature_pyramid_network.py
  torchvision/ops/focal_loss.py
  torchvision/ops/misc.py
  torchvision/ops/poolers.py
  torchvision/ops/ps_roi_align.py
  torchvision/ops/ps_roi_pool.py
  torchvision/ops/roi_align.py
  torchvision/ops/roi_pool.py
  torchvision/ops/stochastic_depth.py
  torchvision/utils.py
Labels: cla signed, ciflow/default

#4667 add tests for prototype datasets API
  .circleci/config.yml
  .circleci/config.yml.in
  test/test_prototype_datasets.py
Labels: module: datasets, module: tests, cla signed, ciflow/default, prototype

#4807 add val split and year 2017 to prototype coco
  torchvision/prototype/datasets/_builtin/coco.py
Labels: module: datasets, cla signed, ciflow/default, prototype
