Repository pytorch/vision, pull requests merged in 2021-07, with the labels that each got.

#4148 Explicitly exclude PIL 8.3.0 from compatible dependencies
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/windows/scripts/environment.yml
  setup.py
Labels: bug, cla signed, dependency issue

#4123 Add iNaturalist dataset
  docs/source/datasets.rst
  test/test_datasets.py
  torchvision/datasets/__init__.py
  torchvision/datasets/inaturalist.py
Labels: cla signed

#4141 Support float in `torchvision.io.video.read_video`
  torchvision/io/video.py
Labels: cla signed, code quality, module: video

#4159 Minor grammar fix to docstring
  torchvision/__init__.py
Labels: cla signed, enhancement, module: documentation

#4162 Do not install lame when building torchvision
  packaging/build_wheel.sh
  packaging/pkg_helpers.bash
Labels: cla signed

#4165 Catch ValueError due to recent change to torch.testing.assert_close
  test/test_models.py
Labels: bug, module: tests

#4166 [FBcode->GH] [JIT] Add reference semantics to TorchScript classes (#44324)
  test/test_transforms_tensor.py
Labels: bug, cla signed, torchscript

#4167 Don't check transparency channel for pil >= 8.3
  test/test_image.py
Labels: bug, cla signed, dependency issue, module: io, module: tests

#4177 Cleanup test suite related to `torch.testing.assert_close`
  test/_assert_utils.py
  test/common_utils.py
  test/test_datasets_samplers.py
  test/test_datasets_video_utils.py
  test/test_functional_tensor.py
  test/test_image.py
  test/test_io.py
  test/test_models_detection_anchor_utils.py
  test/test_models_detection_negative_samples.py
  test/test_models_detection_utils.py
  test/test_onnx.py
  test/test_ops.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  test/test_transforms_video.py
  test/test_utils.py
  test/test_video_reader.py
Labels: cla signed, code quality, module: tests

#4179 Don't install torchvision as editable mode when not needed
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed, module: ci

#4184 Fixed MNIST Download Raises 'UserWarning: The given NumPy array is not writeable'
  torchvision/datasets/mnist.py
Labels: cla signed

#4176 [ONNX] use test images from repo rather than internet
  test/test_onnx.py
Labels: cla signed, code quality, module: onnx, module: tests

#4168 Added missing typing annotations in datasets/coco
  torchvision/datasets/coco.py
Labels: cla signed, code quality, module: datasets

#4170 Added missing typing annotations in datasets/kinetics
  torchvision/datasets/kinetics.py
Labels: cla signed, code quality, module: datasets

#4171 Added missing typing annotations in datasets/ucf101
  torchvision/datasets/ucf101.py
Labels: cla signed

#4196 add `pytest.ini`
  pytest.ini
Labels: cla signed, module: ci, module: tests

#4197 Mock redirection logic for tests
  test/test_datasets_utils.py
  test/test_internet.py
Labels: cla signed, dependency issue, module: tests

#4185 [ONNX] Remove conditional import of onnxruntime
  test/test_onnx.py
Labels: cla signed

#4202 update PyTorch version in android workflow
  android/build.gradle
Labels: cla signed, dependency issue, module: ci

#4200 Ignore direnv files
  .gitignore
Labels: cla signed

#4201 pin delocate version for macos wheel build
  packaging/build_wheel.sh
Labels: cla signed, dependency issue, module: ci, topic: binaries

#4064 Fixed missing audio with pyav backend
  test/test_video_reader.py
  torchvision/io/video.py
Labels: cla signed, module: io, module: tests, module: video

#4207 Remove TestCase dependency for test_models_detection_anchor_utils.py
  test/test_models_detection_anchor_utils.py
Labels: cla signed, code quality, module: tests

#4212 Replace set_deterministic with non-deprecated spelling
  test/test_functional_tensor.py
Labels: cla signed

#4208 [1/2] Added backward pass on CPU for interpolation with anti-alias option
  test/test_functional_tensor.py
  torchvision/csrc/ops/cpu/interpolate_aa_kernels.cpp
  torchvision/csrc/ops/cuda/interpolate_aa_kernels.cu
  torchvision/csrc/ops/interpolate_aa.cpp
  torchvision/csrc/ops/interpolate_aa.h
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#4215 Port test/test_datasets.py to use pytest
  test/datasets_utils.py
  test/test_datasets.py
Labels: cla signed

#4169 Added missing typing annotations in datasets/hmdb51
  torchvision/datasets/hmdb51.py
Labels: cla signed

#4203 fix MacOS cmake workflow
  packaging/build_cmake.sh
Labels: cla signed, module: ci, topic: build
