Repository pytorch/vision, pull requests merged in 2021-02, with the labels that each got.

#3329 Move run-clang-format script in .circleci
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/linux/scripts/run-clang-format.py
  travis-scripts/run-clang-format/LICENSE
Labels: cla signed

#3296 Adds fill paramter to utils.draw_bounding_boxes
  .gitignore
  test/assets/fakedata/draw_boxes_util.png
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#3335 Fixing mypy errors
  torchvision/datasets/semeion.py
  torchvision/datasets/stl10.py
  torchvision/datasets/usps.py
Labels: cla signed

#3333 Bugfix - same output for PIL and tensor when centercrop size is greater than imgsize
  CONTRIBUTING.md
  test/test_transforms.py
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: cla signed

#3336 Add download tests for MNIST
  .github/workflows/tests-schedule.yml
  test/test_datasets_download.py
Labels: cla signed

#3337 Add download tests for FashionMNIST
  test/test_datasets_download.py
Labels: cla signed

#3245 Check if the file is located on Google Drive
  test/test_datasets_utils.py
  torchvision/datasets/utils.py
Labels: cla signed

#3323 Add Quantizable MobilenetV3 architecture for Classification
  docs/source/models.rst
  references/classification/README.md
  references/classification/train.py
  references/classification/train_quantization.py
  torchvision/models/mobilenetv3.py
  torchvision/models/quantization/mobilenet.py
  torchvision/models/quantization/mobilenetv3.py
Labels: cla signed

#3338 Add download tests for remaining datasets
  test/test_datasets_download.py
Labels: cla signed

#3347 [FBCode->GH] accept python bytes in _read_video_from_memory()
  torchvision/io/_video_opt.py
Labels: cla signed

#3346 Improve download tests
  test/test_datasets_download.py
Labels: cla signed

#3345 Add tests for the STL10 dataset
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed

#3348 Fix some deprecation warnings from PyTorch
  torchvision/models/detection/retinanet.py
  torchvision/transforms/_functional_video.py
Labels: cla signed

#3350 [FBCode->GH] Add ops-cpp target to torchvision
  test/cpp/test_custom_operators.cpp
Labels: cla signed

#2897 [android] android gradle project for ops
  android/.gitignore
  android/build.gradle
  android/gradle.properties
  android/gradle_scripts/android_maven_install.gradle
  android/gradle_scripts/android_tasks.gradle
  android/gradle_scripts/bintray.gradle
  android/gradle_scripts/gradle_maven_push.gradle
  android/gradle_scripts/release.gradle
  android/gradle_scripts/release_bintray.gradle
  android/ops/CMakeLists.txt
  android/ops/build.gradle
  android/ops/gradle.properties
  android/ops/src/main/AndroidManifest.xml
  android/settings.gradle
  android/test_app/app/build.gradle
  android/test_app/app/src/main/AndroidManifest.xml
  android/test_app/app/src/main/java/org/pytorch/testapp/BBox.java
  android/test_app/app/src/main/java/org/pytorch/testapp/CameraActivity.java
  android/test_app/app/src/main/java/org/pytorch/testapp/MainActivity.java
  android/test_app/app/src/main/java/org/pytorch/testapp/Result.java
  android/test_app/app/src/main/res/layout/activity_camera.xml
  android/test_app/app/src/main/res/layout/activity_main.xml
  android/test_app/app/src/main/res/layout/texture_view.xml
  android/test_app/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/test_app/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/test_app/app/src/main/res/values/colors.xml
  android/test_app/app/src/main/res/values/strings.xml
  android/test_app/app/src/main/res/values/styles.xml
  android/test_app/make_assets.py
  torchvision/csrc/vision.cpp
Labels: cla signed

#3353 fix STL10 folds
  torchvision/datasets/stl10.py
Labels: cla signed

#3360 Replace top-X error with Acc@X and fix metric discrepancies
  docs/source/models.rst
Labels: cla signed

#3344 bugfix aspect ratio sampling in transforms.RandomErasing
  test/test_transforms.py
  torchvision/transforms/transforms.py
Labels: cla signed

#3354 Adding MobileNetV3 Small pre-trained model
  docs/source/models.rst
  references/classification/README.md
  torchvision/models/mobilenetv3.py
Labels: cla signed

#3366 Removed temporarily the MobileNetV3 Small quantized model endpoint
  docs/source/models.rst
  torchvision/models/quantization/mobilenet.py
  torchvision/models/quantization/mobilenetv3.py
Labels: cla signed

#3369 Fix flaky test_random_erasing test
  test/test_transforms.py
Labels: cla signed

#3352 Add weight averaging and storing methods in references utils
  references/classification/utils.py
Labels: cla signed

#3374 [FBcode->GH] Use proper variable for tls key file for avformat options
  torchvision/csrc/io/decoder/decoder.cpp
Labels: cla signed

#3376 remove generated dataset folders after download tests
  test/test_datasets_download.py
Labels: cla signed

#3379 [FBcode->GH] Daily `arc lint --take GOOGLEJAVAFORMAT`
  android/test_app/app/src/main/java/org/pytorch/testapp/CameraActivity.java
  android/test_app/app/src/main/java/org/pytorch/testapp/MainActivity.java
Labels: cla signed

#3382 Rewrite generalized_box_iou and box_iou to share code
  torchvision/ops/boxes.py
Labels: cla signed

#3380 Fix ops registration on windows
  test/tracing/frcnn/test_frcnn_tracing.cpp
  torchvision/csrc/macros.h
  torchvision/csrc/vision.h
Labels: cla signed

#3381 Use version.txt to determine torchvision version in CMakeLists.txt
  CMakeLists.txt
Labels: cla signed

#3341 .circleci: Add Python 3.9, CUDA 11.2 to CI
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/linux/scripts/setup_env.sh
  .circleci/unittest/windows/scripts/environment.yml
  .circleci/unittest/windows/scripts/install.sh
  .circleci/unittest/windows/scripts/setup_env.sh
  packaging/pkg_helpers.bash
  packaging/torchvision/meta.yaml
  packaging/windows/internal/cuda_install.bat
  test/common_utils.py
  test/test_video.py
  test/test_video_reader.py
Labels: cla signed, module: ci

#3384 [FBcode->GH] Enable GPU/RE teags for pytorch/*/TARGETS that needs GPU
  test/_utils_internal.py
  test/common_utils.py
Labels: cla signed

#3386 Fix test flakiness on test_random_erasing()
  test/test_transforms.py
Labels: cla signed

#3390 Fixed compilation warnings on C++ codebase
  torchvision/csrc/io/image/cpu/decode_jpeg.cpp
  torchvision/csrc/io/image/cpu/encode_png.cpp
  torchvision/csrc/io/video/video.cpp
  torchvision/csrc/io/video/video.h
  torchvision/csrc/io/video_reader/video_reader.cpp
Labels: cla signed

#3391 [FBcode->GH] Add link-whole to torchvision ops-cpp
  test/cpp/test_custom_operators.cpp
Labels: cla signed

#3383 Fix NMS and IoU overflows for fp16
  test/test_ops.py
  torchvision/csrc/ops/cuda/nms_kernel.cu
  torchvision/ops/boxes.py
Labels: cla signed

#3398 Functional to_tensor returns float tensor of default dtype
  test/test_transforms.py
  torchvision/transforms/functional.py
Labels: cla signed

#3396 Fix incorrectly frozen BN on ResNet FPN backbone
  torchvision/models/detection/backbone_utils.py
Labels: cla signed

#3400 Updated CONTRIBUTING guide.
  CONTRIBUTING.md
Labels: cla signed

#3401 Restore cache in circleCI
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#3377 add a versions.html
  versions.html
Labels: cla signed

#3378 make the version a link to /versions.html
  docs/source/_templates/layout.html
Labels: cla signed

#3373 add CI qualifier to push docs for new tags
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#3407 Typo: fix stable version link
  versions.html
Labels: cla signed

#3408 typo in link to versions.html
  docs/source/_templates/layout.html
Labels: cla signed

#3402 [POC] Base class for dataset tests
  test/common_utils.py
  test/datasets_utils.py
  test/test_datasets.py
Labels: cla signed

#3419 Fix win arg patch for BUILD_SPLIT_CUDA=ON
  CMakeLists.txt
Labels: cla signed

#3038 Revert "Added "-fopenmp" cflags (#2783)"
  setup.py
Labels: cla signed

#3412 Add tests for Caltech101
  test/test_datasets.py
Labels: cla signed

#3413 add tests for CelebA
  test/test_datasets.py
Labels: cla signed

#3415 Add tests for VOC(Segmentation|Detection) and fix existing bugs
  test/fakedata_generation.py
  test/test_datasets.py
  torchvision/datasets/sbd.py
  torchvision/datasets/voc.py
Labels: cla signed, deprecation, module: datasets

#3416 add tests for Coco(Captions|Detection)
  test/test_datasets.py
Labels: cla signed

#3417 improve Coco(Captions|Detection) implementation
  torchvision/datasets/coco.py
Labels: cla signed

#3424 Removed call to optimze_for_mobile
  android/test_app/make_assets.py
Labels: cla signed

#3425 Specify coordinate constraints for box parameters
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/ops/boxes.py
  torchvision/ops/poolers.py
  torchvision/ops/ps_roi_align.py
  torchvision/ops/ps_roi_pool.py
  torchvision/ops/roi_align.py
  torchvision/ops/roi_pool.py
Labels: cla signed

#3418 .circleci: Downgrade CUDA 11.2 -> 11.1
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  packaging/pkg_helpers.bash
  packaging/torchvision/meta.yaml
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#3431 Put back call to optimze_for_mobile
  android/test_app/make_assets.py
Labels: cla signed

#3435 [FBcode->GH] Set `torch.set_deterministic` to false for GPU tests (#3422)
  test/test_transforms_tensor.py
Labels: cla signed

#3411 Add tests for UCF101
  test/datasets_utils.py
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed

#3438 update theme and version styling
  0.8/_static/css/theme.css
  0.8/_static/images/chevron-down-black.svg
  0.8/_static/images/chevron-down-white.svg
  0.8/_static/js/theme.js
  0.8/_static/pygments.css
  0.8/datasets.html
  0.8/genindex.html
  0.8/index.html
  0.8/io.html
  0.8/models.html
  0.8/ops.html
  0.8/py-modindex.html
  0.8/search.html
  0.8/transforms.html
  0.8/utils.html
  versions.html
Labels: cla signed

#3439 [FBcode->GH] Fix to_tensor for accimage backend
  torchvision/transforms/functional.py
Labels: cla signed

#3432 Put back call to optimze_for_mobile
  android/test_app/make_assets.py
Labels: cla signed

#3428 [android][test_app] Cleanup duplicate dependency
  android/test_app/app/build.gradle
Labels: cla signed

#3444 .circleci: Don't install numpy directly
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/smoke_test/docker/Dockerfile
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/linux/scripts/setup_env.sh
  .circleci/unittest/windows/scripts/install.sh
  .circleci/unittest/windows/scripts/setup_env.sh
Labels: cla signed

#3434 Properly fix dataset test that passes by accident
  test/datasets_utils.py
  test/test_datasets.py
Labels: cla signed

#3459 fix **kwargs forwarding in fake data utility functions
  test/datasets_utils.py
Labels: cla signed

#3437 Add version information to docstring of Phototour dataset
  torchvision/datasets/phototour.py
Labels: cla signed

#3450 Improve dataset test infrastructure
  test/datasets_utils.py
Labels: cla signed

#3441 Deprecate _transforms_video and _functional_video
  test/test_transforms_video.py
  torchvision/transforms/_functional_video.py
  torchvision/transforms/_transforms_video.py
Labels: cla signed

#3462 Replace reshape with flatten for mobilenetv2.
  torchvision/models/mobilenetv2.py
Labels: cla signed
