Repository pytorch/vision, pull requests merged in 2021-05, with the labels that each got.

#3764 Update codeql.yml
  .github/workflows/codeql.yml
Labels: cla signed

#3766 Pass custom scales on DefaultBoxGenerator and change default estimation
  test/test_models_detection_anchor_utils.py
  torchvision/models/detection/anchor_utils.py
  torchvision/models/detection/ssd.py
Labels: cla signed, module: models, topic: object detection

#3759 Clean up test accept behaviour
  test/common_utils.py
Labels: code quality, module: tests

#3768 Skip r2plus1d_18 test on linux GPU Circle CI machines
  .circleci/config.yml
  .circleci/config.yml.in
  test/common_utils.py
  test/test_models.py
Labels: cla signed, module: ci, module: tests

#3778 Update CI jobs xcode/macOS version to match PyTorch core
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#3734 Show built doc links directly in PR GUI -- v2
  .github/workflows/show_link_to_built_docs.yml
  CONTRIBUTING.md
Labels: cla signed

#3785 Make reference scripts compatible with submitit
  references/classification/train.py
  references/classification/train_quantization.py
  references/detection/train.py
  references/segmentation/train.py
Labels: cla signed, enhancement, module: reference scripts

#3789 Continue from checkpoint on preemption in reference scripts
  references/detection/train.py
  references/segmentation/train.py
Labels: bug, cla signed, module: reference scripts

#3787 Pin JPEG version to resolve the size_t issue on windows
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/windows/scripts/environment.yml
  packaging/torchvision/meta.yaml
Labels: bug, cla signed, module: ci, module: io, topic: build

#3793 Add auto-augment introduced transforms in docs
  docs/source/transforms.rst
  gallery/plot_transforms.py
Labels: cla signed, module: documentation

#3796 Remove "Show link to docs" GH Action
  .github/workflows/show_link_to_built_docs.yml
  CONTRIBUTING.md
Labels: cla signed

#3679 [android][circle_ci] android build and nightly publish jobs
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .circleci/unittest/android/scripts/binary_android_build.sh
  .circleci/unittest/android/scripts/binary_android_upload.sh
  .circleci/unittest/android/scripts/install_gradle.sh
  android/build.gradle
  android/gradle.properties
  android/ops/build.gradle
  android/test_app/app/build.gradle
Labels: cla signed

#3761 Added antialias option to transforms.functional.resize
  android/ops/CMakeLists.txt
  ios/CMakeLists.txt
  test/test_functional_tensor.py
  test/test_transforms.py
  torchvision/csrc/ops/cpu/interpolate_aa_kernels.cpp
  torchvision/csrc/ops/interpolate_aa.cpp
  torchvision/csrc/ops/interpolate_aa.h
  torchvision/transforms/functional.py
  torchvision/transforms/functional_tensor.py
  torchvision/transforms/transforms.py
Labels: cla signed

#3780 Convert "tensor transforms" notebook into a sphinx-gallery example
  docs/source/transforms.rst
  gallery/assets/dog1.jpg
  gallery/assets/dog2.jpg
  gallery/assets/imagenet_class_index.json
  gallery/plot_scripted_tensor_transforms.py
  gallery/plot_transforms.py
Labels: cla signed, module: documentation, module: transforms

#3629 [iOS] added VisionTestApp for testing vision ops
  .gitignore
  ios/VisionTestApp/VisionTestApp.xcodeproj/project.pbxproj
  ios/VisionTestApp/VisionTestApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/VisionTestApp/VisionTestApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/VisionTestApp/VisionTestApp/AppDelegate.h
  ios/VisionTestApp/VisionTestApp/AppDelegate.m
  ios/VisionTestApp/VisionTestApp/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/VisionTestApp/VisionTestApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/VisionTestApp/VisionTestApp/Assets.xcassets/Contents.json
  ios/VisionTestApp/VisionTestApp/Base.lproj/LaunchScreen.storyboard
  ios/VisionTestApp/VisionTestApp/Base.lproj/Main.storyboard
  ios/VisionTestApp/VisionTestApp/Info.plist
  ios/VisionTestApp/VisionTestApp/ModelRunner.h
  ios/VisionTestApp/VisionTestApp/ModelRunner.mm
  ios/VisionTestApp/VisionTestApp/ViewController.h
  ios/VisionTestApp/VisionTestApp/ViewController.mm
  ios/VisionTestApp/VisionTestApp/main.m
  ios/VisionTestApp/clean.sh
  ios/VisionTestApp/make_assets.py
  ios/VisionTestApp/setup.sh
Labels: cla signed, topic: mobile

#3794 Fix wheel relocation issues on OSX
  packaging/build_wheel.sh
  test/test_ops.py
Labels: cla signed, topic: binaries

#3809 Remove cu101 build
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#3806 Added VisionTestApp for testing vision ops in iOS (#3629)
  .gitignore
  ios/VisionTestApp/VisionTestApp.xcodeproj/project.pbxproj
  ios/VisionTestApp/VisionTestApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/VisionTestApp/VisionTestApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/VisionTestApp/VisionTestApp/AppDelegate.h
  ios/VisionTestApp/VisionTestApp/AppDelegate.m
  ios/VisionTestApp/VisionTestApp/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/VisionTestApp/VisionTestApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/VisionTestApp/VisionTestApp/Assets.xcassets/Contents.json
  ios/VisionTestApp/VisionTestApp/Base.lproj/LaunchScreen.storyboard
  ios/VisionTestApp/VisionTestApp/Base.lproj/Main.storyboard
  ios/VisionTestApp/VisionTestApp/Info.plist
  ios/VisionTestApp/VisionTestApp/ModelRunner.h
  ios/VisionTestApp/VisionTestApp/ModelRunner.mm
  ios/VisionTestApp/VisionTestApp/ViewController.h
  ios/VisionTestApp/VisionTestApp/ViewController.mm
  ios/VisionTestApp/VisionTestApp/main.m
  ios/VisionTestApp/clean.sh
  ios/VisionTestApp/make_assets.py
  ios/VisionTestApp/setup.sh
Labels: cla signed

#3790 Fix inconsistent version pinning across yaml files
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/smoke_test/docker/Dockerfile
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/environment.yml
  .circleci/unittest/windows/scripts/install.sh
  packaging/build_cmake.sh
  packaging/torchvision/meta.yaml
  torchvision/transforms/transforms.py
Labels: cla signed, code quality, module: ci, topic: build

#3792 Support for decoding jpegs on GPU with nvjpeg
  CMakeLists.txt
  setup.py
  test/common_utils.py
  test/test_image.py
  torchvision/csrc/io/image/cuda/decode_jpeg_cuda.cpp
  torchvision/csrc/io/image/cuda/decode_jpeg_cuda.h
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/image/image.h
  torchvision/io/image.py
Labels: cla signed, enhancement, module: io

#3774 Convert "Visualization utilities" notebook into a sphinx-gallery example
  docs/Makefile
  gallery/plot_scripted_tensor_transforms.py
  gallery/plot_visualization_utils.py
  torchvision/utils.py
Labels: cla signed, module: documentation, module: utils

#3810 Added bicubic support for interpolation with AA
  test/test_functional_tensor.py
  torchvision/csrc/ops/cpu/interpolate_aa_kernels.cpp
  torchvision/csrc/ops/interpolate_aa.cpp
  torchvision/csrc/ops/interpolate_aa.h
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#3826 [FBcode->GH] Added dataset download support in fbcode (#3823)
  torchvision/datasets/_utils.py
  torchvision/datasets/utils.py
Labels: cla signed

#3828 Making protected params of MobileNetV3 public
  torchvision/models/detection/ssdlite.py
  torchvision/models/mobilenetv3.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/segmentation/segmentation.py
Labels: cla signed, code quality

#3834 Added Makefile rule to not build the examples
  .gitignore
  CONTRIBUTING.md
  docs/Makefile
Labels: cla signed, module: documentation

#3835 NOMRG Circle CI experiments
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#3839 Remove old css file
  docs/source/_static/css/pytorch_theme.css
  docs/source/conf.py
Labels: code quality

#3838 Show links to notebooks in sphinx-gallery examples
  docs/source/_static/css/custom_torchvision.css
  docs/source/conf.py
Labels: cla signed, module: documentation

#3837 Add cross-PR caching within CircleCI for gallery examples
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed, module: ci, module: documentation

#3845 Port _test_adjust_fn to pytest
  test/test_functional_tensor.py
Labels: cla signed, code quality, module: tests

#3824 Rewrite draw_segmentation_masks and update gallery example to illustrate both instance and semantic segmentation models
  gallery/plot_visualization_utils.py
  test/assets/fakedata/draw_segm_masks_colors_util.png
  test/assets/fakedata/draw_segm_masks_no_colors_util.png
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#3850 Adding some references on MobileNetV3 implementation
  torchvision/models/mobilenetv3.py
Labels: cla signed, code quality

#3851 Update models weights for inception_v3, vgg11, and vgg13
  torchvision/models/inception.py
  torchvision/models/vgg.py
Labels: cla signed, module: models

#3849 correct the size of returned tensor in comments of ps_roi_pool.py and ps_roi_align.py
  torchvision/ops/ps_roi_align.py
  torchvision/ops/ps_roi_pool.py
Labels: bug, cla signed, module: documentation

#3852 Port NMS tests to use pytest
  test/common_utils.py
  test/test_ops.py
Labels: cla signed

#3853 Improvements to models docs
  docs/source/models.rst
  gallery/plot_visualization_utils.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
Labels: cla signed, module: documentation, module: models

#3855 SSDlite documentation fixes
  torchvision/models/detection/ssdlite.py
Labels: cla signed, module: documentation

#3840 add rocm4.2 to nightly wheel builds
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#3842 Added CUDA support for interpolation AA bilinear/bicubic
  test/test_functional_tensor.py
  torchvision/csrc/ops/cuda/interpolate_aa_kernels.cu
Labels: cla signed

#3857 Updated all_gather() to make use of all_gather_object()
  references/detection/utils.py
Labels: cla signed

#3860 fbcode-friendly tests for nvjpeg decoding (#3792)
  test/test_image.py
Labels: cla signed

#3864 [FBcode->GH] Added url to class mapping logic to manifold download
  torchvision/datasets/_utils.py
  torchvision/datasets/utils.py
Labels: cla signed

#3866 Make target argument in transform.py truly optional
  torchvision/models/detection/transform.py
Labels: cla signed, code quality

#3813 Replace byte tensor
  torchvision/transforms/functional.py
Labels: cla signed, code quality, module: transforms

#3867 remove obsolete test/test_datasets_transforms.py
  test/test_datasets_transforms.py
Labels: cla signed

#3869 Change CI cuda versions to 10.2
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
Labels: cla signed, module: ci

#3868 Add CopyButton and minor Improvements Docs
  docs/requirements.txt
  docs/source/conf.py
Labels: cla signed

#3858 addressing #3805: remove deprecated function call
  torchvision/csrc/io/decoder/stream.cpp
Labels: cla signed

#3859 addressing #3805: remove deprecated function call 2
  torchvision/csrc/io/decoder/util.cpp
Labels: cla signed

#3872 Add new assert_equal test util based on torch.testing.assert_close
  test/_assert_utils.py
Labels: cla signed

#3870 Moving tensors to the right device
  .circleci/config.yml
  .circleci/config.yml.in
  torchvision/models/detection/roi_heads.py
  torchvision/transforms/functional_tensor.py
Labels: bug, cla signed

#3874 Use torch.testing.assert_close in test_datasets_samplers.py
  test/test_datasets_samplers.py
Labels: cla signed

#3875 Use torch.testing.assert_close in datasets_video_utils.py
  test/test_datasets_video_utils.py
Labels: cla signed

#3877 Use torch.testing.assert_close in test_image.py
  test/test_image.py
Labels: cla signed

#3878 Use torch.testing.assert_close in test_io.py
  test/test_io.py
Labels: cla signed

#3880 Use torch.testing.assert_close in test_anchor_utils.py
  test/test_models_detection_anchor_utils.py
Labels: cla signed, code quality, module: tests

#3881 Use torch.testing.assert_close in test_detection_utils.py
  test/test_models_detection_utils.py
Labels: cla signed, code quality, module: tests

#3882 Use torch.testing.assert_close in test_onnx.py
  test/test_onnx.py
Labels: cla signed, code quality, module: tests

#3883 Use torch.testing.assert_close in test_ops.py
  test/test_ops.py
Labels: cla signed

#3885 Use torch.testing.assert_close in test_transforms_tensor.py
  test/test_transforms_tensor.py
Labels: cla signed

#3886 Use torch.testing.assert_close in test_transforms_video.py
  test/test_transforms_video.py
Labels: cla signed

#3871 Remove codecov job and dependencies
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/linux/scripts/post_process.sh
  .circleci/unittest/windows/scripts/environment.yml
  .circleci/unittest/windows/scripts/post_process.sh
  README.rst
Labels: cla signed, module: ci

#3786 Replace deprecated AutoNonVariableTypeMode with AutoDispatchBelowADInplaceOrView
  torchvision/csrc/ops/autograd/deform_conv2d_kernel.cpp
  torchvision/csrc/ops/autograd/ps_roi_align_kernel.cpp
  torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp
  torchvision/csrc/ops/autograd/roi_align_kernel.cpp
  torchvision/csrc/ops/autograd/roi_pool_kernel.cpp
Labels: cla signed, module: ops

#3887 Use torch.testing.assert_close in test_utils
  test/test_utils.py
Labels: cla signed

#3888 Use torch.testing.assert_close in test_video_reader.py
  test/test_video_reader.py
Labels: cla signed

#3895 Fix the spacing of labels on draw_bounding_boxes
  test/assets/fakedata/draw_boxes_util.png
  torchvision/utils.py
Labels: bug, cla signed

#3873 Use torch.testing.assert_close in common_utils.py
  test/common_utils.py
Labels: code quality, module: tests

#3896 Fixing SSD and SSDlite docs
  docs/source/models.rst
  gallery/plot_visualization_utils.py
Labels: cla signed, module: documentation

#3900 Fix Android CI
  android/ops/CMakeLists.txt
Labels: bug, cla signed, module: ci

#3897 Change leftover AutoNonVariableTypeMode class.
  ios/VisionTestApp/VisionTestApp/ModelRunner.mm
Labels: cla signed, code quality

#3884 Use torch.testing.assert_close in test_transforms.py
  test/test_transforms.py
Labels: cla signed, code quality, module: tests

#3876 Use torch.testing.assert_close in test_functional_tensor
  test/test_functional_tensor.py
Labels: cla signed, code quality, module: tests

#3879 Use torch.testing.assert_close in test_models.py
  test/test_models.py
Labels: cla signed, code quality, module: tests

#3904 Fix pointer to contiguous data in quantized roi_align
  torchvision/csrc/ops/quantized/cpu/qroi_align_kernel.cpp
Labels: bug, cla signed, module: models.quantization, module: ops

#3907 Refactored and fixed flaky resize tests
  test/test_functional_tensor.py
Labels: cla signed

#3906 Fix bug on detection backbones when trainable_layers == 0
  torchvision/models/detection/backbone_utils.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
Labels: bug, cla signed, module: models, topic: object detection

#3908 Fix write and encode jpeg tests
  test/test_image.py
Labels: cla signed

#3910 Remove unused masks variable in test_image.py
  test/test_utils.py
Labels: cla signed, code quality, module: tests

#3917 Port test/test_utils.py to pytest
  test/test_utils.py
Labels: cla signed

#3791 Fixed audio-video synchronisation problem in read_video() when using `pts` as unit
  test/test_video_reader.py
  torchvision/io/_video_opt.py
  torchvision/io/video.py
Labels: cla signed, topic: video

#3920 [FBcode->GH] Add check_stride=False
  test/test_transforms.py
Labels: module: tests

#3923 Fix installation instructions in contributing guide
  CONTRIBUTING.md
Labels: cla signed, module: documentation

#3925 Bump master versions
  packaging/build_cmake.sh
  packaging/build_conda.sh
  packaging/build_wheel.sh
  version.txt
Labels: cla signed

#3926 Improve model parameterization on tests
  test/test_models.py
Labels: cla signed, code quality, module: tests

#3928 Remove deprecated CI vars
  packaging/wheel/linux_manywheel.sh
  packaging/wheel/osx_wheel.sh
Labels: module: ci

#3927 Update documentation for 0.10.0
  docs/source/conf.py
Labels: cla signed, module: documentation

#3929 Speedup the slow tests of detection models
  test/common_utils.py
  test/expect/ModelTester.test_fasterrcnn_resnet50_fpn_expect.pkl
  test/expect/ModelTester.test_keypointrcnn_resnet50_fpn_expect.pkl
  test/expect/ModelTester.test_maskrcnn_resnet50_fpn_expect.pkl
  test/expect/ModelTester.test_retinanet_resnet50_fpn_expect.pkl
  test/test_models.py
Labels: cla signed, module: models, module: tests

#3930 Port test/test_image.py to pytest
  test/test_image.py
Labels: cla signed, module: tests

#3932 Added check for invalid input file
  test/test_video_reader.py
  torchvision/io/video.py
Labels: cla signed, module: io, module: tests, topic: video

#3922 Port test/test_io.py to pytest
  test/test_io.py
Labels: cla signed, module: tests
