Repository pytorch/vision, pull requests merged in 2021-04, with the labels that each got.

#3631 Fix test_draw_boxes
  test/assets/fakedata/draw_boxes_util.png
  test/test_utils.py
Labels: cla signed, module: tests, module: utils

#3635 Fixed jinja2 environment autoescape to enable select extensions
  .circleci/regenerate.py
Labels: cla signed

#3639 Remove unused imports
  torchvision/models/_utils.py
  torchvision/ops/boxes.py
  torchvision/transforms/functional_pil.py
Labels: cla signed, code quality

#3628 Make DatasetFolder.find_classes public
  torchvision/datasets/folder.py
Labels: cla signed, improvement, module: datasets

#3641 Bump PIL dependency to >=5.3.0 and run 5.3.0 on some CI runs
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
  setup.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_pil.py
Labels: cla signed, module: ci, module: transforms

#3634 Documentation improvements for ops
  torchvision/ops/boxes.py
  torchvision/ops/deform_conv.py
  torchvision/ops/ps_roi_align.py
  torchvision/ops/ps_roi_pool.py
  torchvision/ops/roi_align.py
  torchvision/ops/roi_pool.py
Labels: cla signed, module: documentation, module: ops

#3574 Redirect to correct urls
  torchvision/datasets/celeba.py
  torchvision/datasets/omniglot.py
  torchvision/datasets/sbd.py
  torchvision/datasets/widerface.py
Labels: cla signed

#3625 Added CodeQL and Bandit security checks as GitHub Actions
  .github/workflows/bandit.yml
  .github/workflows/codeql.yml
Labels: cla signed

#3643 Add missing doc for get_video_backend
  torchvision/__init__.py
Labels: cla signed

#3636 Added defusedxml to parse untrusted XML data
  mypy.ini
  torchvision/datasets/voc.py
Labels: cla signed

#3646 Update to transforms docs
  docs/source/transforms.rst
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: cla signed, module: documentation, module: transforms

#3624 Add Quantized version of RoIAlign
  test/test_ops.py
  torchvision/csrc/ops/cpu/roi_align_common.h
  torchvision/csrc/ops/cpu/roi_align_kernel.cpp
  torchvision/csrc/ops/quantized/cpu/qroi_align_kernel.cpp
  torchvision/ops/roi_align.py
Labels: cla signed, improvement, module: models.quantization, module: ops

#3651 Add missing device info on RetinaNet
  torchvision/models/detection/retinanet.py
Labels: bug, cla signed

#3654 Unify onnx and JIT resize implementations
  torchvision/models/detection/transform.py
Labels: cla signed

#3640 Added KITTI dataset
  docs/source/datasets.rst
  test/test_datasets.py
  torchvision/datasets/__init__.py
  torchvision/datasets/kitti.py
Labels: cla signed, module: datasets, new feature

#3647 packaging: Remove pin for jpeg, numpy
  packaging/torchvision/meta.yaml
Labels: cla signed

#3659 Corrected spelling in a Type Error
  torchvision/transforms/transforms.py
Labels: cla signed

#3656 Remove pandas dependency for CelebA dataset
  test/datasets_utils.py
  test/test_datasets.py
  torchvision/datasets/celeba.py
Labels: cla signed, enhancement

#3661 Ported SVHN dataset to new test framework
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed, improvement, module: datasets, module: tests

#3663 [FBcode->GH] Fix spelling in comment
  torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp
Labels: cla signed

#3660 Remove hardcoded dependency version for sphinx
  docs/Makefile
  docs/requirements.txt
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: cla signed, improvement, module: documentation

#3671 Put back error on warnings for sphinx
  docs/Makefile
  torchvision/ops/deform_conv.py
  torchvision/transforms/functional.py
Labels: cla signed, module: documentation

#3672 Fixed floor_divide deprecation warnings seen in pytest output
  test/test_datasets_samplers.py
  torchvision/datasets/celeba.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/roi_heads.py
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#3674 Only sync cuda if cuda available
  references/detection/engine.py
Labels: bug, cla signed, module: reference scripts

#3683 fix docs typo
  torchvision/datasets/fakedata.py
Labels: cla signed

#3684 Fix paper links of VGG models
  torchvision/models/vgg.py
Labels: cla signed, module: documentation, module: models

#3652 Add illustrations of transforms with sphinx-gallery
  .gitignore
  docs/Makefile
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  gallery/README.rst
  gallery/assets/astronaut.jpg
  gallery/plot_transforms.py
Labels: cla signed, improvement, module: documentation, module: transforms

#3689 Update contributing.md about building the docs
  CONTRIBUTING.md
Labels: cla signed, module: documentation

#3686 [FBcode->GH] Fix some tests in fbcode
  test/test_functional_tensor.py
  test/test_models.py
Labels: cla signed, module: models, module: tests, module: transforms

#3691 Fix doc link in README.rst
  README.rst
Labels: cla signed

#3693 Make torchscript parameter constraints more obvious
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: cla signed, module: documentation, module: transforms

#3694 Add examples for RandomPerspective, RandomRotation, and RandomAffine
  gallery/plot_transforms.py
Labels: cla signed

#3665 Ported STL10 dataset's tests to new test framework
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed, improvement, module: datasets, module: tests

#3645 Updates to RoI transforms docs
  torchvision/ops/ps_roi_align.py
  torchvision/ops/ps_roi_pool.py
  torchvision/ops/roi_align.py
  torchvision/ops/roi_pool.py
Labels: cla signed, module: documentation, module: transforms

#3700 Update Google Analytics ID
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: cla signed, module: documentation

#3699 Fix test_random_autocontrast flakyness
  test/common_utils.py
  test/test_transforms_tensor.py
Labels: module: tests, module: transforms

#3697 Refactor test_models to use pytest
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
  test/common_utils.py
  test/test_models.py
Labels: cla signed

#3701 Fix broken link in README
  README.rst
Labels: cla signed, module: documentation

#3698 Add more transform examples in gallery
  gallery/plot_transforms.py
Labels: cla signed, module: documentation, module: transforms

#3704 Various doc fixes for transforms
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: cla signed

#3703 [FBCode->GH] Fix LSUN dataset tests flakyness
  test/test_datasets.py
Labels: cla signed

#3706 Add illustrations for CenterCrop and FiveCrop in gallery example
  gallery/plot_transforms.py
Labels: cla signed

#3715 Fixed a couple of typos
  test/datasets_utils.py
  torchvision/datasets/places365.py
Labels: cla signed, module: documentation

#3710 fix check for exceeded quota on Google Drive
  torchvision/datasets/utils.py
Labels: cla signed

#3705 Ported places365 dataset's tests to the new test framework
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed

#3717 Remove leftover exception
  test/test_models.py
Labels: cla signed

#3718 Revert "Ported places365 dataset's tests to the new test framework"
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed

#3724 Use sphinx-galery 0.9 and simplify conf.py
  docs/requirements.txt
  docs/source/conf.py
Labels: cla signed, module: documentation

#3721 Fix accept mechanism in tests
  test/common_utils.py
Labels: cla signed, module: tests

#3730 Remove fakeroot dependency of Places365 in download tests
  test/test_datasets_download.py
Labels: cla signed, module: datasets, module: tests

#3731 Revert "Revert "Ported places365 dataset's tests to the new test framework""
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed

#3733 Prevent potential bug in DatasetFolder.make_dataset
  torchvision/datasets/folder.py
Labels: bug, cla signed, module: datasets

#3720 Cleaned-up imports in test files related to datasets
  test/datasets_utils.py
  test/fakedata_generation.py
  test/test_datasets.py
Labels: cla signed

#3736 Added download test for KITTI dataset
  test/test_datasets_download.py
Labels: cla signed, module: datasets, module: tests

#3725 Proper error message
  setup.py
Labels: cla signed

#3738 Removed unused import
  test/test_datasets.py
Labels: cla signed

#3727 Add illustrations for AutoAugment in gallery example
  gallery/plot_transforms.py
  torchvision/transforms/autoaugment.py
Labels: cla signed

#3739 Add docs for Interpolation modes
  torchvision/transforms/functional.py
Labels: cla signed

#3740 Remove Many Unused Imports
  torchvision/datasets/hmdb51.py
  torchvision/datasets/ucf101.py
  torchvision/datasets/voc.py
  torchvision/io/_video_opt.py
  torchvision/io/image.py
  torchvision/io/video.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/resnet.py
Labels: cla signed, code quality

#3741 Remove inconsistent FB copyright headers
  test/cpp/test_custom_operators.cpp
  torchvision/csrc/io/decoder/stream.cpp
  torchvision/models/detection/anchor_utils.py
  torchvision/models/detection/generalized_rcnn.py
  torchvision/models/detection/image_list.py
  torchvision/models/detection/rpn.py
  torchvision/ops/poolers.py
Labels: cla signed, code quality

#3744 Rework transforms example in gallery
  gallery/plot_transforms.py
Labels: cla signed, module: documentation, module: transforms

#3732 Expose public methods in docs for datasets
  docs/source/datasets.rst
  torchvision/datasets/folder.py
Labels: cla signed, module: datasets, module: documentation

#3749 [FBcode->GH] Parametrize test_perspective (#3748)
  test/common_utils.py
  test/conftest.py
  test/test_functional_tensor.py
Labels: cla signed

#3750 Keep consistency in Classes ConvBNActivation
  torchvision/models/mobilenetv2.py
Labels: cla signed, code quality

#3745 Removed caching from AnchorGenerator
  torchvision/models/detection/anchor_utils.py
Labels: cla signed, module: models, topic: object detection

#3755 Refactored set_cell_anchors() in AnchorGenerator
  torchvision/models/detection/anchor_utils.py
Labels: cla signed, code quality, module: models, topic: object detection

#3403 Add SSD architecture with VGG16 backbone
  docs/source/models.rst
  references/detection/README.md
  references/detection/presets.py
  references/detection/train.py
  references/detection/transforms.py
  test/expect/ModelTester.test_ssd300_vgg16_expect.pkl
  test/test_models.py
  test/test_models_detection_anchor_utils.py
  test/test_models_detection_negative_samples.py
  torchvision/models/detection/__init__.py
  torchvision/models/detection/_utils.py
  torchvision/models/detection/anchor_utils.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/transform.py
Labels: cla signed, module: models, topic: object detection
