Repository pytorch/vision, pull requests merged in 2021-09, with the labels that each got.

#4340 Update plot_visualization_utils.py
  gallery/plot_visualization_utils.py
Labels: cla signed

#4318 Update sphinx to 3.5.4
  docs/requirements.txt
Labels: module: documentation, cla signed

#4342 Fix Caltech101 docstring renderring
  torchvision/datasets/caltech.py
Labels: module: datasets, module: documentation, cla signed

#4345 Fixed a couple of typos and removed unnecessary bracket
  torchvision/csrc/io/image/cpu/encode_jpeg.cpp
Labels: cla signed

#4341 Explicitely store a distance value that is reused
  torchvision/models/detection/_utils.py
Labels: cla signed

#4335 Adding label smoothing on classification reference
  references/classification/train.py
Labels: enhancement, module: reference scripts, cla signed

#4348 Adding RandAugment implementation
  references/classification/presets.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  torchvision/transforms/autoaugment.py
Labels: module: transforms, new feature, cla signed

#4352 fixed typo in gallery example
  gallery/plot_scripted_tensor_transforms.py
Labels: cla signed

#4362 Small typo on IntermediateLayerGetter
  torchvision/models/detection/backbone_utils.py
Labels: module: documentation, cla signed

#4361 added serialization note to models docs
  docs/source/models.rst
Labels: module: documentation, cla signed

#4363 Fix note about model serialization BC guarantees
  docs/source/models.rst
Labels: module: documentation, cla signed

#4365 Replace "master" with "main" in links to torchvision repo
  gallery/plot_video_api.py
  references/video_classification/README.md
  torchvision/models/video/README.md
  torchvision/transforms/transforms.py
Labels: cla signed

#4221 Integration of TrivialAugment with the current AutoAugment Code
  docs/source/transforms.rst
  gallery/plot_transforms.py
  references/classification/presets.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  torchvision/transforms/autoaugment.py
Labels: module: transforms, new feature, cla signed

#4370 Fix RandAugment and TrivialAugment bugs
  torchvision/transforms/autoaugment.py
Labels: bug, module: transforms, cla signed

#4351 Fixes deform_conv issue with large input/output
  torchvision/csrc/ops/cuda/cuda_helpers.h
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
Labels: module: ops, cla signed

#4372 Resolving tracing problem on StochasticDepth iterator
  torchvision/ops/stochastic_depth.py
Labels: bug, module: ops

#4369 Add typing in GeneralizedRCNNTransform
  torchvision/models/detection/transform.py
Labels: cla signed, code quality

#4302 Add FX feature extraction as an alternative to intermediate_layer_getter
  docs/source/feature_extraction.rst
  docs/source/index.rst
  test/test_backbone_utils.py
  torchvision/models/__init__.py
  torchvision/models/feature_extraction.py
Labels: cla signed

#4373 Make StochasticDepth FX-compatible
  test/test_backbone_utils.py
  torchvision/ops/stochastic_depth.py
Labels: cla signed

#4376 fix fx example so that it works with MaskRCNN
  docs/source/feature_extraction.rst
Labels: cla signed

#4380 [FBcode->GH] [jit] Make operation call accept Stack& instead Stack* (#63414)
  test/cpp/test_custom_operators.cpp
Labels: module: tests, cla signed

#4377 fix splitting CelebA dataset + corresponding test
  test/test_datasets.py
  torchvision/datasets/celeba.py
Labels: module: datasets, cla signed

#4383 Added paper references to detection models
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
Labels: cla signed

#4381 Added Exponential Moving Average support to classification reference script
  references/classification/train.py
  references/classification/utils.py
Labels: module: reference scripts, cla signed

#4390 Clarification for training resnext101_32x8d on ImageNet
  references/classification/README.md
Labels: cla signed

#4375 Deprecate the C++ vision::models namespace
  README.rst
  examples/cpp/hello_world/main.cpp
  examples/cpp/hello_world/trace_model.py
  packaging/build_cmake.sh
  torchvision/csrc/models/alexnet.cpp
  torchvision/csrc/models/densenet.cpp
  torchvision/csrc/models/googlenet.cpp
  torchvision/csrc/models/inception.cpp
  torchvision/csrc/models/mnasnet.cpp
  torchvision/csrc/models/mobilenet.cpp
  torchvision/csrc/models/modelsimpl.h
  torchvision/csrc/models/resnet.h
  torchvision/csrc/models/shufflenetv2.cpp
  torchvision/csrc/models/squeezenet.cpp
  torchvision/csrc/models/vgg.cpp
Labels: cla signed, deprecation, code quality

#4387 add pre-commit hooks for convenient formatting checks
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/linux/scripts/run-clang-format.py
  .circleci/unittest/windows/scripts/install_conda.bat
  .pre-commit-config.yaml
  CONTRIBUTING.md
  android/build.gradle
  android/test_app/app/src/main/res/layout/activity_main.xml
  docs/source/_static/css/custom_torchvision.css
  docs/source/_static/img/pytorch-logo-flame.svg
  docs/source/feature_extraction.rst
  examples/cpp/hello_world/README.rst
  examples/python/README.md
  gallery/README.rst
  gallery/assets/imagenet_class_index.json
  ios/VisionTestApp/VisionTestApp/ViewController.h
  packaging/vs2017/install_activate.bat
  packaging/vs2019/install_activate.bat
  references/classification/README.md
  references/detection/README.md
  test/test_video_reader.py
Labels: cla signed

#4388 rm install_cuda_compatible_cmath
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/scripts/vs_install_cmath.ps1
Labels: cla signed

#4394 Overwrite the existing dlls while unzipping
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#4396 Change versions.html to main
  versions.html
Labels: cla signed

#4400 fix MacOS cmake workflow (#4203)
  packaging/build_cmake.sh
Labels: cla signed

#4401 Fix for macos wheel build by ignoring missing dependencies after delocate version update (#4201)
  packaging/build_wheel.sh
Labels: cla signed

#4399 [v0.10.1] .circleci: Bump version for pytorch 1.9.1
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#4404 remove unused package in coco_eval.py
  references/detection/coco_eval.py
Labels: cla signed

#4406 Added update_parameters to EMA to fix calculation
  references/classification/utils.py
Labels: module: reference scripts, cla signed

#4407 Updated model-ema-decay default to 0.9
  references/classification/train.py
Labels: module: reference scripts, cla signed

#4255 Added LFW Dataset
  docs/source/datasets.rst
  test/test_datasets.py
  torchvision/datasets/__init__.py
  torchvision/datasets/lfw.py
Labels: module: datasets, cla signed

#4408 Update the metrics output on reference scripts
  references/classification/train.py
Labels: module: reference scripts, cla signed

#4410 Ignore platforms other than Linux for ffmpeg
  setup.py
Labels: module: video, cla signed

#4416 Updated annotation to be a Union of Tensor and List
  torchvision/ops/_utils.py
  torchvision/ops/roi_align.py
  torchvision/ops/roi_pool.py
Labels: cla signed, code quality

#4379 Adding Mixup and Cutmix
  references/classification/train.py
  references/classification/transforms.py
  references/classification/utils.py
  test/test_transforms.py
  torchvision/transforms/transforms.py
Labels: module: reference scripts, new feature, cla signed

#4414 add prototype implementation for MNIST and CIFAR
  .github/workflows/test.yml
  test/prototype/datasets/dataset_mocks.py
  test/prototype/datasets/test_datasets.py
  torchvision/prototype/__init__.py
  torchvision/prototype/datasets/__init__.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/cifar.py
  torchvision/prototype/datasets/_builtin/mnist.py
  torchvision/prototype/datasets/datapipes.py
  torchvision/prototype/datasets/decoder.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_helpers.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: cla signed

#4409 TensorRT compatible retinanet
  torchvision/models/detection/anchor_utils.py
Labels: module: models, topic: object detection, cla signed

#4423 [PROTOTYPE] Refactor DatasetConfig and add tests
  test/prototype/datasets/test_builtin_datasets.py
  test/prototype/datasets/test_utils.py
  torchvision/prototype/datasets/utils/_dataset.py
Labels: cla signed

#4417 Skip building torchvision with ffmpeg when python==3.9
  setup.py
  test/common_utils.py
  test/test_video_reader.py
  test/test_videoapi.py
Labels: module: tests, topic: build, cla signed

#4424 [PROTOTYPE] Fix tests
  torchvision/prototype/datasets/_builtin/mnist.py
Labels: cla signed

#4413 Enable building torchvision with ffmpeg regardless of version on Linux
  setup.py
Labels: cla signed

#4428 [PROTOTYPE] add more tests for utils and core API
  .github/workflows/test.yml
  test/prototype/datasets/dataset_mocks.py
  test/prototype/datasets/test_api.py
  test/prototype/datasets/test_builtin_datasets.py
  test/prototype/datasets/test_utils.py
  torchvision/io/video.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/cifar.py
  torchvision/prototype/datasets/_builtin/mnist.py
  torchvision/prototype/datasets/decoder.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_helpers.py
  torchvision/prototype/datasets/utils/_internal.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: cla signed

#4431 [PROTOTYPE] add Caltech256 dataset
  test/prototype/datasets/dataset_mocks.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/caltech256.py
Labels: cla signed

#4432 [PROTOTYPE] add support for categories in DatasetInfo
  setup.py
  test/prototype/datasets/conftest.py
  test/prototype/datasets/test_api.py
  test/prototype/datasets/test_utils.py
  torchvision/prototype/datasets/__init__.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/caltech256.categories
  torchvision/prototype/datasets/_builtin/caltech256.py
  torchvision/prototype/datasets/_builtin/cifar.py
  torchvision/prototype/datasets/_builtin/cifar10.categories
  torchvision/prototype/datasets/_builtin/cifar100.categories
  torchvision/prototype/datasets/_builtin/mnist.py
  torchvision/prototype/datasets/_home.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_helpers.py
  torchvision/prototype/datasets/utils/_internal.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: cla signed

#4411 Warmup schedulers in References
  references/classification/train.py
  references/detection/engine.py
  references/detection/utils.py
  references/segmentation/train.py
  references/segmentation/transforms.py
  references/video_classification/scheduler.py
  references/video_classification/train.py
Labels: module: reference scripts, cla signed

#4439 Fix size_t issues across JPEG versions and platforms
  torchvision/csrc/io/image/cpu/encode_jpeg.cpp
Labels: cla signed

#4419 FIX CMAKE_WINDOWS_GPU workflow
  .circleci/unittest/windows/scripts/set_cuda_envs.sh
  packaging/build_cmake.sh
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#4451 updated Readme.md files with torchrun
  references/classification/README.md
  references/detection/README.md
  references/segmentation/README.md
  references/video_classification/README.md
Labels: module: reference scripts, module: documentation, cla signed

#4442 Conda: Add numpy dependency
  packaging/torchvision/meta.yaml
Labels: cla signed

#4453 Cleaned-up coco evaluation code
  references/detection/coco_eval.py
Labels: module: reference scripts, cla signed

#4327 Allow gradient backpropagation through GeneralizedRCNNTransform to inputs
  test/test_models.py
  torchvision/models/detection/transform.py
Labels: enhancement, module: models, cla signed

#4448 Allow custom activation in SqueezeExcitation of EfficientNet
  torchvision/models/efficientnet.py
Labels: module: models, cla signed

#4290 `masks_to_bounding_boxes` op
  docs/requirements.txt
  docs/source/ops.rst
  gallery/plot_repurposing_annotations.py
  test/assets/labeled_image.png
  test/assets/masks.tiff
  test/test_masks_to_boxes.py
  torchvision/ops/__init__.py
  torchvision/ops/boxes.py
Labels: cla signed

#4454 make tests that involve GDrive more robust
  test/test_datasets_utils.py
  test/test_internet.py
Labels: module: tests, cla signed

#4444 Further enhance Classification Reference
  references/classification/train.py
  references/segmentation/train.py
  references/video_classification/train.py
Labels: module: reference scripts, cla signed

#4457 Update docstring for RandAugment
  torchvision/transforms/autoaugment.py
Labels: module: documentation, cla signed

#4441 add prototype image folder dataset
  torchvision/prototype/__init__.py
  torchvision/prototype/datasets/__init__.py
  torchvision/prototype/datasets/_folder.py
  torchvision/prototype/datasets/decoder.py
Labels: module: datasets, cla signed, prototype

#4469 Rewrite test and fix masks_to_boxes implementation
  test/test_masks_to_boxes.py
  test/test_ops.py
  torchvision/ops/boxes.py
Labels: bug, module: ops, cla signed

#4477 Added gray images support for `adjust_contrast`
  test/common_utils.py
  test/test_functional_tensor.py
  torchvision/transforms/functional_tensor.py
Labels: enhancement, module: transforms, cla signed

#4473 add API for new style datasets
  torchvision/prototype/datasets/__init__.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_home.py
  torchvision/prototype/datasets/decoder.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_internal.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: module: datasets, cla signed, prototype

#4479 Removed tests executing deprecated F_t.center/five/ten_crop methods
  test/test_functional_tensor.py
Labels: cla signed

#4475 update cuda version in unittest_windows_gpu
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/windows/scripts/install.sh
Labels: cla signed

#4482 [CircleCI] s/gpu.small/gpu.nvidia.small/
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#4481 Replaced ToTensor with a combination of PILToTensor and ConvertImageDtype
  references/classification/presets.py
Labels: module: reference scripts, cla signed, code quality

#4478 Update gpu atomics include path
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_align_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_pool_kernel.cu
  torchvision/csrc/ops/cuda/roi_align_kernel.cu
  torchvision/csrc/ops/cuda/roi_pool_kernel.cu
Labels: cla signed

#4480 Added gray image support to `adjust_saturation` function
  test/common_utils.py
  test/test_functional_tensor.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  torchvision/transforms/autoaugment.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_tensor.py
  torchvision/transforms/transforms.py
Labels: enhancement, module: transforms, module: documentation, cla signed

#4490 Bump main trunk version to 0.12
  packaging/build_cmake.sh
  packaging/build_conda.sh
  packaging/build_wheel.sh
  version.txt
Labels: cla signed

#4382 Added documentation for video backend
  README.rst
Labels: module: documentation, cla signed

#4494 Replaced example usage of ToTensor() by PILToTensor() + ConvertImageDtype()
  torchvision/transforms/transforms.py
Labels: cla signed

#4421 enable windows cuda unit tests
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/windows/scripts/install.sh
  .circleci/unittest/windows/scripts/run_test.sh
  .circleci/unittest/windows/scripts/set_cuda_envs.sh
  packaging/windows/internal/cuda_install.bat
  packaging/windows/internal/driver_update.bat
Labels: cla signed

#4471 cleanup prototype datasets
  torchvision/prototype/datasets/__init__.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_folder.py
  torchvision/prototype/datasets/_home.py
  torchvision/prototype/datasets/decoder.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_internal.py
Labels: module: datasets, cla signed, prototype

#4484 Rewrite gallery example for masks to boxes.
  docs/source/ops.rst
  docs/source/utils.rst
  gallery/assets/FudanPed00054.png
  gallery/assets/FudanPed00054_mask.png
  gallery/plot_repurposing_annotations.py
Labels: cla signed

#4472 Add JIT tests for box_area, box_iou, genaralized_box_iou
  test/test_ops.py
Labels: cla signed

#4501 Fix bot that pings us when PR labels are missing
  .github/workflows/pr-labels.yml
Labels: cla signed

#4497 Prevent tests from leaking their respective RNG
  test/conftest.py
  test/test_transforms_tensor.py
Labels: module: tests, cla signed, code quality

#4487 Replace MobileNetV3's SqueezeExcitation with EfficientNet's one
  torchvision/models/mobilenetv3.py
  torchvision/models/quantization/mobilenetv3.py
Labels: module: ops, module: models, cla signed, code quality

#4503 Fix minor typo in bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: module: documentation, cla signed

#4403 Add RegNet Architecture in TorchVision
  docs/source/models.rst
  hubconf.py
  references/classification/README.md
  test/expect/ModelTester.test_regnet_x_16gf_expect.pkl
  test/expect/ModelTester.test_regnet_x_1_6gf_expect.pkl
  test/expect/ModelTester.test_regnet_x_32gf_expect.pkl
  test/expect/ModelTester.test_regnet_x_3_2gf_expect.pkl
  test/expect/ModelTester.test_regnet_x_400mf_expect.pkl
  test/expect/ModelTester.test_regnet_x_800mf_expect.pkl
  test/expect/ModelTester.test_regnet_x_8gf_expect.pkl
  test/expect/ModelTester.test_regnet_y_16gf_expect.pkl
  test/expect/ModelTester.test_regnet_y_1_6gf_expect.pkl
  test/expect/ModelTester.test_regnet_y_32gf_expect.pkl
  test/expect/ModelTester.test_regnet_y_3_2gf_expect.pkl
  test/expect/ModelTester.test_regnet_y_400mf_expect.pkl
  test/expect/ModelTester.test_regnet_y_800mf_expect.pkl
  test/expect/ModelTester.test_regnet_y_8gf_expect.pkl
  torchvision/models/__init__.py
  torchvision/models/regnet.py
Labels: cla signed

#4505 Change transforms gallery thumbnail
  gallery/assets/repurposing_annotations_thumbnail.png
  gallery/assets/transforms_thumbnail.png
  gallery/assets/visualization_utils_thumbnail.png
  gallery/plot_repurposing_annotations.py
  gallery/plot_transforms.py
  gallery/plot_visualization_utils.py
Labels: module: documentation, cla signed

#4504 Moving common layers to ops
  torchvision/models/_utils.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/regnet.py
  torchvision/ops/misc.py
Labels: module: ops, module: models, cla signed, code quality

#4499 add torchdata as prototype dependency
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
  mypy.ini
  torchvision/prototype/datasets/__init__.py
Labels: cla signed

#4510 add prototypes for `Caltech(101|256)` datasets
  setup.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_builtin/caltech101.categories
  torchvision/prototype/datasets/_builtin/caltech256.categories
  torchvision/prototype/datasets/decoder.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_internal.py
Labels: module: datasets, cla signed, prototype

#4495 Added PILToTensor and ConvertImageDtype classes in reference scripts
  references/detection/presets.py
  references/detection/transforms.py
  references/segmentation/presets.py
  references/segmentation/transforms.py
Labels: module: transforms, module: reference scripts, cla signed, code quality
