Repository pytorch/vision, pull requests merged in 2021-06, with the labels that each got.

#3936 Speed up Transformations tests
  test/test_transforms.py
  test/test_transforms_tensor.py
Labels: cla signed, improvement, module: tests, module: transforms

#3939 Faster dataset indexing
  torchvision/datasets/folder.py
Labels: Perf, cla signed, module: datasets

#3933 Turn on fast gradcheck for DeformConv
  test/test_ops.py
Labels: cla signed, improvement, module: tests

#3942 [FBcode->GH] Fix DeformConvTester::test_backward_cuda
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
Labels: cla signed

#3943 Fix clang formatting in deform_conv2d_kernel.cu
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
Labels: cla signed

#3861 addressing #3805: remove deprecated function call 3
  torchvision/csrc/io/decoder/audio_stream.cpp
  torchvision/csrc/io/decoder/decoder.cpp
Labels: cla signed, module: io, topic: video

#3944 Document minimum required shapes for classification model builder.
  torchvision/models/alexnet.py
  torchvision/models/densenet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/squeezenet.py
  torchvision/models/vgg.py
Labels: cla signed, improvement, module: documentation

#3946 Remove TransformsTester
  test/common_utils.py
  test/test_functional_tensor.py
  test/test_transforms_tensor.py
Labels: code quality, module: tests, module: transforms

#3950 port adjusts in test_transforms to pytest
  test/test_transforms.py
Labels: cla signed, module: tests

#3947 Take assertExpected and check_jit_scriptable out of the TestCase class
  test/common_utils.py
  test/test_models.py
Labels: cla signed, code quality, module: models, module: tests

#3954 Port test pad in test_transforms to pytest
  test/test_transforms.py
Labels: cla signed

#3955 Port Group O test to pytest ref #3945
  test/test_transforms.py
Labels: cla signed

#3953 Port test_ops.py to pytest
  test/test_ops.py
Labels: cla signed

#3894 Cleanup Docs and Add Index
  docs/source/conf.py
  docs/source/index.rst
Labels: cla signed, module: documentation

#3957 port tests in test_transforms to pytest
  test/test_transforms.py
Labels: cla signed

#3962 Port grayscale tests in test_tranforms to pytest
  test/test_transforms.py
Labels: cla signed

#3948 Fixed read_image bug
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_png.cpp
Labels: cla signed, module: io, module: tests

#3967 Change 'range' in docstrings of 'normalize' to 'value_range'.
  torchvision/utils.py
Labels: cla signed

#3964 Port group H test_transforms.py to pytest
  test/test_transforms.py
Labels: cla signed

#3961 Add warning for files with corrupt containers
  torchvision/io/video.py
Labels: cla signed

#3863 Add Docs for `VisionDataset`
  docs/source/datasets.rst
  torchvision/datasets/vision.py
Labels: cla signed, module: documentation

#3952 Port test resize in test_transforms to pytest
  test/test_transforms.py
Labels: cla signed

#3966 Port to_tensor tests in test_transforms to pytest
  test/test_transforms.py
Labels: cla signed

#3971 Refactor test random horizontal flip
  test/test_transforms.py
Labels: cla signed

#3972 Port some test_random_xxx in test_transforms to pytest
  test/test_transforms.py
Labels: cla signed

#3959 Port Group A test_transforms.py to pytest
  test/test_transforms.py
Labels: cla signed

#3977 port tests in test_functional_tensor to pytest
  test/test_functional_tensor.py
Labels: cla signed

#3974 port pad, resized_crop and affine in test_functional_tensor to pytest
  test/test_functional_tensor.py
Labels: cla signed

#3978 Port test_models to pytest
  test/test_models.py
Labels: cla signed

#3976 Prepare test_transforms_tensor.py for porting to pytest
  test/test_transforms_tensor.py
Labels: cla signed, code quality, module: tests, module: transforms

#3983 Port test_rotate in test_functional_tensor.py to pytest
  test/test_functional_tensor.py
Labels: cla signed

#3989 Revert "addressing #3805: remove deprecated function call 3"
  torchvision/csrc/io/decoder/audio_stream.cpp
  torchvision/csrc/io/decoder/decoder.cpp
Labels: cla signed

#3988 Refactor test hsv2rgb
  test/test_functional_tensor.py
Labels: code quality, module: tests, module: transforms

#3990 Finish porting test_functional_tensor.py to pytest
  test/test_functional_tensor.py
Labels: code quality, module: tests, module: transforms

#3991 Port test_backbone_utils.py to pytest
  test/test_backbone_utils.py
Labels: cla signed, code quality, module: models, module: tests

#3985 port test_accimage_xxx in test_transforms to pytest
  test/test_transforms.py
Labels: cla signed

#3984 Port affine transform tests in test_tranforms to pytest
  test/test_transforms.py
Labels: cla signed, code quality, module: tests, module: transforms

#3981 Group G,Group D
  test/test_transforms.py
Labels: cla signed

#4007 Fixed comparison warnings in audio_stream and video_stream
  torchvision/csrc/io/decoder/audio_stream.cpp
  torchvision/csrc/io/decoder/video_stream.cpp
Labels: cla signed, code quality, module: video

#3993 ping maintainers in case a PR was not properly labeled
  .github/process_pr.py
  .github/workflows/pr-labels.yml
Labels: cla signed

#4012 fix syntax in PR labels workflow
  .github/workflows/pr-labels.yml
Labels: cla signed

#4011 Ignore mypy's missing import warning for requests
  torchvision/datasets/utils.py
Labels: cla signed, module: ci

#4013 [skip ci] fix name of script for PR label processing
  .github/workflows/pr-labels.yml
Labels: cla signed

#4002 Skip CPU-only tests on CircleCI machines with GPU
  .circleci/config.yml
  .circleci/config.yml.in
  test/common_utils.py
Labels: cla signed

#4015 [skip CI] test PR for label-checking workflow
  foo
Labels: cla signed

#4016 [skip CI] fix PR labels processing logic
  .github/process_pr.py
Labels: cla signed

#4017 [skip CI] try fix trigger for unlabeled PR pings
  .github/workflows/pr-labels.yml
Labels: cla signed

#4018 [skip CI] remove quotes around users ping
  .github/workflows/pr-labels.yml
Labels: cla signed

#4019 [skip CI] cleanup PR labeling workflow
  .github/process_commit.py
  .github/workflows/pr-labels.yml
Labels: cla signed

#4008 [pytest port] color_jitter, pad, crop, center_crop in test_transforms_tensor
  test/test_transforms_tensor.py
Labels: cla signed, code quality, module: tests, module: transforms

#4014 [CI] mypy install missing stubs
  .circleci/config.yml
  .circleci/config.yml.in
  torchvision/datasets/utils.py
Labels: cla signed, module: ci

#4020 [skip CI] fix ping message for unlabeled PRs
  .github/workflows/pr-labels.yml
Labels: cla signed

#4000 Port random affine, rotate, perspective and to_grayscale to pytest
  test/test_transforms_tensor.py
Labels: cla signed

#4021 Fix workflow for pinging maintainers in case of unlabeled PRs
  .github/process_commit.py
  .github/workflows/pr-labels.yml
Labels: cla signed

#4010 [pytest port] test{crop_five, crop_ten, resize, resized_crop} in test_transforms_tensor
  test/test_transforms_tensor.py
Labels: cla signed, code quality, module: tests, module: transforms

#4023 Port normalize, linear_transformation, compose, random_apply, gaussian_blur to pytest
  test/test_transforms_tensor.py
Labels: cla signed

#4026 Group E test_transforms.py port to pytest
  test/common_utils.py
  test/test_transforms.py
Labels: cla signed, code quality, module: tests, module: transforms

#4027 Drop virtual from private member functions of Decoder class
  torchvision/csrc/io/decoder/decoder.h
Labels: cla signed, module: video

#4003 Fixed some ffmpeg deprecation warnings in decoder
  torchvision/csrc/io/decoder/decoder.cpp
Labels: cla signed, code quality, module: video

#4028 Fixed typo in audio_sampler
  torchvision/csrc/io/decoder/audio_sampler.cpp
Labels: cla signed, module: video

#3680 Download and Kinetics 400/600/700 Datasets
  test/datasets_utils.py
  test/test_datasets.py
  test/test_datasets_download.py
  torchvision/datasets/__init__.py
  torchvision/datasets/kinetics.py
Labels: cla signed, module: datasets, new feature

#4035 Port test_datasets_video_utils.py to pytest
  test/test_datasets_video_utils.py
Labels: cla signed

#4036 port test_models_detection_utils.py to pytest
  test/test_models_detection_utils.py
Labels: cla signed

#4038 Port test_hub.py to pytest
  .circleci/config.yml
  .circleci/config.yml.in
  test/test_hub.py
Labels: cla signed

#4034 Port test_quantized_models.py to pytest
  test/test_models.py
  test/test_quantized_models.py
Labels: cla signed, code quality, module: models, module: tests

#3996 Porting to pytest
  test/test_transforms_tensor.py
Labels: cla signed

#4037 Port test_datasets_samplers.py to pytest
  test/test_datasets_samplers.py
Labels: cla signed

#4043 bug-fix to issue #4042
  torchvision/utils.py
Labels: bug, cla signed, module: utils

#4047 Port test_onnx.py to pytest
  .circleci/config.yml
  .circleci/config.yml.in
  test/test_onnx.py
Labels: cla signed

#4040 Port tests in test_transforms_video.py to pytest
  test/test_transforms_video.py
Labels: cla signed

#4046 Port test_models_detection_anchor_utils.py to pytest
  test/test_models_detection_anchor_utils.py
Labels: cla signed, code quality, module: models, module: tests

#4045 Port test_models_detection_negative_samples.py to pytest
  test/test_models_detection_negative_samples.py
Labels: cla signed, code quality, module: models, module: tests

#3998 add filter for binary_linux_wheel_py3.7_cpu
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#4049 Better handling of grayscale images in draw bbox
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed, code quality, module: utils

#4050 Removed test_audio_video_sync as it doesn't work as expected
  test/test_video_reader.py
Labels: cla signed, module: tests, module: video

#4041 Added warning message for unsupported ffmpeg version
  setup.py
Labels: cla signed, topic: build, version incompatibility

#4025 Better logic for ignoring CPU tests on GPU machines
  test/common_utils.py
  test/conftest.py
  test/test_image.py
  test/test_models.py
  test/test_ops.py
  test/test_transforms_tensor.py
Labels: cla signed, module: ci, module: tests

#4032 Port test_internet.py to pytest and add new pytest-mock dependency
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/windows/scripts/environment.yml
  CONTRIBUTING.md
  test/test_internet.py
Labels: cla signed

#4053 always run build_docs in CI
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#4059 fixup '*' -> '/.*/' for CI filter
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#3934 Fixed missing audio with video_reader backend
  test/test_video_reader.py
  torchvision/io/_video_opt.py
Labels: cla signed, module: io, module: video

#4030 Refactor test_transforms.py into classes
  test/test_transforms.py
Labels: cla signed, code quality, module: tests, module: transforms

#4060 backport fixes to build/push docs on tags
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#4065 Remove special versioning suffix rules for CUDA 10.2
  packaging/pkg_helpers.bash
Labels: cla signed

#4067 [android] Add mavenCentral repository for release publishing
  android/ops/build.gradle
  android/test_app/app/build.gradle
Labels: cla signed

#4055 [iOS] podspec file for Cocoapods release, pod name: LibTorchvision
  ios/LibTorchvision.podspec
Labels: cla signed

#4072 Add comments to not change load_state_dict_from_url imports
  torchvision/models/utils.py
Labels: code quality

#4074 [iOS] podspec file for Cocoapods release, pod name: LibTorchvision
  ios/LibTorchvision.podspec
Labels: cla signed, topic: mobile

#4062 [FBcode->GH] Better logic for ignoring CPU tests on GPU CI machines (#4025)
  test/conftest.py
  test/test_image.py
Labels: fb-exported, module: tests

#4073 [FBcode->GH] Allow all torchvision test rules to run with RE
  test/conftest.py
Labels: cla signed

#4079 Make DeformConv2d scriptable
  test/test_ops.py
  torchvision/ops/deform_conv.py
Labels: bug, cla signed, module: ops, torchscript

#4080 [FBcode->GH] Support opt mode for torchvision ops
  torchvision/_register_extension.py
  torchvision/extension.py
  torchvision/io/_video_opt.py
  torchvision/io/image.py
Labels: cla signed

#4081 Only tag merger if PR isn't properly labeled
  .github/process_commit.py
  .github/workflows/pr-labels.yml
Labels: cla signed

#3918 Replace torch.lstsq with torch.linalg.lstsq
  torchvision/transforms/functional.py
Labels: cla signed, code quality

#3409 Update train.py
  references/video_classification/train.py
Labels: cla signed

#3662 Add test to check that classification models are FX-compatible
  test/test_models.py
Labels: cla signed

#4089 Fix training model instructions in references/classification
  references/classification/README.md
Labels: cla signed, enhancement, module: documentation

#4090 [FBcode->GH] Enable analytics logging for MNIST and CIFAR
  torchvision/datasets/cifar.py
  torchvision/datasets/mnist.py
Labels: cla signed, module: datasets

#4082 ci: Remove mentions of conda-forge
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/environment.yml
  .circleci/unittest/windows/scripts/install.sh
  CONTRIBUTING.md
  packaging/build_conda.sh
  packaging/pkg_helpers.bash
  packaging/torchvision/meta.yaml
Labels: cla signed, topic: binaries, topic: build

#4097 Add bzip2 file compression support
  test/test_datasets_utils.py
  torchvision/datasets/utils.py
Labels: cla signed, enhancement, module: datasets

#4075 supoort single color in utils.draw_bounding_boxes
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed, enhancement, module: utils

#4099 Add support for files with periods in name
  test/test_datasets_utils.py
  torchvision/datasets/utils.py
Labels: cla signed, enhancement, module: datasets

#4101 Raise proper error when deconding 16-bits jpegs
  torchvision/csrc/io/image/cpu/decode_png.cpp
Labels: bug, cla signed, module: io

#4109 Fix _quota_exceeded check and gdrive download
  torchvision/datasets/utils.py
Labels: bug, cla signed, module: datasets

#4114 Port test_datasets_utils to pytest
  test/common_utils.py
  test/test_datasets_utils.py
Labels: cla signed

#4121 Fix current CI failures
  test/test_models.py
Labels: bug, cla signed, module: tests

#4130 [FBcode->GH] Remove torchvision/test/fakedata_generation.py
  test/fakedata_generation.py
Labels: code quality, module: tests

#4131 Add check for fx compatibility on segmentation and video models
  test/test_models.py
Labels: cla signed, module: tests

#4132 Fix documentation for SSD and RetinaNet
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
Labels: bug, cla signed, module: documentation

#4118 use from_blob to avoid memcpy
  torchvision/csrc/io/image/cpu/encode_jpeg.cpp
Labels: cla signed, code quality, module: io

#4133 README: update torch/torchvision support table
  README.rst
Labels: cla signed

#4138 Minor additions to Resize docs
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: cla signed, enhancement, module: documentation
