Repository pytorch/vision, pull requests merged in 2021-08, with the labels that each got.

#4233 Pytest for test_videoapi.py and test_video_reader.py
  test/common_utils.py
  test/test_video_reader.py
  test/test_videoapi.py
Labels: cla signed

#4241 Port 'examples/python/video_api.ipynb' to gallery
  gallery/plot_video_api.py
Labels: cla signed

#4246 Avoid cmyk images in nvjpeg tests
  test/test_image.py
Labels: bug, cla signed, module: tests

#4211 [2/2] Added backward pass on CUDA for interpolation with anti-alias option
  test/test_functional_tensor.py
  torchvision/csrc/ops/cuda/interpolate_aa_kernels.cu
Labels: cla signed

#4256 Use torch instead of scipy for random initialization of inception and googlenet weights
  test/expect/ModelTester.test_googlenet_expect.pkl
  test/expect/ModelTester.test_inception_v3_expect.pkl
  torchvision/models/googlenet.py
  torchvision/models/inception.py
Labels: module: models, cla signed, code quality, bc-breaking

#4254 ffmpeg version query
  setup.py
Labels: cla signed

#4250 using `np.random.RandomState(seed)` instead of `np.random.seed(seed)`
  test/common_utils.py
  test/test_datasets.py
  test/test_image.py
  test/test_transforms.py
  test/test_transforms_video.py
Labels: cla signed

#4248 Add CUDA-11.3 builds to torchvision
  .circleci/config.yml
  .circleci/regenerate.py
  .gitattributes
  packaging/pkg_helpers.bash
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#4251 Indicate which Kitti dataset we're vendoring
  torchvision/datasets/kitti.py
Labels: cla signed

#4268 deinterlacing PNG images with read_image
  test/assets/interlaced_png/wizard_low-interlaced.png
  test/assets/interlaced_png/wizard_low.png
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_png.cpp
Labels: bug, module: io, cla signed

#4239 Add docs to LSUN dataset to install lmdb package
  torchvision/datasets/lsun.py
Labels: enhancement, module: datasets, module: documentation

#4258 More robust assertion checks in test_to_tensor_video
  test/test_transforms_video.py
Labels: module: tests, module: video, code quality

#4236 Added missing typing annotations to transforms/functional_tensor
  mypy.ini
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#4226 Added typing annotations to transforms/autoaugment
  mypy.ini
  torchvision/transforms/autoaugment.py
Labels: cla signed

#3754 [docs] descriptive comments of the decoder C++ api
  torchvision/csrc/io/decoder/audio_stream.cpp
  torchvision/csrc/io/decoder/decoder.cpp
  torchvision/csrc/io/decoder/stream.cpp
  torchvision/csrc/io/decoder/video_sampler.cpp
  torchvision/csrc/io/decoder/video_stream.cpp
Labels: cla signed

#4283 Fix unnecessary backbone weights download on lraspp_mobilenet_v3_large
  torchvision/models/segmentation/segmentation.py
Labels: bug, module: models, topic: object detection, cla signed

#4284 Skip test if connection issues on fate
  test/test_videoapi.py
Labels: module: tests, cla signed

#4285 Make torch version check numeric
  setup.py
Labels: enhancement, topic: build, cla signed

#4280 Replace get_tmp_dir() with tmpdir fixture in pytest
  test/common_utils.py
  test/test_datasets_download.py
  test/test_datasets_samplers.py
  test/test_datasets_utils.py
  test/test_datasets_video_utils.py
  test/test_image.py
  test/test_internet.py
  test/test_io.py
  test/test_transforms_tensor.py
Labels: cla signed

#4234 Added typing annotations to transforms/functional_pil
  torchvision/transforms/functional_pil.py
Labels: cla signed

#4291 remove dependency for dtype getters
  test/common_utils.py
Labels: module: tests, dependency issue, cla signed

#4288 Unpinned the libjpeg version and fixed jpeg_mem_dest's size type Wind…
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/windows/scripts/environment.yml
  packaging/torchvision/meta.yaml
  torchvision/csrc/io/image/cpu/encode_jpeg.cpp
Labels: topic: build, dependency issue, cla signed

#4301 Add StochasticDepth implementation
  docs/source/ops.rst
  test/test_ops.py
  torchvision/ops/__init__.py
  torchvision/ops/stochastic_depth.py
Labels: module: ops, new feature, cla signed

#4306 Prep change for changing def branch to main
  .circleci/build_docs/commit_docs.sh
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .github/workflows/bandit.yml
  .github/workflows/codeql.yml
  CONTRIBUTING.md
  README.rst
  android/gradle.properties
  docs/source/conf.py
  test/test_cpp_models.py
  torchvision/__init__.py
Labels: cla signed, ciflow/default

#4227 Added typing annotations to models/segmentation
  torchvision/models/segmentation/_utils.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/segmentation/segmentation.py
Labels: cla signed

#4229 Added typing annotations to models/video
  torchvision/models/video/resnet.py
Labels: cla signed

#4308 fix dependency table
  README.rst
Labels: cla signed

#4299 New issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/questions-help-support.md
Labels: cla signed

#4224 Added typing annotations to io/__init__
  torchvision/io/__init__.py
Labels: cla signed

#4232 Add typing annotations to models/quantization
  mypy.ini
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/quantization/utils.py
Labels: cla signed

#4337 Correct typo (Update transforms.rst)
  docs/source/transforms.rst
Labels: cla signed

#4338 Refactor AutoAugment to support more augmentations
  torchvision/transforms/autoaugment.py
Labels: module: transforms, cla signed, code quality
