Repository pytorch/vision, pull requests merged in 2022-12, with the labels that each got.

#6999 Add shebang to bash script to make internal linter happy
  packaging/post_build_script.sh
  packaging/pre_build_script.sh
Labels: cla signed

#6996 Adding _ops and _weight_size metadata checks to tests
  test/common_extended_utils.py
  test/test_extended_models.py
Labels: enhancement, module: models, module: tests, cla signed

#6997 [DataPipe] Properly cleanup unclosed files within generator function
  torchvision/prototype/datasets/_builtin/celeba.py
  torchvision/prototype/datasets/_builtin/mnist.py
  torchvision/prototype/datasets/_builtin/pcam.py
Labels: cla signed

#6955 Upgrade nightly wheels to ROCm5.3
  .circleci/config.yml
  .circleci/regenerate.py
Labels: module: rocm, cla signed

#7009 fix prototype dataset imagenet mock data
  test/builtin_dataset_mocks.py
Labels: cla signed

#7012 add usage logging to prototype dispatchers / kernels
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/_augment.py
  torchvision/prototype/transforms/functional/_color.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/prototype/transforms/functional/_meta.py
  torchvision/prototype/transforms/functional/_misc.py
  torchvision/prototype/transforms/functional/_temporal.py
Labels: module: transforms, cla signed, prototype

#7013 improve download tests and fix SBU
  .github/workflows/tests-schedule.yml
  test/test_datasets_download.py
Labels: module: datasets, module: tests, cla signed

#7014 Add more advanced smoke test for project Nova and validation workflows
  test/smoke_test.py
Labels: cla signed

#7020 Add cuda resnet50 test to smoke test
  test/smoke_test.py
Labels: enhancement, module: tests, cla signed

#7010 [Nova] Remove old M1 Workflow
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#6919 [proto][ci] Try add GPU ci for prototype transforms
  .github/workflows/prototype-transforms-tests-linux-gpu.yml
  test/prototype_transforms_kernel_infos.py
Labels: cla signed

#6849 [cherry-pick] pin pyav to <10 (#6789)
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/windows/scripts/environment.yml
  .github/workflows/test-m1.yml
Labels: cla signed

#7031 Allow dropout overwrites on EfficientNet
  test/smoke_test.py
  torchvision/models/efficientnet.py
Labels: enhancement, module: models, cla signed

#6845 Added typing annotations to datasets/_optical_flow
  torchvision/datasets/_optical_flow.py
Labels: cla signed

#7025 Fix non-existing parameters in docstrings
  references/depth/stereo/utils/losses.py
  test/datasets_utils.py
  test/test_ops.py
  torchvision/models/_api.py
  torchvision/models/detection/_utils.py
  torchvision/transforms/transforms.py
Labels: cla signed

#7045 remove RandomApply inheritance from SimpleCopyPaste
  torchvision/prototype/transforms/_augment.py
Labels: module: transforms, cla signed, prototype

#7041 Fix documentation of `torchvision.ops.misc.MLP` (linear not convolution)
  torchvision/ops/misc.py
Labels: cla signed

#7037 migrate prototype CI to Nova
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/prototype-tests.yml
  .github/workflows/prototype-transforms-tests-linux-gpu.yml
  test/test_prototype_transforms_consistency.py
  test/test_prototype_transforms_functional.py
Labels: module: ci, cla signed, prototype

#7048 Fix `repr` of `transforms.RandomResizedCrop` (remove `)`)
  torchvision/transforms/transforms.py
Labels: cla signed

#6846 Added missing typing annotations in datasets/_stereo_matching
  torchvision/datasets/_stereo_matching.py
Labels: cla signed

#7051 Fix for use download_and_extract in SBU dataset (#7046)
  torchvision/datasets/sbu.py
Labels: cla signed
