Repository pytorch/vision, pull requests merged in 2022-05, with the labels that each got.

#5866 feat: add functional pad on segmentation mask
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: cla signed

#5930 Update SVHN docs
  torchvision/datasets/svhn.py
Labels: module: datasets, module: documentation, cla signed

#5547 Fix libtorchvision.so not able to encode images by adding *_FOUND macros to CMakeLists.txt
  CMakeLists.txt
Labels: cla signed, ciflow/default

#5917 docs: Added SSDLite to the new doc
  docs/source/models/ssdlite.rst
  docs/source/models_new.rst
  torchvision/models/detection/ssdlite.py
Labels: enhancement, module: documentation, cla signed

#5915 docs: Added FCN to the new doc
  docs/source/models/fcn.rst
  docs/source/models_new.rst
  torchvision/models/segmentation/fcn.py
Labels: cla signed

#5923 Add lraspp docs
  docs/source/models/lraspp.rst
  docs/source/models_new.rst
  torchvision/models/segmentation/lraspp.py
Labels: cla signed

#5924 Add inception docs
  docs/source/models.rst
  docs/source/models/inception.rst
  docs/source/models_new.rst
  torchvision/models/googlenet.py
  torchvision/models/inception.py
Labels: cla signed

#5918 Revamp docs for Faster RCNN
  docs/source/models/faster_rcnn.rst
  docs/source/models_new.rst
  torchvision/models/detection/faster_rcnn.py
Labels: cla signed

#5921 Add revamped docs for `ShuffleNet V2`
  docs/source/models/shufflenetv2.rst
  docs/source/models_new.rst
  torchvision/models/shufflenetv2.py
Labels: cla signed

#5920 updating mnasnet docs
  docs/source/models/mnasnet.rst
  docs/source/models_new.rst
  torchvision/models/mnasnet.py
Labels: cla signed

#5819 Reduce variance of evaluation in reference
  references/detection/train.py
  references/optical_flow/train.py
  references/segmentation/train.py
  references/segmentation/utils.py
  references/similarity/train.py
  references/video_classification/train.py
  references/video_classification/utils.py
Labels: enhancement, module: reference scripts, cla signed

#5936 Remove references to non-existing weights in MNASNET
  docs/source/models/mnasnet.rst
  torchvision/models/mnasnet.py
Labels: cla signed

#5937 Fix RegNet links in docs
  torchvision/models/regnet.py
Labels: enhancement, module: documentation, cla signed

#5949 Add mask rcnn to instance segmentation docs
  docs/source/conf.py
  docs/source/models/faster_rcnn.rst
  docs/source/models_new.rst
Labels: cla signed

#5970 Fix type annotation
  torchvision/models/_api.py
Labels: cla signed, other

#5946 [ROCm] update to rocm5.1.1
  .circleci/config.yml
  .circleci/regenerate.py
Labels: module: rocm, cla signed

#5935 Adding resnext101 64x4d model
  docs/source/models.rst
  test/expect/ModelTester.test_resnext101_64x4d_expect.pkl
  test/expect/ModelTester.test_resnext101_64x4d_quantized_expect.pkl
  test/test_models.py
  torchvision/models/quantization/resnet.py
  torchvision/models/resnet.py
Labels: module: models, new feature, cla signed

#5898 Update transforms for PIL deprecation
  test/test_onnx.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  torchvision/transforms/_pil_constants.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/transforms.py
Labels: cla signed

#5888 [proto] Added functional `perspective_bounding_box/segmentation_mask` ops
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#5972 [proto] Added `center_crop_bounding_box` functional op
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#5962 Fixing AlexNet references
  docs/source/models/alexnet.rst
  torchvision/models/alexnet.py
Labels: enhancement, module: documentation, cla signed

#5978 Cleanup removing old cu115 code
  packaging/build_conda.sh
  packaging/pkg_helpers.bash
  packaging/windows/internal/cuda_install.bat
Labels: module: ci, cla signed, code quality

#5975 Add Docs for QuantizedGoogleNet
  docs/source/conf.py
  docs/source/models/googlenet_quant.rst
  docs/source/models_new.rst
  torchvision/models/googlenet.py
  torchvision/models/quantization/googlenet.py
Labels: enhancement, module: documentation, cla signed

#5950 remove explicit install of Pillow throughout CI
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/smoke_test/docker/Dockerfile
  .circleci/unittest/linux/scripts/environment.yml
  .circleci/unittest/windows/scripts/environment.yml
  .circleci/unittest/windows/scripts/setup_env.sh
  packaging/build_cmake.sh
Labels: module: ci, cla signed

#5985 Fix regression on Detection training script
  references/detection/train.py
Labels: bug, module: reference scripts, cla signed

#5984 Adding ciou and diou support in `_box_loss()`
  torchvision/models/detection/_utils.py
Labels: module: models, topic: object detection, cla signed

#5988 Allow custom docs for Weight enums and Weights fields
  docs/source/conf.py
  test/test_extended_models.py
  torchvision/models/resnet.py
Labels: cla signed

#5991 remove SampleQuery from prototype datasets
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_query.py
Labels: module: datasets, cla signed, prototype

#5995 Remove comment which is rendered as css class
  docs/source/docutils.conf
Labels: enhancement, module: documentation, cla signed

#5998 rely on patched datasets home rather than passing it around
  test/builtin_dataset_mocks.py
  test/test_prototype_builtin_datasets.py
Labels: enhancement, module: datasets, module: tests, cla signed, prototype

#6000 Add Comment to clarify
  docs/source/docutils.conf
Labels: cla signed

#5992 Reinstate and deprecate `model_urls` and `quant_model_urls`
  torchvision/models/_utils.py
  torchvision/models/alexnet.py
  torchvision/models/densenet.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/vgg.py
  torchvision/models/video/resnet.py
  torchvision/models/vision_transformer.py
Labels: module: models, module: models.quantization, cla signed, deprecation

#6002 Fix SSD documentation
  docs/source/models/ssd.rst
  docs/source/models_new.rst
Labels: enhancement, module: documentation, cla signed

#6006 Handle empty weights in doc generation
  docs/source/conf.py
  torchvision/models/mnasnet.py
Labels: enhancement, module: documentation, cla signed

#6003 Clean up model documentation
  docs/source/conf.py
  docs/source/models/mnasnet.rst
  torchvision/models/alexnet.py
  torchvision/models/densenet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/resnet.py
  torchvision/models/squeezenet.py
Labels: enhancement, module: documentation, cla signed

#6009 Add preprocessing information on the Weights documentation
  docs/source/conf.py
  torchvision/transforms/_presets.py
Labels: enhancement, module: documentation, cla signed

#6005 [DOC] Add quantized inception updated documentation.
  docs/source/models/inception_quant.rst
  docs/source/models_new.rst
  torchvision/models/quantization/inception.py
Labels: cla signed

#6012 added quantized resnet docs
  docs/source/models/resnet_quant.rst
  docs/source/models_new.rst
  torchvision/models/quantization/resnet.py
Labels: cla signed

#6016 Revamp docs for Quantized MobileNetV3
  docs/source/models/mobilenetv3_quant.rst
  docs/source/models_new.rst
  torchvision/models/quantization/mobilenetv3.py
Labels: cla signed

#6021 Highlighting the Note in the docs
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
Labels: cla signed

#6022 Update ShuffleNetV2 annotations for x1_5 and x2_0 variants
  torchvision/models/shufflenetv2.py
Labels: enhancement, module: models, cla signed

#6023 Fix ConvNext weight links
  torchvision/models/convnext.py
Labels: enhancement, module: documentation, cla signed

#6026 Expose `get_weight` to Torch Hub
  hubconf.py
  torchvision/models/_api.py
  torchvision/models/detection/backbone_utils.py
Labels: enhancement, module: hub, cla signed

#6025 Add more info on new models.srt
  docs/source/conf.py
  docs/source/models_new.rst
  gallery/plot_visualization_utils.py
  torchvision/transforms/_presets.py
Labels: enhancement, module: documentation, cla signed

#6028 Revamp docs for Quantized ShuffleNetV2
  docs/source/models/shufflenetv2_quant.rst
  docs/source/models_new.rst
  torchvision/models/quantization/shufflenetv2.py
Labels: cla signed

#6033 docs: Fixed quantized resnet docstring
  torchvision/models/quantization/resnet.py
Labels: enhancement, module: documentation, cla signed

#6032 docs: Added quantized ResNext to the new doc
  docs/source/models/resnext_quant.rst
  docs/source/models_new.rst
  torchvision/models/quantization/resnet.py
Labels: enhancement, module: documentation, cla signed

#6030 Update galleries to use Multi-weight idioms
  gallery/plot_optical_flow.py
  gallery/plot_visualization_utils.py
Labels: enhancement, module: documentation, cla signed

#6010 Merge mock data preparation and dataset logic in prototype tests
  test/builtin_dataset_mocks.py
  test/test_prototype_builtin_datasets.py
Labels: module: datasets, module: tests, cla signed, prototype

#5990 simplify OnlineResource.load
  test/test_prototype_datasets_utils.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: enhancement, module: datasets, cla signed, prototype

#6036 Document all pre-trained Classification weights
  docs/source/conf.py
  test/test_extended_models.py
  torchvision/models/alexnet.py
  torchvision/models/convnext.py
  torchvision/models/densenet.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/mnasnet.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/swin_transformer.py
  torchvision/models/vgg.py
  torchvision/models/vision_transformer.py
Labels: enhancement, module: documentation, cla signed

#6031 Re arrange docs for Ops
  docs/source/ops.rst
Labels: enhancement, module: documentation, cla signed

#6024 Cleanup ops
  torchvision/ops/__init__.py
  torchvision/ops/_utils.py
  torchvision/ops/boxes.py
  torchvision/ops/ciou_loss.py
  torchvision/ops/diou_loss.py
  torchvision/ops/giou_loss.py
Labels: cla signed

#6039 Document all remaining pre-trained weights
  docs/source/conf.py
  test/test_extended_models.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/optical_flow/raft.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/video/resnet.py
Labels: enhancement, module: documentation, cla signed

#6044 Fix resnext docs
  torchvision/models/quantization/resnet.py
Labels: enhancement, module: documentation, cla signed

#5895 Doc revamp for optical flow models
  docs/source/conf.py
  docs/source/models/raft.rst
  docs/source/models_new.rst
  torchvision/models/optical_flow/raft.py
Labels: cla signed

#6049 Models doc revamp: final cleanup
  docs/Makefile
  docs/source/conf.py
  docs/source/index.rst
  docs/source/models.rst
  docs/source/models_new.rst
Labels: enhancement, module: documentation, cla signed

#6048 add swin_s and swin_b variants and improved swin_t
  docs/source/models/swin_transformer.rst
  references/classification/README.md
  test/expect/ModelTester.test_swin_b_expect.pkl
  test/expect/ModelTester.test_swin_s_expect.pkl
  torchvision/models/swin_transformer.py
Labels: enhancement, module: models, cla signed

#6054 Minor Swin Transformer fixes
  hubconf.py
  test/expect/ModelTester.test_swin_b_expect.pkl
  test/expect/ModelTester.test_swin_s_expect.pkl
  test/test_models.py
Labels: module: models, cla signed, code quality

#6053 Adding multi-layer perceptron in ops
  docs/source/ops.rst
  torchvision/models/swin_transformer.py
  torchvision/models/vision_transformer.py
  torchvision/ops/__init__.py
  torchvision/ops/misc.py
Labels: module: ops, new feature, cla signed

#6055 Move Permute layer to ops
  docs/source/ops.rst
  torchvision/models/convnext.py
  torchvision/models/swin_transformer.py
  torchvision/ops/__init__.py
  torchvision/ops/misc.py
Labels: module: ops, cla signed, code quality

#5977 Document ResNet architecture tweak
  docs/source/models/resnet.rst
  torchvision/models/resnet.py
Labels: enhancement, module: documentation, cla signed

#6052 Deactivate CelebA download
  torchvision/datasets/celeba.py
  torchvision/prototype/datasets/_builtin/celeba.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: cla signed

#5704 improve error handling for GDrive downloads
  torchvision/datasets/utils.py
Labels: enhancement, module: datasets, cla signed

#5857 Fix IndexError on `draw_segmentation_masks` and `draw_bounding_boxes`
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#6061 Add output_format do video datasets and readers
  torchvision/datasets/hmdb51.py
  torchvision/datasets/kinetics.py
  torchvision/datasets/ucf101.py
  torchvision/datasets/video_utils.py
  torchvision/io/video.py
Labels: enhancement, module: video, cla signed

#6058 Remove `(N, T, H, W, C) => (N, T, C, H, W)` from presets
  docs/source/models.rst
  gallery/plot_optical_flow.py
  references/video_classification/train.py
  test/test_extended_models.py
  torchvision/transforms/_presets.py
Labels: enhancement, module: models, cla signed

#6059 Indicate Celeba download parameter is deprecated and will be removed
  torchvision/datasets/celeba.py
Labels: cla signed

#5961 feat: add functional center crop on mask
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#6077 Validate against expected files on videos
  test/expect/ModelTester.test_mc3_18_expect.pkl
  test/expect/ModelTester.test_r2plus1d_18_expect.pkl
  test/expect/ModelTester.test_r3d_18_expect.pkl
  test/test_models.py
Labels: enhancement, module: tests, cla signed

#6082 [bugfix] Check if norm_layer has not-None weight before init
  torchvision/models/resnet.py
Labels: bug, module: models, cla signed

#6080 Test 0.13 release branch against torch RC (test) instead of nightly
  .circleci/config.yml
  .circleci/config.yml.in
  packaging/pkg_helpers.bash
Labels: topic: binaries, dependency issue, cla signed

#6085 [bugfix] Cherrypick resnet norm init bugfix
  torchvision/models/resnet.py
Labels: bug, module: models, cla signed

#6089 [v0.13.0] .circleci: Bump version for pytorch 1.12.0
  .circleci/config.yml
  .circleci/config.yml.in
Labels: topic: binaries, module: ci, cla signed

#6038 add tests for F.pad_bounding_box
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, module: tests, cla signed, prototype

#6091 Fix edge cases on test_backbone_utils when the sampled node is buffer with integer value
  test/test_backbone_utils.py
Labels: bug, module: tests, cla signed

#6097 Change weights return type to Mapping
  torchvision/models/_api.py
Labels: enhancement, cla signed, code quality

#6101 Fix install command for torch cpu release 1.12
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#5948 Add TorchVision wheel builds for M1
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#6104 [proto] Added tests for other padding modes
  test/test_prototype_transforms_functional.py
Labels: module: transforms, cla signed, prototype

#6106 Fixing CI job "cmake_linux_gpu" issue with setup_env.sh in docker
  .circleci/unittest/linux/scripts/setup_env.sh
Labels: cla signed

#6109 [Cherrypick 0.13] Fixing issue with setup_env.sh in docker (#6106)
  .circleci/unittest/linux/scripts/setup_env.sh
Labels: bug, module: ci, cla signed

#6110 [M1] Set build version and delocate wheels
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#6100 [Cherrypick] Refactor swin transfomer so its component can be reused on the 3d version
  torchvision/models/swin_transformer.py
Labels: enhancement, module: models, cla signed
