Repository pytorch/vision, pull requests merged in 2022-07, with the labels that each got.

#6226 Fill arg supports float values, scripted pad op
  test/test_functional_tensor.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_tensor.py
Labels: enhancement, module: transforms, cla signed

#6230 Add build-system requirements
  pyproject.toml
Labels: cla signed

#6228 Add missing `resnext101_64x4d` to `hubconf.py`
  hubconf.py
Labels: bug, module: hub, cla signed

#6234 Update the dataset cache to factor input parameters
  references/video_classification/train.py
Labels: enhancement, module: reference scripts, cla signed

#6201 Refactor setup.py to build only wanted extensions.
  setup.py
Labels: enhancement, topic: build, cla signed

#6237 Extend `_log_api_usage_once` to work for overwritten classes
  torchvision/utils.py
Labels: enhancement, module: utils, cla signed

#6219 [proto] Added mid-level ops and feature-based ops
  .github/workflows/prototype-tests.yml
  test/test_prototype_transforms_functional.py
  torchvision/prototype/features/_bounding_box.py
  torchvision/prototype/features/_feature.py
  torchvision/prototype/features/_image.py
  torchvision/prototype/features/_label.py
  torchvision/prototype/features/_segmentation_mask.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_augment.py
  torchvision/prototype/transforms/functional/_color.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/functional_pil.py
Labels: cla signed

#6241 Adding video accuracy for video_classification reference script
  references/video_classification/datasets.py
  references/video_classification/train.py
  references/video_classification/utils.py
  torchvision/models/video/mvit.py
  torchvision/models/video/resnet.py
Labels: enhancement, module: reference scripts, cla signed

#6248 [jit] Updated tests checking save and load transforms
  test/test_transforms_tensor.py
Labels: enhancement, module: tests, cla signed

#6251 Generalize ConvNormActivation function to accept tuple for some parameters
  torchvision/ops/misc.py
  torchvision/utils.py
Labels: enhancement, module: ops, cla signed

#6252 Small Patch SwinTransformer for FX compatibility
  torchvision/models/swin_transformer.py
Labels: bug, module: models, cla signed

#6245 [proto] Added some transformations and fixed type hints
  test/test_functional_tensor.py
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/features/_bounding_box.py
  torchvision/prototype/features/_feature.py
  torchvision/prototype/features/_image.py
  torchvision/prototype/features/_label.py
  torchvision/prototype/features/_segmentation_mask.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_auto_augment.py
  torchvision/prototype/transforms/_color.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/functional/_color.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#6262 [proto] Added few transforms tests, part 1
  test/test_prototype_transforms.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/transforms/transforms.py
Labels: cla signed

#6273 [proto] Added GaussianBlur transform and tests
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/features/_feature.py
  torchvision/prototype/features/_image.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_misc.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_misc.py
Labels: cla signed

#6276 fixing a typo
  gallery/plot_video_api.py
Labels: cla signed

#6275 [proto] Added random color transforms and tests
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_color.py
Labels: cla signed

#6284 [proto] Added RandomPerspective and tests
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#6285 Added more functional tests
  test/test_prototype_transforms_functional.py
Labels: cla signed

#6291 Fix grammatical error
  torchvision/transforms/transforms.py
Labels: cla signed

#6294 fix typo in 'swin_transformer.rst' docs
  docs/source/models/swin_transformer.rst
Labels: cla signed

#6297 Minor typo fix in tests
  test/test_transforms.py
Labels: module: tests, cla signed, code quality

#6295 [proto] Added elastic transform and tests
  test/test_functional_tensor.py
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/features/_bounding_box.py
  torchvision/prototype/features/_feature.py
  torchvision/prototype/features/_image.py
  torchvision/prototype/features/_segmentation_mask.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#6303 Update git-blame-ignore-revs following new ufmt version
  .git-blame-ignore-revs
  CONTRIBUTING.md
Labels: cla signed, code quality, other

#6278 Vectorize box encoding in FCOS
  torchvision/models/detection/_utils.py
  torchvision/models/detection/fcos.py
Labels: cla signed

#6309 [proto] Implemented RandomErase on PIL input as fallback to tensors
  test/test_prototype_transforms.py
  torchvision/prototype/transforms/_augment.py
Labels: module: transforms, cla signed, prototype

#6298 Set MACOSX_DEPLOYMENT_TARGET=10.9 for binary jobs
  .circleci/config.yml
  .circleci/config.yml.in
  packaging/torchvision/meta.yaml
Labels: bug, topic: binaries, cla signed

#6272 [proto] Updated center_crop tests
  test/test_prototype_transforms_functional.py
Labels: enhancement, module: transforms, module: tests, cla signed

#6290 ci: Update macos runner to self hosted
  .github/workflows/build-m1-binaries.yml
  .github/workflows/test-m1.yml
  packaging/pkg_helpers.bash
Labels: enhancement, module: ci, cla signed

#6316 Cherry pick vision version to 1.12.1
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#6314 Indicate strings can be used to specify `weights` parameter
  docs/source/conf.py
Labels: enhancement, module: documentation, cla signed

#6312 Set MACOSX_DEPLOYMENT_TARGET=10.9 for binary jobs (#6298)
  .circleci/config.yml
  .circleci/config.yml.in
  packaging/torchvision/meta.yaml
Labels: cla signed

#6301 Small Patch SwinTransformer for FX compatibility (#6252)
  torchvision/models/swin_transformer.py
Labels: module: models, cla signed, other

#6318 Indicate strings can be used to specify weights paramete
  docs/source/conf.py
Labels: cla signed

#6027 Refactor tests for ops
  test/test_ops.py
Labels: enhancement, module: ops, module: tests, cla signed

#6319 Added image_size computation for BoundingBox.rotate if expand
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/features/_bounding_box.py
  torchvision/prototype/features/_image.py
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#6320 [proto] Added erase_image_pil and eager/jit erase_image_tensor test
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_augment.py
Labels: module: transforms, cla signed, prototype

#6322 Replaced CHECK_ by TORCH_CHECK_
  torchvision/csrc/io/decoder/audio_sampler.cpp
  torchvision/csrc/io/decoder/sync_decoder.cpp
  torchvision/csrc/io/decoder/sync_decoder_test.cpp
  torchvision/csrc/io/decoder/util.cpp
  torchvision/csrc/io/video/video.cpp
  torchvision/csrc/io/video_reader/video_reader.cpp
Labels: module: ops, cla signed, other

#6324 Run M1 unit-tests on every PR
  .github/workflows/test-m1.yml
Labels: enhancement, module: ci, cla signed

#6305 [proto] Ported all transforms to the new API
  test/test_functional_tensor.py
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/features/_bounding_box.py
  torchvision/prototype/features/_feature.py
  torchvision/prototype/features/_image.py
  torchvision/prototype/features/_segmentation_mask.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_color.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_misc.py
  torchvision/prototype/transforms/_transform.py
  torchvision/prototype/transforms/_utils.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_augment.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/prototype/transforms/functional/_misc.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/functional_tensor.py
  torchvision/transforms/transforms.py
Labels: module: transforms, cla signed, prototype

#6328 Renamed num_bands into num_channels
  torchvision/transforms/functional_pil.py
Labels: module: transforms, cla signed, code quality, prototype

#6327 [FBcode->GH] [pytorch] Bump SoLoader version to 0.10.4 (#81946)
  android/build.gradle
Labels: cla signed

#6329 Replaced python built-in input by inpt
  torchvision/prototype/transforms/_auto_augment.py
  torchvision/prototype/transforms/_container.py
  torchvision/prototype/transforms/_deprecated.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_meta.py
  torchvision/prototype/transforms/_misc.py
  torchvision/prototype/transforms/_type_conversion.py
  torchvision/prototype/transforms/_utils.py
Labels: module: transforms, cla signed, code quality, prototype

#6334 Add minor versioning to release 0.13
  .github/workflows/build-m1-binaries.yml
  version.txt
Labels: cla signed

#6335 Simplify _check_integrity for cifar and stl10
  torchvision/datasets/cifar.py
  torchvision/datasets/stl10.py
Labels: cla signed
