Repository pytorch/vision, pull requests merged in 2022-06, with the labels that each got.

#6117 [BE] Unify version computation
  .github/workflows/build-m1-binaries.yml
  packaging/build_cmake.sh
  packaging/build_conda.sh
  packaging/build_wheel.sh
  packaging/pkg_helpers.bash
Labels: cla signed

#6122 [M1] Install "jpeg<=9b" rather than OpenJpeg
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#5121 Docs: build with Sphinx 5
  docs/requirements.txt
  docs/source/conf.py
Labels: cla signed, ciflow/default

#6132 Add unit-tests for M1
  .github/workflows/build-m1-binaries.yml
  .github/workflows/test-m1.yml
Labels: cla signed

#6105 Adding MViT v2 architecture
  docs/source/models.rst
  docs/source/models/video_mvitv2.rst
  test/expect/ModelTester.test_mvit_v2_b_expect.pkl
  test/expect/ModelTester.test_mvit_v2_s_expect.pkl
  test/expect/ModelTester.test_mvit_v2_t_expect.pkl
  test/test_extended_models.py
  test/test_models.py
  torchvision/models/video/__init__.py
  torchvision/models/video/mvitv2.py
Labels: module: models, new feature, cla signed

#6133 [FBcode->GH] [quant][core][better-engineering] Rename files in quantized directory…
  torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp
Labels: cla signed

#6141 Remove `AffineQuantizer.h` from `qnms_kernel.cpp`
  torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp
Labels: cla signed

#6140 Adding tagged builds for M1
  .github/workflows/build-m1-binaries.yml
  packaging/pkg_helpers.bash
Labels: cla signed

#6147 Put back CelebA download
  torchvision/datasets/celeba.py
  torchvision/prototype/datasets/_builtin/celeba.py
  torchvision/prototype/datasets/utils/_resource.py
Labels: cla signed

#6146 Fix `if` condition for s3/conda uploads
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#6150 Fix ViT and Resnext docs
  docs/source/models/resnext.rst
  torchvision/models/vision_transformer.py
Labels: bug, module: documentation

#6149 Put back CelebA download (#6147)
  torchvision/datasets/celeba.py
Labels: cla signed

#6154 Update _pil_constants.py
  test/test_transforms.py
  torchvision/transforms/_pil_constants.py
Labels: bug, module: transforms, cla signed

#6156 Update _pil_constants.py
  test/test_transforms.py
  torchvision/transforms/_pil_constants.py
Labels: bug, module: transforms, cla signed

#6158 Fix typo in GHA nightly build condition
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#4938 Added elastic transform in torchvision.transforms
  gallery/plot_transforms.py
  gallery/plot_video_api.py
  test/test_functional_tensor.py
  test/test_transforms.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_tensor.py
  torchvision/transforms/transforms.py
Labels: module: transforms, new feature, cla signed, ciflow/default

#6163 Fix minor typo in optical flow gallery example
  gallery/plot_optical_flow.py
Labels: enhancement, module: documentation, cla signed

#6164 Fix minor typo in optical flow gallery example
  gallery/plot_optical_flow.py
Labels: enhancement, module: documentation

#6115 Add new `.. betastatus::` directive to document Beta APIs
  docs/source/beta_status.py
  docs/source/conf.py
  docs/source/io.rst
  docs/source/models.rst
  docs/source/models/deeplabv3.rst
  docs/source/models/faster_rcnn.rst
  docs/source/models/fcn.rst
  docs/source/models/fcos.rst
  docs/source/models/keypoint_rcnn.rst
  docs/source/models/lraspp.rst
  docs/source/models/mask_rcnn.rst
  docs/source/models/retinanet.rst
  docs/source/models/ssd.rst
  docs/source/models/ssdlite.rst
  docs/source/models/video_resnet.rst
  torchvision/io/image.py
  torchvision/io/video_reader.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/video/resnet.py
Labels: cla signed

#6168 Make sure we are building against test channel for release
  .github/workflows/build-m1-binaries.yml
  .github/workflows/test-m1.yml
Labels: cla signed

#6167 M1 fixes cherry
  .github/workflows/build-m1-binaries.yml
  .github/workflows/test-m1.yml
  packaging/build_cmake.sh
  packaging/build_conda.sh
  packaging/build_wheel.sh
  packaging/pkg_helpers.bash
Labels: cla signed

#5825 Add SimpleCopyPaste augmentation
  references/detection/train.py
  references/detection/transforms.py
Labels: enhancement, module: transforms, topic: object detection, cla signed

#6170 Fix push on release reference name
  .github/workflows/build-m1-binaries.yml
  .github/workflows/test-m1.yml
Labels: cla signed

#6171 Fix push on release reference name (#6170)
  .github/workflows/build-m1-binaries.yml
  .github/workflows/test-m1.yml
Labels: cla signed

#6174 Adding `_log_api_usage_once` to Swin's reusable components
  torchvision/models/swin_transformer.py
Labels: bug, module: models, cla signed

#6176 Fix all broken URLs in docs
  torchvision/datasets/caltech.py
  torchvision/datasets/kinetics.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/resnet.py
  torchvision/prototype/datasets/_builtin/caltech.py
Labels: enhancement, module: documentation, cla signed

#6175 Adding _log_api_usage_once to Swin's reusable components (#6174)
  torchvision/models/swin_transformer.py
Labels: bug, module: models, cla signed

#6177 Fix all broken URLs (#6176)
  torchvision/datasets/caltech.py
  torchvision/datasets/kinetics.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/resnet.py
Labels: cla signed

#6181 Fix copypaste collate pickle issues
  references/detection/train.py
Labels: bug, module: reference scripts, cla signed

#6188 [FBcode->GH] fix submodule imports by importing functions directly
  torchvision/extension.py
Labels: cla signed

#6191 Refactored and modified private api for resize functional op
  test/test_transforms_tensor.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/functional_tensor.py
Labels: enhancement, module: transforms, cla signed

#6199 Add flag to ignore ffmpeg in python build.
  setup.py
Labels: cla signed

#6198 Add MViT architecture in TorchVision
  docs/source/models.rst
  docs/source/models/video_mvit.rst
  references/video_classification/train.py
  test/expect/ModelTester.test_mvit_v1_b_expect.pkl
  test/test_extended_models.py
  test/test_models.py
  torchvision/models/video/__init__.py
  torchvision/models/video/mvit.py
Labels: module: models, new feature, cla signed

#6208 Bugfix for accimage test on functional_pil.resize image
  torchvision/transforms/functional_pil.py
Labels: bug, module: transforms, cla signed

#6215 Add new version v0.13.0 to readme
  README.rst
Labels: module: documentation, cla signed, release-issue

#6218 Move from xcode v12 to v14
  .circleci/config.yml
  .circleci/config.yml.in
Labels: enhancement, module: ci, cla signed
