Repository pytorch/vision, pull requests merged in 2022-04, with the labels that each got.

#5715 Detection recipe enhancements
  references/classification/train.py
  references/detection/presets.py
  references/detection/train.py
  test/test_extended_models.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/transform.py
  torchvision/ops/_utils.py
Labels: enhancement, module: models, module: reference scripts, cla signed

#5671 add set_weight_decay to support custom weight decay setting
  references/classification/train.py
  references/classification/utils.py
Labels: module: reference scripts, new feature, cla signed

#5714 Add SWAG Vision Transformer Weight
  README.rst
  test/test_extended_models.py
  torchvision/models/vision_transformer.py
Labels: module: models, new feature, cla signed

#5489 Fix shape mismatch error
  test/test_video_reader.py
  torchvision/io/_video_opt.py
  torchvision/io/video.py
Labels: bug, module: io, module: video, cla signed, ciflow/default

#5645 support confirming no virus scan on GDrive download
  torchvision/datasets/utils.py
Labels: enhancement, module: datasets, cla signed, ciflow/default

#5724 disable pyav==9.1.1 on windows
  .circleci/unittest/windows/scripts/environment.yml
Labels: dependency issue, module: ci, cla signed

#5722 Add regnet model from SWAG
  torchvision/models/regnet.py
Labels: module: models, new feature, cla signed

#5717 indicate md5 checksum is not used for security
  torchvision/datasets/utils.py
Labels: enhancement, module: datasets, cla signed

#5675 port Grayccale and RandomGrayscale transforms to prototype API
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_legacy.py
  torchvision/prototype/transforms/_meta.py
Labels: module: transforms, cla signed, deprecation, prototype

#5584 Food101 new dataset api
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/food101.categories
  torchvision/prototype/datasets/_builtin/food101.py
Labels: module: datasets, cla signed, ciflow/default, prototype

#5660 [ROCm] Update to rocm5.0 wheels
  .circleci/config.yml
  .circleci/regenerate.py
Labels: module: rocm, cla signed

#5692 [proto] Added functional `rotate_segmentation_mask` op
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#5732 Add regnet_y_128gf from SWAG
  torchvision/models/regnet.py
Labels: module: models, new feature, cla signed

#5739 remove unnecessary pytest install
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
Labels: module: ci, cla signed, code quality

#5738 fix missing torchdata error message
  torchvision/prototype/datasets/__init__.py
Labels: module: datasets, cla signed, prototype

#5711 fix prototype datasets data loading tests
  test/test_prototype_builtin_datasets.py
Labels: module: datasets, cla signed, prototype

#5721 Adding the huge vision transformer from SWAG
  docs/source/models.rst
  hubconf.py
  test/expect/ModelTester.test_vit_h_14_expect.pkl
  test/test_models.py
  torchvision/models/vision_transformer.py
Labels: module: models, new feature, cla signed

#5743 migrate VOC prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/imagenet.py
  torchvision/prototype/datasets/_builtin/voc.py
Labels: module: datasets, cla signed, prototype

#5444 Post-paper Detection Optimizations
  test/expect/ModelTester.test_fasterrcnn_resnet50_fpn_v2_expect.pkl
  test/expect/ModelTester.test_maskrcnn_resnet50_fpn_v2_expect.pkl
  test/expect/ModelTester.test_retinanet_resnet50_fpn_v2_expect.pkl
  test/test_models.py
  torchvision/models/detection/_utils.py
  torchvision/models/detection/backbone_utils.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/rpn.py
  torchvision/ops/feature_pyramid_network.py
Labels: enhancement, module: reference scripts, topic: object detection, cla signed, ciflow/default

#5753 migrate country211 prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/country211.py
Labels: module: datasets, cla signed, prototype

#5473 migrate coco prototype
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/coco.py
  torchvision/prototype/datasets/_builtin/imagenet.py
  torchvision/prototype/datasets/_builtin/voc.py
  torchvision/prototype/datasets/generate_category_files.py
  torchvision/prototype/datasets/utils/_dataset.py
Labels: module: datasets, cla signed, ciflow/default, prototype

#5745 Migrate PCAM prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/pcam.py
Labels: cla signed

#5757 Migrate DTD prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/dtd.py
Labels: cla signed

#5746 Migrate GTSRB prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/gtsrb.py
Labels: cla signed

#5750 migrate CelebA prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/celeba.py
Labels: module: datasets, cla signed, prototype

#5758 Migrate Food101 prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/food101.py
Labels: cla signed

#5759 Migrate Fer2013 prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/fer2013.py
Labels: cla signed

#5760 Migrate EuroSAT prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/eurosat.py
Labels: cla signed

#5761 Migrate Semeion prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/semeion.py
Labels: cla signed

#5764 Migrate Oxford Pets prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/oxford_iiit_pet.py
Labels: cla signed

#5480 migrate mnist prototype datasets
  test/builtin_dataset_mocks.py
  test/test_prototype_builtin_datasets.py
  torchvision/prototype/datasets/_builtin/mnist.py
Labels: module: datasets, cla signed, ciflow/default, prototype

#5767 Migrate Stanford Cars prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/dtd.py
  torchvision/prototype/datasets/_builtin/stanford_cars.py
Labels: cla signed

#5770 fix category file generation
  torchvision/prototype/datasets/_builtin/country211.py
  torchvision/prototype/datasets/_builtin/dtd.py
  torchvision/prototype/datasets/_builtin/food101.py
  torchvision/prototype/datasets/_builtin/oxford_iiit_pet.py
  torchvision/prototype/datasets/_builtin/sbd.py
  torchvision/prototype/datasets/_builtin/voc.py
Labels: module: datasets, cla signed, prototype

#5771 Migrate USPS prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/usps.py
Labels: cla signed

#5772 migrate SBD prototype dataset
  test/builtin_dataset_mocks.py
  torchvision/prototype/datasets/_builtin/sbd.py
Labels: module: datasets, cla signed, prototype

#5756 Add RetinaNet improved weights
  torchvision/models/detection/retinanet.py
Labels: module: models, topic: object detection, new feature, cla signed

#5763 Add FasterRCNN improved weights
  torchvision/models/detection/faster_rcnn.py
Labels: module: models, topic: object detection, new feature, cla signed

#5773 Add MaskRCNN improved weights
  torchvision/models/detection/mask_rcnn.py
Labels: module: models, topic: object detection, new feature, cla signed

#5775 fix Flowers102 dataset labels
  torchvision/datasets/flowers102.py
Labels: bug, module: datasets, cla signed

#5774 Cleanup prototype dataset implementation
  test/builtin_dataset_mocks.py
  test/test_prototype_builtin_datasets.py
  test/test_prototype_datasets_api.py
  test/test_prototype_datasets_utils.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_builtin/celeba.py
  torchvision/prototype/datasets/_builtin/cifar.py
  torchvision/prototype/datasets/_builtin/clevr.py
  torchvision/prototype/datasets/_builtin/coco.py
  torchvision/prototype/datasets/_builtin/country211.py
  torchvision/prototype/datasets/_builtin/cub200.py
  torchvision/prototype/datasets/_builtin/dtd.py
  torchvision/prototype/datasets/_builtin/eurosat.py
  torchvision/prototype/datasets/_builtin/fer2013.py
  torchvision/prototype/datasets/_builtin/food101.py
  torchvision/prototype/datasets/_builtin/gtsrb.py
  torchvision/prototype/datasets/_builtin/imagenet.py
  torchvision/prototype/datasets/_builtin/mnist.py
  torchvision/prototype/datasets/_builtin/oxford_iiit_pet.py
  torchvision/prototype/datasets/_builtin/pcam.py
  torchvision/prototype/datasets/_builtin/sbd.py
  torchvision/prototype/datasets/_builtin/semeion.py
  torchvision/prototype/datasets/_builtin/stanford_cars.py
  torchvision/prototype/datasets/_builtin/svhn.py
  torchvision/prototype/datasets/_builtin/usps.py
  torchvision/prototype/datasets/_builtin/voc.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_internal.py
  torchvision/prototype/utils/_internal.py
Labels: cla signed

#5734 Remove Bandit and CodeQL jobs
  .github/workflows/bandit.yml
  .github/workflows/codeql.yml
Labels: enhancement, module: ci, cla signed, ciflow/default

#5777 update prototype dataset README
  torchvision/prototype/datasets/_builtin/README.md
Labels: module: datasets, cla signed, prototype

#5778 Refactor prototype datasets
  test/builtin_dataset_mocks.py
  test/test_prototype_builtin_datasets.py
  test/test_prototype_datasets_api.py
  test/test_prototype_datasets_utils.py
  torchvision/prototype/datasets/__init__.py
  torchvision/prototype/datasets/_api.py
  torchvision/prototype/datasets/_builtin/README.md
  torchvision/prototype/datasets/_builtin/__init__.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_builtin/celeba.py
  torchvision/prototype/datasets/_builtin/cifar.py
  torchvision/prototype/datasets/_builtin/clevr.py
  torchvision/prototype/datasets/_builtin/coco.py
  torchvision/prototype/datasets/_builtin/country211.py
  torchvision/prototype/datasets/_builtin/cub200.py
  torchvision/prototype/datasets/_builtin/dtd.py
  torchvision/prototype/datasets/_builtin/eurosat.py
  torchvision/prototype/datasets/_builtin/fer2013.py
  torchvision/prototype/datasets/_builtin/food101.py
  torchvision/prototype/datasets/_builtin/gtsrb.py
  torchvision/prototype/datasets/_builtin/imagenet.py
  torchvision/prototype/datasets/_builtin/mnist.py
  torchvision/prototype/datasets/_builtin/oxford_iiit_pet.py
  torchvision/prototype/datasets/_builtin/pcam.py
  torchvision/prototype/datasets/_builtin/sbd.py
  torchvision/prototype/datasets/_builtin/semeion.py
  torchvision/prototype/datasets/_builtin/stanford_cars.py
  torchvision/prototype/datasets/_builtin/svhn.py
  torchvision/prototype/datasets/_builtin/usps.py
  torchvision/prototype/datasets/_builtin/voc.py
  torchvision/prototype/datasets/generate_category_files.py
  torchvision/prototype/datasets/utils/__init__.py
  torchvision/prototype/datasets/utils/_dataset.py
  torchvision/prototype/datasets/utils/_internal.py
  torchvision/prototype/utils/_internal.py
Labels: module: datasets, cla signed, prototype

#5781 [proto] Added functional `crop_bounding_box` op
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: cla signed

#5796 Fix typos.
  torchvision/ops/_register_onnx_ops.py
  torchvision/ops/misc.py
Labels: enhancement, module: documentation, cla signed

#5789 fix caltech dataset downloads
  torchvision/datasets/caltech.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_builtin/cub200.py
Labels: module: datasets, cla signed

#5687 add background category to prototype VOC dataset
  torchvision/prototype/datasets/_builtin/voc.categories
  torchvision/prototype/datasets/_builtin/voc.py
Labels: module: datasets, cla signed, prototype

#5793 Add SWAG model weight that only the linear head is finetuned to ImageNet1K
  torchvision/models/regnet.py
  torchvision/models/vision_transformer.py
Labels: module: models, new feature, cla signed

#5802 [CircleCI] Update base images to ubuntu-2004
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#5805 do not re-download from GDrive if file is already present
  torchvision/datasets/utils.py
Labels: bug, module: datasets, cla signed

#5792 Add test for giou_loss
  test/test_ops.py
Labels: module: tests, new feature, cla signed

#5814 Fix FGVCAircraft dataset documentation
  torchvision/datasets/fgvc_aircraft.py
Labels: module: datasets, module: documentation, cla signed

#5827 Fix typos
  torchvision/models/feature_extraction.py
Labels: cla signed

#5807 Add RandomEqualize prototype transforms
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_color.py
Labels: module: transforms, cla signed, prototype

#5816 fix fcos gt_areas calculation
  torchvision/models/detection/fcos.py
Labels: cla signed

#5799 Focal Loss Documentation enhanced
  torchvision/ops/focal_loss.py
Labels: enhancement, module: documentation, cla signed

#5823 Replace usages of atomicAdd with gpuAtomicAdd
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_align_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_pool_kernel.cu
  torchvision/csrc/ops/cuda/roi_align_kernel.cu
  torchvision/csrc/ops/cuda/roi_pool_kernel.cu
Labels: module: ops, cla signed, code quality

#5785 add warning if font is not set
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#5820 the ` vision_transformer.py` assert msg problem
  torchvision/models/vision_transformer.py
Labels: enhancement, module: models, cla signed

#5821 Model doc revamp - first PR
  .gitignore
  docs/Makefile
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/models/resnet.rst
  docs/source/models/vgg.rst
  docs/source/models_new.rst
  torchvision/models/resnet.py
  torchvision/models/vgg.py
Labels: cla signed

#5832 Add docs for SqueezeNet
  docs/source/models/squeezenet.rst
  docs/source/models_new.rst
  torchvision/models/squeezenet.py
Labels: enhancement, module: documentation

#5654 Minor updates to optical flow ref for consistency
  references/optical_flow/train.py
Labels: cla signed

#5841 Respect `strict=False` when loading detection models
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/rpn.py
  torchvision/ops/feature_pyramid_network.py
Labels: bug, module: models, cla signed

#5844 fix INaturalist 2021_train checksum
  torchvision/datasets/inaturalist.py
Labels: bug, module: datasets, cla signed

#5847 Document make html-noplot as the default doc building method
  CONTRIBUTING.md
Labels: enhancement, module: documentation, cla signed

#5848 Remove publication_year and interpolation meta
  test/test_extended_models.py
  torchvision/models/alexnet.py
  torchvision/models/convnext.py
  torchvision/models/densenet.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/mnasnet.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/optical_flow/raft.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/vgg.py
  torchvision/models/video/resnet.py
  torchvision/models/vision_transformer.py
Labels: module: models, cla signed, code quality

#5849 Replace distutils.spawn with shutil.which per PEP632 in setup script
  setup.py
Labels: module: video, cla signed

#5852 Clean up purely informational fields from Weight Meta-data
  test/test_extended_models.py
  torchvision/models/alexnet.py
  torchvision/models/convnext.py
  torchvision/models/densenet.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/mnasnet.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/optical_flow/raft.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/vgg.py
  torchvision/models/video/resnet.py
  torchvision/models/vision_transformer.py
Labels: enhancement, module: documentation, cla signed

#5856 Adding revamp docs for vision_transformers and regnet
  docs/source/models/regnet.rst
  docs/source/models/resnet.rst
  docs/source/models/squeezenet.rst
  docs/source/models/vgg.rst
  docs/source/models/vision_transformer.rst
  docs/source/models_new.rst
  torchvision/models/regnet.py
  torchvision/models/vision_transformer.py
Labels: enhancement, module: documentation, cla signed

#5851 Added `crop_segmentation_mask` op
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: cla signed

#5861 simplify boundingbox kernels with jit compatible ellipsis
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, torchscript, cla signed, prototype

#5859 Restructuring metrics meta-data
  docs/source/conf.py
  test/test_extended_models.py
  torchvision/models/alexnet.py
  torchvision/models/convnext.py
  torchvision/models/densenet.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/mnasnet.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/optical_flow/raft.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/vgg.py
  torchvision/models/video/resnet.py
  torchvision/models/vision_transformer.py
Labels: enhancement, module: documentation, cla signed

#5860 test: add functional vertical flip tests on segmentation mask
  test/test_prototype_transforms_functional.py
Labels: enhancement, module: transforms, module: tests, cla signed

#5862 Removing cuda115 since we migrated to cuda116
  .circleci/config.yml
  .circleci/regenerate.py
Labels: enhancement, module: ci, cla signed

#5868 Pin setuptools to 58.0.4 on Widnows
  .circleci/unittest/windows/scripts/environment.yml
Labels: module: ci, cla signed

#5853 Added `resized_crop_bounding_box` op
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: cla signed

#5854 EfficientNet New Documentation
  docs/source/models/efficientnet.rst
  docs/source/models_new.rst
  torchvision/models/efficientnet.py
Labels: cla signed

#5864 Efficientnetv2
  docs/source/models/efficientnetv2.rst
  docs/source/models_new.rst
  torchvision/models/efficientnet.py
Labels: cla signed

#5869 Add docs for ConvNext
  docs/source/models/convnext.rst
  docs/source/models_new.rst
  torchvision/models/convnext.py
Labels: cla signed

#5871 Add docs for ResNeXt
  docs/source/models/resnext.rst
  docs/source/models_new.rst
  torchvision/models/resnet.py
Labels: cla signed

#5874 Fix weight doc generation
  docs/source/conf.py
Labels: bug, module: documentation, cla signed

#5855 Added `resized_crop_segmentation_mask` op
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: cla signed

#5878 Added docs for DenseNet
  docs/source/models/densenet.rst
  docs/source/models_new.rst
  torchvision/models/densenet.py
Labels: cla signed

#5880 remove magic comma in some places
  test/test_functional_tensor.py
  torchvision/transforms/functional_tensor.py
Labels: enhancement, cla signed, code quality

#5875 Fixed issue with padding on CI
  test/test_transforms_tensor.py
  torchvision/transforms/functional_tensor.py
Labels: module: ci, cla signed

#5876 Start doc revamp for detection models
  docs/source/conf.py
  docs/source/models/retinanet.rst
  docs/source/models_new.rst
  torchvision/models/detection/retinanet.py
Labels: cla signed

#5884 Start doc revamp for semantic segmentation models
  docs/source/conf.py
  docs/source/models/deeplabv3.rst
  docs/source/models_new.rst
  torchvision/models/detection/retinanet.py
  torchvision/models/segmentation/deeplabv3.py
Labels: cla signed

#5886 AlexNet New Documentation.
  docs/source/models/alexnet.rst
  docs/source/models/efficientnetv2.rst
  docs/source/models_new.rst
  torchvision/models/alexnet.py
Labels: cla signed

#5891 Document MobileNetV3 quantization approach
  torchvision/models/quantization/mobilenetv3.py
Labels: enhancement, module: documentation, cla signed

#5896 Fix Accuracy meta-data on shufflenetv2
  torchvision/models/shufflenetv2.py
Labels: bug, module: documentation, cla signed

#5491 Adding Swin Transformer architecture
  docs/source/models.rst
  docs/source/models/swin_transformer.rst
  docs/source/models_new.rst
  references/classification/README.md
  references/classification/train.py
  test/expect/ModelTester.test_swin_t_expect.pkl
  torchvision/models/__init__.py
  torchvision/models/swin_transformer.py
Labels: module: models, new feature, cla signed, ciflow/default

#5899 docs: Added MobileNetV2 to the new doc
  docs/source/models/mobilenetv2.rst
  docs/source/models_new.rst
  torchvision/models/mobilenetv2.py
Labels: cla signed

#5894 Add revamped docs for video classification models
  docs/source/conf.py
  docs/source/models/video_resnet.rst
  docs/source/models_new.rst
  torchvision/models/video/resnet.py
Labels: enhancement, module: documentation, cla signed

#5900 docs: Added MaskRCNN to the new doc
  docs/source/models/mask_rcnn.rst
  docs/source/models_new.rst
  torchvision/models/detection/mask_rcnn.py
Labels: cla signed

#5901 refactor FCOS doc
  docs/source/models/fcos.rst
  docs/source/models_new.rst
  torchvision/models/detection/fcos.py
Labels: cla signed

#5902 Add swin_t to slow list
  test/expect/ModelTester.test_swin_t_expect.pkl
  test/test_models.py
Labels: cla signed

#5905 Fix alexnet docs
  docs/source/models/alexnet.rst
  torchvision/models/alexnet.py
Labels: enhancement, module: documentation, cla signed

#5910 Disable `test_encode|write_jpeg_reference` tests
  test/test_image.py
Labels: bug, module: tests, cla signed

#5911 Fix keypointrcnn_resnet50_fpn flaky test
  test/expect/ModelTester.test_keypointrcnn_resnet50_fpn_expect.pkl
  test/test_models.py
Labels: bug, module: tests, cla signed

#5903 Skip big model in test to reduce memory usage in CI
  test/test_models.py
Labels: enhancement, module: tests, cla signed

#5904 Make weights tables row size smaller
  docs/source/_static/css/custom_torchvision.css
  docs/source/conf.py
Labels: cla signed

#5908 Add docs for Mobilenetv3
  docs/source/models/convnext.rst
  docs/source/models/mobilenetv3.rst
  docs/source/models_new.rst
  torchvision/models/mobilenetv3.py
Labels: cla signed

#5912 fix test_data_loader on Windows and macOS
  test/test_prototype_builtin_datasets.py
Labels: module: datasets, cla signed, prototype

#5914 add Windows and macOS CI jobs for prototype tests
  .circleci/config.yml
  .circleci/config.yml.in
  .github/workflows/prototype-tests.yml
Labels: module: ci, cla signed, prototype

#5906 Add shufflenetv2 1.5 and 2.0 weights
  docs/source/models.rst
  hubconf.py
  references/classification/README.md
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/shufflenetv2.py
Labels: enhancement, module: models, cla signed

#5776 Added CIOU loss function
  docs/source/ops.rst
  test/test_ops.py
  torchvision/ops/__init__.py
  torchvision/ops/boxes.py
  torchvision/ops/ciou_loss.py
Labels: module: ops, topic: object detection, new feature, cla signed
