Repository pytorch/vision, pull requests merged in 2023-05, with the labels that each got.

#7540 Adding windows wheel builds
  .github/workflows/build-wheels-windows.yml
  packaging/pre_build_script.sh
Labels: cla signed

#7547 [Nova] Adding conda windows build
  .github/workflows/build-conda-windows.yml
Labels: cla signed

#7498 enable Windows GPU CI on GHA
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .github/workflows/test-windows.yml
Labels: module: ci, cla signed

#7550 improve smoke test
  test/smoke_test.py
Labels: module: tests, cla signed

#7546 refactor download tests
  test/test_datasets_download.py
Labels: module: datasets, module: tests, cla signed

#7536 Fix Resize() documentation
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
  torchvision/transforms/v2/_geometry.py
Labels: cla signed

#7551 [Nova] Adding conda windows build
  .github/workflows/build-conda-windows.yml
Labels: cla signed

#7553 [FBcode->GH] [codemod] Replace hasattr with getattr in pytorch/vision/test/test_transforms_tensor.py
  test/test_transforms_tensor.py
Labels: module: tests, cla signed, code quality

#7524 remove android and iOS builds from CI
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  android/README.md
  ios/README.md
Labels: topic: mobile, module: ci, cla signed

#7554 Fix lint CI
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
  torchvision/transforms/v2/_geometry.py
Labels: cla signed, code quality, other

#7355 remove temporary skips in favor of increased tolerances
  test/transforms_v2_kernel_infos.py
Labels: cla signed

#7219 Check sha256 of weights
  torchvision/models/_api.py
  torchvision/models/alexnet.py
  torchvision/models/convnext.py
  torchvision/models/densenet.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/maxvit.py
  torchvision/models/mnasnet.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/optical_flow/raft.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/swin_transformer.py
  torchvision/models/vgg.py
  torchvision/models/video/mvit.py
  torchvision/models/video/resnet.py
  torchvision/models/video/s3d.py
  torchvision/models/video/swin_transformer.py
  torchvision/models/vision_transformer.py
  torchvision/prototype/models/depth/stereo/crestereo.py
  torchvision/prototype/models/depth/stereo/raft_stereo.py
Labels: cla signed

#7519 proper comparison of input and outpus size before resizing
  test/test_transforms.py
  torchvision/transforms/functional.py
Labels: bug, module: transforms, cla signed

#7558 Add missing cuda 12.1 code, cleanup cu116 use cases
  packaging/pkg_helpers.bash
  packaging/windows/internal/cuda_install.bat
  packaging/windows/internal/vc_install_helper.sh
Labels: cla signed

#7516 remove double doc upload after CloudFront fix
  .github/workflows/docs.yml
Labels: module: documentation, module: ci, cla signed

#7555 moving windows conda / CUDA workarounds to Nova
  .github/workflows/test-windows.yml
Labels: cla signed

#7566 fix v2.Lambda
  test/test_transforms_v2.py
  torchvision/transforms/v2/_misc.py
Labels: bug, module: transforms, cla signed

#7521 add same size shortcut for resize in transforms v2
  test/transforms_v2_kernel_infos.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: enhancement, module: transforms, cla signed

#7567 use automatic doc upload instead of seperate job
  .github/workflows/docs.yml
Labels: module: documentation, module: ci, cla signed

#7559 remove obsolete pre Pyhton3.8 compat
  torchvision/_internally_replaced_utils.py
  torchvision/extension.py
Labels: cla signed, code quality

#7571 Turn off windows circleci nightly builds. Enable GHA
  .circleci/config.yml
  .circleci/regenerate.py
  .github/workflows/build-conda-windows.yml
  .github/workflows/build-wheels-windows.yml
Labels: cla signed

#7572 Revert "Turn off windows circleci nightly builds. Enable GHA"
  .circleci/config.yml
  .circleci/regenerate.py
  .github/workflows/build-conda-windows.yml
  .github/workflows/build-wheels-windows.yml
Labels: cla signed

#7569 Add BC linter
  .github/workflows/lint.yml
Labels: cla signed

#7573 setup.py: fix ROCm build
  setup.py
Labels: bug, topic: binaries, module: rocm, cla signed

#7575 fix code format
  setup.py
Labels: cla signed, other

#7574 consolidate test workflows
  .github/workflows/test-macos.yml
  .github/workflows/test-windows.yml
  .github/workflows/tests.yml
Labels: module: ci, cla signed, code quality

#7339 Assert RAFT input resolution is 128 x 128 or higher
  torchvision/models/optical_flow/raft.py
Labels: cla signed

#7576 add 0.15.2 release to readme
  README.md
Labels: module: documentation, cla signed

#7578 Take 2, Turn off windows circleci nightly builds. Enable GHA
  .circleci/config.yml
  .circleci/regenerate.py
  .github/workflows/build-conda-windows.yml
  .github/workflows/build-wheels-windows.yml
Labels: cla signed

#7583 Add cpu smoke_test_torchvision_decode_jpeg test
  test/smoke_test.py
Labels: cla signed

#7582 Alert non-deterministic on kernels that use gpuAtomicAdd
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_align_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_pool_kernel.cu
  torchvision/csrc/ops/cuda/roi_align_kernel.cu
  torchvision/csrc/ops/cuda/roi_pool_kernel.cu
Labels: cla signed

#7588 Fix lint
  .github/workflows/lint.yml
  test/smoke_test.py
Labels: cla signed

#7589 Include dlls required for wheel building
  packaging/pre_build_script.sh
Labels: cla signed

#7591 Cleanup circleci binary generation
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
Labels: cla signed

#7587 Add deterministic, pure-Python roi_align implementation
  test/test_ops.py
  torchvision/ops/roi_align.py
Labels: cla signed

#7580 reinstate doc upload
  .github/workflows/docs.yml
Labels: module: documentation, module: ci, cla signed

#7593 add comments for ops LastLevelMaxPool to avoid potential confusion
  torchvision/ops/feature_pyramid_network.py
Labels: cla signed

#7600 fix version wrangling in docs
  .github/workflows/docs.yml
  docs/source/conf.py
Labels: module: documentation, cla signed

#7597 convert torch.split return to list in RAFT
  torchvision/prototype/models/depth/stereo/raft_stereo.py
Labels: cla signed, other

#7592 Add non-TS'able _resize_image_and_masks variant with less tensor ops
  torchvision/models/detection/transform.py
Labels: cla signed

#7613 remove unused kwargs from make_grid
  torchvision/utils.py
Labels: module: utils, cla signed, code quality

#7606 Remove addressed workaround in ResizeV2
  torchvision/transforms/v2/functional/_geometry.py
Labels: cla signed

#7596 Replaced gpuAtomicAdd by fastAtomicAdd
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_align_kernel.cu
  torchvision/csrc/ops/cuda/ps_roi_pool_kernel.cu
  torchvision/csrc/ops/cuda/roi_align_kernel.cu
  torchvision/csrc/ops/cuda/roi_pool_kernel.cu
Labels: cla signed

#7417 migrate cmake workflows from CircleCI to GHA
  .github/scripts/cmake.sh
  .github/scripts/setup-env.sh
  .github/workflows/build-cmake.yml
  packaging/windows/internal/cuda_install.bat
Labels: module: ci, cla signed

#7621 Improve "Illustration of Transform" docs
  gallery/plot_transforms.py
Labels: cla signed

#7623 fix lint
  gallery/plot_transforms.py
Labels: cla signed, code quality

#7616 Remove CUDA 11.7 builds; add 11.8
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests.yml
  test/test_models.py
Labels: module: ci, cla signed

#7622 fix system image library uninstallation on macos x86
  .github/scripts/setup-env.sh
Labels: module: ci, cla signed

#7632 Fix segfault in DeformConv2d when `mask` is None
  torchvision/ops/deform_conv.py
Labels: bug, module: ops, cla signed

#7635 Use the same CUDNN version on Windows as PyTorch
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#7639 pin numpy for Python 3.8
  setup.py
Labels: dependency issue, module: ci, cla signed

#7640 also list full conda env in CI
  .github/scripts/setup-env.sh
Labels: module: ci, cla signed

#7625 Avoid `_prims_common.check` in favor of `torch._check`
  torchvision/_meta_registrations.py
Labels: cla signed, core issue

#7641 only run pyav backend tests for VideoReader if av is available
  test/test_videoapi.py
Labels: module: tests, module: video, dependency issue, cla signed

#7646 Add discalimer about skipped video tests
  test/test_videoapi.py
Labels: cla signed

#7645 always install dependencies upfront with pip in CI
  .github/scripts/setup-env.sh
  setup.py
Labels: dependency issue, module: ci, cla signed
