Repository pytorch/vision, pull requests merged in 2023-03, with the labels that each got.

#7365 Extend TorchVision smoke tests to MPS
  test/smoke_test.py
Labels: cla signed

#7362 fix flaky test for rotate_bounding_box
  test/common_utils.py
  test/test_transforms_v2_functional.py
  test/transforms_v2_kernel_infos.py
Labels: module: tests, cla signed

#7367 [Cherry-pick for 0.15] Fix flaky test + add smoke test
  test/common_utils.py
  test/smoke_test.py
  test/test_transforms_v2_functional.py
  test/transforms_v2_kernel_infos.py
Labels: cla signed

#7359 Add smoke test Using a simple RN50 with torch.compile
  test/smoke_test.py
Labels: cla signed

#7369 increase timeout for Linux unittest CI on CPU
  .github/workflows/test-linux-cpu.yml
Labels: module: ci, cla signed

#7370 Use python 3.9 conda environment for cmake circleci workflows
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#7371 [Cherry-pick for 0.15] Use python 3.9 conda environment for cmake circleci workflows (#7370)
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#7354 remove Linux GPU unittest from CircleCI
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
Labels: module: ci, cla signed

#7189 consolidate Linux workflows on CPU and GPU
  .github/unittest.sh
  .github/workflows/test-linux-cpu.yml
  .github/workflows/test-linux-gpu.yml
  .github/workflows/test-linux.yml
Labels: module: ci, cla signed

#7377 fix code format
  test/smoke_test.py
Labels: cla signed, code quality

#7379 Skip some warning test on 3.10 to avoid MKL-related warning (and failure)
  test/test_transforms.py
  test/test_transforms_v2.py
Labels: cla signed

#7386 Execute compile smoke test only on linux, check that windows throws an exception
  test/smoke_test.py
Labels: cla signed

#7387 Assert Runtime Error for torch.compile on Python 3.11
  test/smoke_test.py
Labels: cla signed

#7388 Fix failing smoke test
  test/smoke_test.py
Labels: cla signed

#7394 Added an "s" to match the function name
  torchvision/__init__.py
Labels: cla signed

#7395 [Cherry-pick for 0.15] Fix warning message
  torchvision/__init__.py
Labels: cla signed

#7399 remove torch.hub tests
  .circleci/config.yml
  .circleci/config.yml.in
  test/test_hub.py
Labels: module: tests, module: hub, module: ci, cla signed

#7376 add macOS unittest to GHA
  .github/unittest.sh
  .github/workflows/test-m1.yml
  .github/workflows/test-macos.yml
  setup.py
Labels: module: ci, cla signed

#7396 port special tests from CircleCI to GHA
  .github/scripts/setup-env.sh
  .github/scripts/unittest.sh
  .github/workflows/test-linux.yml
  .github/workflows/test-macos.yml
  scripts/download_model_urls.py
Labels: module: ci, cla signed

#7404 guard against deprecation of binom_test
  test/test_ops.py
  test/test_transforms.py
Labels: cla signed

#7403 test_prototype_datasets_builtin: Properly close all streams
  test/test_prototype_datasets_builtin.py
Labels: cla signed

#7406 Add device check to `io.decode_image`
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_image.cpp
Labels: cla signed

#7408 Fix lint
  test/test_image.py
Labels: cla signed

#7409 fix lint c workflow
  .github/workflows/lint.yml
Labels: module: ci, cla signed

#7411 simplify ci env setup
  .github/scripts/setup-env.sh
  .github/workflows/lint.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-macos.yml
Labels: cla signed

#7364 Surface failing tests on GHA
  .github/scripts/unittest.sh
  .github/workflows/test-linux.yml
Labels: cla signed

#7416 also surface failing tests in prototype jobs
  .github/workflows/prototype-tests-linux-gpu.yml
Labels: module: ci, cla signed, prototype

#7419 Version number bump for vision
  .circleci/config.yml
  .circleci/config.yml.in
  version.txt
Labels: cla signed

#7407 [PoC] migrate docs workflow to GHA
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .github/workflows/docs.yml
Labels: module: documentation, module: ci, cla signed

#7422 Mark 0.15 as stable version
  versions.html
Labels: cla signed

#7400 bump version
  README.rst
  ios/LibTorchvision.podspec
  version.txt
Labels: cla signed, other

#7427 Minor doc typo fix
  docs/source/models/fcos.rst
Labels: enhancement, module: documentation, cla signed

#7435 Add a workflow to update the viable/strict branch
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#7441 Fixed the typo in the "Update viable/strict" workflow.
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#7442 move parameter sampling of RandomPhotometricDistort into _get_params
  torchvision/transforms/v2/_color.py
Labels: bug, module: transforms, cla signed

#7447 fix test_detection_preset for ssd data augmentation
  test/test_transforms_v2.py
Labels: module: transforms, module: tests, cla signed

#7446 prevent unwrapping in SanitizeBoundingBoxes
  test/test_transforms_v2.py
  torchvision/transforms/v2/_misc.py
Labels: bug, module: transforms, cla signed

#7449 MovingMNIST split fix
  test/test_datasets.py
  torchvision/datasets/moving_mnist.py
Labels: bug, module: datasets, cla signed

#7444 [Cherry-pick for 0.15.2] move parameter sampling of RandomPhotometricDistort into _get_params
  test/test_transforms_v2.py
  torchvision/transforms/v2/_color.py
Labels: cla signed

#7451 [CHERRY-PICK] MovingMNIST split fix (#7449)
  test/test_datasets.py
  torchvision/datasets/moving_mnist.py
Labels: cla signed

#7450 [CHERRY-PICK] prevent unwrapping in SanitizeBoundingBoxes (#7446)
  test/test_transforms_v2.py
  torchvision/transforms/v2/_misc.py
Labels: cla signed

#7448 SymIntify roi_align
  torchvision/__init__.py
  torchvision/_meta_registrations.py
  torchvision/csrc/ops/autograd/roi_align_kernel.cpp
  torchvision/csrc/ops/roi_align.cpp
  torchvision/csrc/ops/roi_align.h
Labels: cla signed

#7464 Update C++ standard to C++17
  setup.py
Labels: cla signed

#7459 prepare doc preview s3-prefix for future change
  .github/workflows/docs.yml
Labels: module: documentation, module: ci, cla signed

#7467 kill ONNX / extended unittest workflows on CircleCI
  .circleci/config.yml
  .circleci/config.yml.in
Labels: module: ci, cla signed

#7470 cleanup CircleCI config
  .circleci/config.yml
  .circleci/config.yml.in
Labels: module: ci, cla signed, code quality

#7477 fix ImagePair MAE comparison
  test/common_utils.py
Labels: module: tests, cla signed, core issue

#7479 Unblock viable/strict branch
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#7480 Update docstring of Resize with shape constraint
  torchvision/transforms/transforms.py
Labels: enhancement, module: documentation, cla signed
