Repository pytorch/vision, pull requests merged in 2023-12, with the labels that each got.

#8140 remove redundant typing casts
  torchvision/prototype/tv_tensors/_label.py
  torchvision/transforms/v2/_geometry.py
Labels: cla signed, other

#8139 add Imagenette dataset
  docs/source/datasets.rst
  test/test_datasets.py
  torchvision/datasets/__init__.py
  torchvision/datasets/imagenette.py
  torchvision/tv_tensors/_dataset_wrapper.py
Labels: module: datasets, new feature, cla signed

#8148 Avoid segfault in VideoClip test
  test/test_datasets_video_utils.py
Labels: cla signed

#8144 Add manual opcheck tests for roi ops
  test/optests_failures_dict.json
  test/test_ops.py
Labels: cla signed

#8149 S390x big endian fixes
  test/test_transforms.py
  torchvision/datasets/mnist.py
  torchvision/transforms/functional.py
Labels: cla signed

#8153 Update `main` version to 18.0a0. Also update README
  README.md
  version.txt
Labels: cla signed

#8158 disable download progress for smoke test weights
  test/smoke_test.py
Labels: module: ci, cla signed, other

#8161 Explicitly ignore all video decoding tests
  .github/scripts/unittest.sh
Labels: cla signed

#8164 Fix root path expansion in `datasets.Kitti` (#8163)
  torchvision/datasets/kitti.py
Labels: cla signed

#8165 [Cherry-pick for 0.17] Fix root path expansion in datasets.Kitti
  torchvision/datasets/kitti.py
Labels: bug, module: datasets, cla signed

#8105 [TorchFix] Add weights_only to torch.load
  references/classification/train.py
  references/classification/train_quantization.py
  references/classification/utils.py
  references/depth/stereo/cascade_evaluation.py
  references/depth/stereo/train.py
  references/detection/train.py
  references/optical_flow/train.py
  references/segmentation/train.py
  references/similarity/train.py
  references/video_classification/train.py
  test/test_functional_tensor.py
  test/test_models.py
  test/test_prototype_datasets_builtin.py
  test/test_transforms_v2.py
  test/test_utils.py
  torchvision/datasets/imagenet.py
  torchvision/datasets/mnist.py
  torchvision/datasets/phototour.py
Labels: cla signed

#8150 support of float dtypes for draw_segmentation_masks
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#8174 [oidc] switch linux wheels to oidc
  .github/workflows/build-wheels-linux.yml
Labels: cla signed

#8176 Revert "[oidc] switch linux wheels to oidc"
  .github/workflows/build-wheels-linux.yml
Labels: cla signed

#8173 Improve io.videoreader pyav backend performance
  torchvision/io/video_reader.py
Labels: cla signed

#8171 use torch.where over boolean masking
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, cla signed, pt2

#8177 Revert "Revert "[oidc] switch linux wheels to oidc""
  .github/workflows/build-wheels-linux.yml
Labels: cla signed

#8178 Revert "Revert "Revert "[oidc] switch linux wheels to oidc"""
  .github/workflows/build-wheels-linux.yml
Labels: cla signed

#8181 Pin expecttest to restore CI
  .github/scripts/unittest.sh
Labels: cla signed

#8180 Pass use_reentrant for checkpoint
  torchvision/models/densenet.py
Labels: cla signed

#8185 exclude expecttest==0.2.0
  .github/scripts/unittest.sh
Labels: dependency issue, module: ci, cla signed
