Repository pytorch/vision, pull requests merged in 2023-04, with the labels that each got.

#7484 Add missing paper link for mvitv2
  torchvision/models/video/mvit.py
Labels: enhancement, module: documentation, cla signed

#7487 Fix mvitv2 docstring format
  torchvision/models/video/mvit.py
Labels: cla signed

#7475 enable Windows CPU CI on GHA
  .github/scripts/setup-env.sh
  .github/scripts/unittest.sh
  .github/workflows/test-windows.yml
Labels: module: ci, cla signed

#7485 Added allowed_workflows to pytorch probot
  .github/pytorch-probot.yml
Labels: cla signed

#7499 Remove cmake for update viable/strict
  .github/workflows/update-viablestrict.yml
Labels: module: ci, cla signed

#7502 Improved configuration naming for repetitive workflows
  .github/pytorch-probot.yml
Labels: cla signed

#7488 only return small set of targets by default from dataset wrapper
  gallery/plot_transforms_v2_e2e.py
  test/datasets_utils.py
  test/test_datasets.py
  torchvision/datapoints/_dataset_wrapper.py
Labels: enhancement, module: datasets, module: transforms, cla signed

#7500 Only do meta registrations if we have the ops
  torchvision/_meta_registrations.py
Labels: cla signed

#7505 Remove temporary channel for python 3.11
  packaging/build_conda.sh
Labels: cla signed

#7511 add image_id to the default return for wrapped CocoDetection
  torchvision/datapoints/_dataset_wrapper.py
Labels: module: datasets, cla signed

#7514 add example for v2 wrapping for custom datasets
  gallery/plot_datapoints.py
  torchvision/datapoints/_dataset_wrapper.py
Labels: module: datasets, module: documentation, cla signed, module: datapoints

#7526 disable Windows CPU unittests on CircleCI
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
Labels: module: ci, cla signed

#7531 [Release only change] Advance version for minor release
  .circleci/config.yml
  .circleci/config.yml.in
  version.txt
Labels: cla signed

#7532 Remove temporary channel for python 3.11 (#7505)
  packaging/build_conda.sh
Labels: cla signed

#7520 fix color in draw_segmentation_masks
  test/test_utils.py
  torchvision/utils.py
Labels: enhancement, module: utils, cla signed

#7533 Add CUDA 12.1 builds
  .circleci/config.yml
  .circleci/regenerate.py
  .circleci/unittest/windows/scripts/install.sh
  packaging/pkg_helpers.bash
  packaging/windows/internal/cuda_install.bat
Labels: cla signed
