Repository pytorch/vision, pull requests merged in 2023-08, with the labels that each got.

#7734 remove spatial_size
  gallery/plot_datapoints.py
  gallery/plot_transforms_v2.py
  test/common_utils.py
  test/test_datapoints.py
  test/test_prototype_transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/test_transforms_v2_utils.py
  test/transforms_v2_kernel_infos.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_dataset_wrapper.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_deprecated.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/utils.py
Labels: module: transforms, cla signed, code quality

#7779 Allow catch-all 'others' key in fill dicts. Avoid need for defaultdict.
  gallery/plot_transforms_v2_e2e.py
  references/segmentation/presets.py
  references/segmentation/v2_extras.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_misc.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_utils.py
Labels: cla signed

#7784 Cutmix -> CutMix
  docs/source/transforms.rst
  references/classification/transforms.py
  test/test_prototype_transforms.py
  test/test_transforms_v2_refactored.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_augment.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_utils.py
Labels: cla signed

#7789 Fix docs
  gallery/plot_cutmix_mixup.py
Labels: module: documentation, other

#7643 Add MPS kernels
  .github/scripts/run-clang-format.py
  CMakeLists.txt
  setup.py
  test/common_utils.py
  test/conftest.py
  test/test_ops.py
  torchvision/csrc/ops/cpu/nms_kernel.cpp
  torchvision/csrc/ops/mps/mps_helpers.h
  torchvision/csrc/ops/mps/mps_kernels.h
  torchvision/csrc/ops/mps/nms_kernel.mm
  torchvision/csrc/ops/mps/ps_roi_align_kernel.mm
  torchvision/csrc/ops/mps/ps_roi_pool_kernel.mm
  torchvision/csrc/ops/mps/roi_align_kernel.mm
  torchvision/csrc/ops/mps/roi_pool_kernel.mm
  torchvision/ops/roi_align.py
Labels: cla signed

#7747 refactor Datapoint dispatch mechanism
  test/common_utils.py
  test/datasets_utils.py
  test/test_transforms_v2.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
  torchvision/datapoints/__init__.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
  torchvision/transforms/v2/functional/_utils.py
Labels: cla signed

#7793 Use `# %%` syntax for gallery examples
  gallery/plot_datapoints.py
  gallery/plot_optical_flow.py
  gallery/plot_repurposing_annotations.py
  gallery/plot_scripted_tensor_transforms.py
  gallery/plot_transforms.py
  gallery/plot_transforms_v2.py
  gallery/plot_transforms_v2_e2e.py
  gallery/plot_video_api.py
  gallery/plot_visualization_utils.py
Labels: cla signed

#7792 Fix typo in setup.py
  setup.py
Labels: cla signed

#7787 Remove cutmix and mixup from prototype
  test/test_prototype_transforms.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_augment.py
Labels: module: transforms, cla signed, prototype, other

#7796 Allow register_kernel() to take dispatcher name as input
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/functional/_utils.py
Labels: cla signed

#7783 cleanup spatial_size -> canvas_size
  test/common_utils.py
  test/test_transforms_v2_functional.py
Labels: module: tests, cla signed, other

#7795 Add tuto for custom transforms and custom datapoints in gallery example
  docs/source/conf.py
  docs/source/datapoints.rst
  docs/source/transforms.rst
  gallery/plot_custom_datapoints.py
  gallery/plot_custom_transforms.py
  gallery/plot_datapoints.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/prototype/datapoints/_label.py
  torchvision/transforms/v2/functional/_utils.py
Labels: cla signed

#7797 register tensor and PIL kernel the same way as datapoints
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
  torchvision/transforms/v2/functional/_utils.py
Labels: module: transforms, cla signed, code quality

#7805 Remove `_wrap()` class method from base class Datapoint
  test/test_datapoints.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/prototype/datapoints/_label.py
Labels: cla signed

#7810 Change default pytest traceback from native to short
  pytest.ini
Labels: cla signed

#7624 add PermuteChannels transform
  docs/source/transforms.rst
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_color.py
Labels: enhancement, module: transforms, cla signed

#7812 cleanup v2 tests
  test/test_transforms_v2_refactored.py
Labels: module: transforms, module: tests, cla signed, code quality

#7814 remove custom types defintions from datapoints module
  torchvision/datapoints/__init__.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_video.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_misc.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/_utils.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_deprecated.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
  torchvision/transforms/v2/functional/_utils.py
Labels: module: transforms, cla signed, code quality

#7806 Simplify _NO_WRAPPING_EXCEPTIONS
  test/test_datapoints.py
  torchvision/datapoints/_datapoint.py
Labels: cla signed

#7820 Clean up jpeg tests
  test/test_image.py
Labels: cla signed

#7804 move passthrough for unknown types from dispatchers to transforms
  test/test_prototype_transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_refactored.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/_transform.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
  torchvision/transforms/v2/functional/_utils.py
Labels: module: transforms, cla signed

#7815 Adding aarch64 linux builds
  .github/workflows/build-wheels-aarch64-linux.yml
  packaging/wheel/relocate.py
Labels: cla signed

#7826 Fix typo in gallery/plot_transforms_v2_e2e.py
  gallery/plot_transforms_v2_e2e.py
Labels: cla signed

#7825 Allow users to choose whether to return Datapoint subclasses or pure Tensor
  docs/source/datapoints.rst
  test/test_datapoints.py
  torchvision/datapoints/__init__.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_torch_function_helpers.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/_utils.py
Labels: cla signed

#7829 Dispatcher -> Functional
  gallery/plot_custom_datapoints.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_transform.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_utils.py
Labels: cla signed

#7754 Replace stack/mask/reduce by indexing in _hsv2rgb
  torchvision/transforms/v2/functional/_color.py
Labels: cla signed

#7830 More datapoints docs and comments
  gallery/plot_custom_datapoints.py
  gallery/plot_datapoints.py
  test/test_datapoints.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_torch_function_helpers.py
  torchvision/transforms/v2/functional/_utils.py
Labels: cla signed

#7835 allow dispatch to PIL image subclasses
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/functional/_utils.py
Labels: bug, module: transforms, cla signed

#7838 fix elastic error
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: bug, module: transforms, cla signed

#7831 make PIL kernels private
  docs/source/transforms.rst
  gallery/plot_transforms_v2_e2e.py
  references/detection/presets.py
  references/segmentation/presets.py
  test/common_utils.py
  test/test_prototype_transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/test_transforms_v2_utils.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
  torchvision/prototype/transforms/_augment.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_type_conversion.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_deprecated.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_type_conversion.py
Labels: module: transforms, cla signed, code quality

#7841 fix elastic tests
  test/test_transforms_v2_refactored.py
Labels: bug, module: tests, cla signed

#7843 Add google collab link for gallery examples
  .github/workflows/docs.yml
  gallery/plot_datapoints.py
Labels: cla signed

#7845 Fixed few typos in docs for type conversion transforms
  torchvision/transforms/v2/_type_conversion.py
Labels: cla signed

#7823 Add ToPureTensor transform
  docs/source/transforms.rst
  references/classification/presets.py
  references/detection/presets.py
  references/segmentation/presets.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_type_conversion.py
Labels: cla signed

#7840 Fixed setup.py when missing libjpeg
  README.md
  torchvision/csrc/io/image/cpu/decode_jpeg.cpp
Labels: cla signed

#7726 Don't error on cuda minor version mismatch
  torchvision/extension.py
Labels: cla signed

#7847 Cleanup README.md
  CONTRIBUTING.md
  README.md
  docs/source/io.rst
Labels: cla signed

#7851 increase HTTP post buffer for doc upload
  .github/workflows/docs.yml
Labels: module: documentation, module: ci, cla signed

#7849 Split example gallery into subsections
  docs/source/conf.py
  docs/source/datapoints.rst
  docs/source/transforms.rst
  docs/source/utils.rst
  gallery/README.rst
  gallery/others/README.rst
  gallery/others/plot_optical_flow.py
  gallery/others/plot_repurposing_annotations.py
  gallery/others/plot_scripted_tensor_transforms.py
  gallery/others/plot_transforms.py
  gallery/others/plot_video_api.py
  gallery/others/plot_visualization_utils.py
  gallery/v2_transforms/README.rst
  gallery/v2_transforms/plot_custom_datapoints.py
  gallery/v2_transforms/plot_custom_transforms.py
  gallery/v2_transforms/plot_cutmix_mixup.py
  gallery/v2_transforms/plot_datapoints.py
  gallery/v2_transforms/plot_transforms_v2.py
  gallery/v2_transforms/plot_transforms_v2_e2e.py
  torchvision/datapoints/_datapoint.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/functional/_utils.py
Labels: enhancement, module: documentation, cla signed

#7842 separate transforms v2 legacy test utils
  test/common_utils.py
  test/prototype_common_utils.py
  test/test_datapoints.py
  test/test_prototype_transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/test_transforms_v2_utils.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
  test/transforms_v2_legacy_utils.py
Labels: module: tests, cla signed, code quality

#7853 Remove import-time warning for v2 namespaces
  docs/source/conf.py
  gallery/v2_transforms/plot_custom_datapoints.py
  gallery/v2_transforms/plot_custom_transforms.py
  gallery/v2_transforms/plot_cutmix_mixup.py
  gallery/v2_transforms/plot_datapoints.py
  gallery/v2_transforms/plot_transforms_v2.py
  gallery/v2_transforms/plot_transforms_v2_e2e.py
  test/conftest.py
  test/test_transforms_v2.py
  torchvision/__init__.py
  torchvision/datapoints/__init__.py
  torchvision/datasets/__init__.py
  torchvision/transforms/v2/__init__.py
Labels: cla signed

#7854 Add links to collab
  .github/workflows/docs.yml
  docs/source/conf.py
  gallery/others/plot_optical_flow.py
  gallery/others/plot_repurposing_annotations.py
  gallery/others/plot_scripted_tensor_transforms.py
  gallery/others/plot_transforms.py
  gallery/others/plot_video_api.py
  gallery/others/plot_visualization_utils.py
  gallery/v2_transforms/plot_custom_datapoints.py
  gallery/v2_transforms/plot_custom_transforms.py
  gallery/v2_transforms/plot_cutmix_mixup.py
  gallery/v2_transforms/plot_datapoints.py
  gallery/v2_transforms/plot_transforms_v2.py
  gallery/v2_transforms/plot_transforms_v2_e2e.py
Labels: cla signed

#7855 remove batch_dims from make bounding boxes and detection masks
  test/common_utils.py
Labels: module: tests, cla signed, code quality

#7858 Fix typos in docstrings
  cmake/iOS.cmake
  docs/source/models/fcos.rst
  docs/source/models/retinanet.rst
  docs/source/models/vgg.rst
  gallery/others/plot_optical_flow.py
  gallery/v2_transforms/plot_custom_transforms.py
  test/test_models.py
  torchvision/datapoints/_dataset_wrapper.py
  torchvision/datasets/_stereo_matching.py
  torchvision/io/video_reader.py
  torchvision/transforms/v2/_geometry.py
Labels: cla signed

#7857 CONTRIBUTING.md: Remove trailing whitespaces
  CONTRIBUTING.md
Labels: cla signed

#7859 Revamp transforms doc
  docs/source/datapoints.rst
  docs/source/datasets.rst
  docs/source/transforms.rst
  gallery/v2_transforms/README.rst
  gallery/v2_transforms/plot_datapoints.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
  torchvision/datapoints/_dataset_wrapper.py
  torchvision/datapoints/_torch_function_helpers.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_deprecated.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
  torchvision/transforms/v2/functional/_type_conversion.py
  torchvision/transforms/v2/functional/_utils.py
Labels: enhancement, module: transforms, module: documentation, cla signed

#7839 Fixed issue with jitted AA transforms in v2 and added tests
  test/test_transforms_v2_consistency.py
  torchvision/transforms/v2/_auto_augment.py
Labels: cla signed

#7863 Make v2.utils private.
  references/segmentation/v2_extras.py
  test/test_prototype_datasets_builtin.py
  test/test_prototype_transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_utils.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_misc.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_transform.py
  torchvision/transforms/v2/_type_conversion.py
  torchvision/transforms/v2/_utils.py
  torchvision/transforms/v2/utils.py
Labels: cla signed

#7864 clarifying docs for v2.ToPILImage()
  torchvision/transforms/v2/_type_conversion.py
Labels: enhancement, module: documentation, cla signed

#7870 Re-write getting started guide for transforms V2
  docs/source/conf.py
  docs/source/transforms.rst
  gallery/v2_transforms/helpers.py
  gallery/v2_transforms/plot_datapoints.py
  gallery/v2_transforms/plot_transforms_v2.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/transforms/v2/_misc.py
Labels: enhancement, module: documentation, cla signed

#7867 Convert v2 doc warning into a note
  docs/source/beta_status.py
Labels: enhancement, module: documentation, cla signed

#7869 Update coco_utils.py
  references/detection/coco_utils.py
Labels: cla signed

#7872 Fix aarch64 builds
  packaging/pre_build_script.sh
Labels: cla signed

#7874 disable tests for vit op counts
  test/common_extended_utils.py
  test/test_extended_models.py
Labels: module: models, module: tests, module: ci, cla signed, core issue

#7860 enforce pickleability for v2 transforms and wrapped datasets
  test/datasets_utils.py
  test/test_datasets.py
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  torchvision/datapoints/_dataset_wrapper.py
  torchvision/datasets/widerface.py
Labels: enhancement, module: transforms, cla signed

#7880 Stricter SanitizeBoundingBoxes labels_getter heuristic
  gallery/v2_transforms/plot_transforms_v2.py
  test/test_transforms_v2.py
  torchvision/transforms/v2/_utils.py
Labels: bug, module: transforms, cla signed

#7741 Added support for CMYK in decode_jpeg
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_jpeg.cpp
Labels: cla signed

#7862 Replaced ConvertImageDtype by ToDtype in reference scripts
  references/classification/presets.py
  references/detection/presets.py
  references/detection/transforms.py
  references/segmentation/presets.py
  references/segmentation/transforms.py
  references/segmentation/v2_extras.py
Labels: cla signed

#7856 port remaining resize tests
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
Labels: module: transforms, cla signed

#7881 Rewrite transforms v2 e2e example
  gallery/v2_transforms/helpers.py
  gallery/v2_transforms/plot_transforms_v2.py
  gallery/v2_transforms/plot_transforms_v2_e2e.py
Labels: enhancement, module: documentation, cla signed

#7883 Improvements to gallery
  docs/source/conf.py
  docs/source/datapoints.rst
  docs/source/transforms.rst
  gallery/transforms/README.rst
  gallery/transforms/helpers.py
  gallery/transforms/plot_custom_datapoints.py
  gallery/transforms/plot_custom_transforms.py
  gallery/transforms/plot_cutmix_mixup.py
  gallery/transforms/plot_datapoints.py
  gallery/transforms/plot_transforms_e2e.py
  gallery/transforms/plot_transforms_getting_started.py
  gallery/v2_transforms/README.rst
  torchvision/datapoints/_datapoint.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/functional/_utils.py
Labels: enhancement, module: documentation, cla signed

#7886 Make transforms illutration example use v2 instead of v1
  docs/source/conf.py
  gallery/others/plot_scripted_tensor_transforms.py
  gallery/transforms/helpers.py
  gallery/transforms/plot_transforms_illustrations.py
Labels: enhancement, module: transforms, module: documentation, cla signed

#7882 Enable v1 vs. v2 consistency in refactored tests
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_refactored.py
Labels: module: transforms, module: tests, cla signed

#7884 improve affine bounding box reference helper
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, module: tests, cla signed

#7889 Redo torchscript example
  docs/source/transforms.rst
  gallery/others/plot_scripted_tensor_transforms.py
  gallery/transforms/plot_transforms_getting_started.py
Labels: enhancement, module: documentation, cla signed

#7898 Fix weight download URLs
  torchvision/models/efficientnet.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/shufflenetv2.py
Labels: bug, module: models, cla signed

#7900 Separate Test Token for Conda Uploads
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-conda-macos.yml
  .github/workflows/build-conda-windows.yml
Labels: cla signed

#7905 Avoid / silence warnings in refactored tests
  test/test_transforms_v2_refactored.py
Labels: cla signed

#7908 remove trailing _tensor from image kernel checks
  test/test_transforms_v2_refactored.py
Labels: module: transforms, module: tests, cla signed, code quality

#7906 Bunch of doc edits
  docs/source/transforms.rst
  docs/source/tv_tensors.rst
  gallery/README.rst
  gallery/transforms/plot_transforms_e2e.py
  gallery/transforms/plot_transforms_getting_started.py
Labels: enhancement, module: documentation, cla signed

#7902 port tests for F.erase and transforms.RandomErasing
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
Labels: module: transforms, module: tests, cla signed

#7887 Fixed sigma input type for v2.GaussianBlur
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_utils.py
Labels: cla signed

#7913 [Release-Only] Branch Cut - Bump vision Version 0.16.0
  .github/workflows/build-cmake.yml
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-conda-macos.yml
  .github/workflows/build-conda-windows.yml
  .github/workflows/build-wheels-aarch64-linux.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/build-wheels-macos.yml
  .github/workflows/build-wheels-windows.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests.yml
  .github/workflows/update-viablestrict.yml
  version.txt
Labels: cla signed

#7910 rename BoundingBoxes module to match class name
  torchvision/tv_tensors/__init__.py
  torchvision/tv_tensors/_bounding_boxes.py
Labels: cla signed, code quality, module: tv_tensors

#7914 Try to turn off DEBUG mode when building for release
  setup.py
Labels: cla signed

#7918 [Cherry pick] rename BoundingBoxes module to match class name (#7910)
  torchvision/tv_tensors/__init__.py
  torchvision/tv_tensors/_bounding_boxes.py
Labels: cla signed, other

#7919 allow sequence fill for v2 AA scripted
  test/test_transforms_v2_consistency.py
  torchvision/transforms/v2/_auto_augment.py
Labels: bug, module: transforms, cla signed

#7920 [CHERRYPICK] allow sequence fill for v2 AA scripted
  test/test_transforms_v2_consistency.py
  torchvision/transforms/v2/_auto_augment.py
Labels: cla signed

#7907 downgrade warnign for F.rotate with center and expand=True
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, module: documentation, cla signed

#7921 [CHERRYPICK] downgrade warnign for F.rotate with center and expand=True
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: cla signed
