Repository pytorch/vision, pull requests merged in 2023-06, with the labels that each got.

#7634 disable tf32 in cuDNN for classification models
  test/test_models.py
Labels: module: ci, cla signed

#7648 dont reinstall CUDA in CMake / Windows workflow
  .github/scripts/setup-env.sh
  .github/workflows/build-cmake.yml
  packaging/windows/internal/cuda_install.bat
Labels: module: ci, cla signed

#7656 Remove unused packaging/pkg_helpers.bash, Remove CONDA_CHANNEL_FLAGS
  packaging/pkg_helpers.bash
  packaging/pre_build_script.sh
Labels: cla signed

#7665 fix bug when using PIL backend in references/classification
  references/classification/presets.py
Labels: cla signed

#7662 Typo backbone_utils.py
  torchvision/models/detection/backbone_utils.py
Labels: cla signed

#7669 Fix: don't call round() on float images for ResizeV2
  test/test_transforms_v2_functional.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: bug, module: transforms, cla signed

#7668 Add uint8 bicubic support to ResizeV2
  test/test_transforms_v2_consistency.py
  test/transforms_v2_kernel_infos.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: cla signed

#7678 remove obsolete transforms tests
  test/test_functional_tensor.py
Labels: module: transforms, module: tests, cla signed, code quality

#7673 Simpler file chunking
  packaging/wheel/relocate.py
  torchvision/datasets/utils.py
  torchvision/prototype/datasets/_builtin/README.md
  torchvision/prototype/datasets/utils/_resource.py
Labels: cla signed, code quality

#7677 Add objc clang format
  .clang-format
  .pre-commit-config.yaml
Labels: cla signed

#7687 Rename cpu_and_gpu into cpu_and_cuda
  test/common_utils.py
  test/conftest.py
  test/test_functional_tensor.py
  test/test_models.py
  test/test_ops.py
  test/test_prototype_models.py
  test/test_transforms_tensor.py
  test/test_transforms_v2.py
  test/test_transforms_v2_functional.py
Labels: cla signed, code quality, other

#7685 fix mypy
  torchvision/models/_api.py
Labels: cla signed, other

#7688 Udate google analytics ID
  docs/source/conf.py
Labels: module: documentation, cla signed, other

#7562 [PoC] refactor transforms v2 tests
  test/common_utils.py
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
Labels: module: transforms, module: tests, cla signed

#7691 Fix heap buffer overflow in `decode_png`
  test/assets/toosmall_png/heapbof.png
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_png.cpp
Labels: cla signed

#7686 Fix ShuffleNet ONNX export
  torchvision/models/shufflenetv2.py
Labels: bug, module: models, module: onnx, cla signed

#7693 Fix test RNG
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_refactored.py
Labels: cla signed

#7694 CMake build using VS2022
  .github/scripts/setup-env.sh
  .github/workflows/build-cmake.yml
  .github/workflows/tests.yml
  packaging/windows/internal/vc_env_helper.bat
  packaging/windows/internal/vc_install_helper.sh
Labels: cla signed

#7684 Add GPU support for draw_segmentation_masks
  test/test_utils.py
  torchvision/utils.py
Labels: enhancement, module: utils, cla signed

#7695 Fix typos in mobilenetv3 docstrings
  torchvision/models/mobilenetv3.py
Labels: enhancement, module: documentation, cla signed

#7679 clarifying docs for ToPILImage()
  torchvision/transforms/transforms.py
Labels: enhancement, module: transforms, module: documentation, cla signed

#7701 make datapoints deepcopyable
  test/test_datapoints.py
  test/test_prototype_datapoints.py
  torchvision/datapoints/_datapoint.py
Labels: cla signed, module: datapoints

#7702 fix to_grayscale deprecation warning
  torchvision/transforms/v2/functional/_deprecated.py
Labels: cla signed

#7703 port horizontal flip tests
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, module: tests, cla signed

#7707 undeprecate to_grayscale
  test/test_transforms_v2_functional.py
  torchvision/transforms/functional.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_deprecated.py
Labels: module: transforms, cla signed

#7709 fix formatting in test_functional_tensor.py
  test/test_functional_tensor.py
Labels: cla signed, code quality, other

#7710 ignore #7709 in git blame
  .git-blame-ignore-revs
Labels: cla signed, code quality, other

#7708 port affine tests
  test/test_transforms_v2.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
Labels: module: transforms, module: tests, cla signed

#7712 port vertical flip
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, module: tests, cla signed
