Repository pytorch/vision, pull requests merged in 2023-02, with the labels that each got.

#7156 Fixed typo in models.rst
  docs/source/models.rst
Labels: enhancement, module: documentation, cla signed

#7072 Fix quantized classif reference - missing args
  references/classification/train.py
Labels: bug, module: reference scripts, cla signed

#7142 Update docs to not mention 'registration mechanism' - and move corresponding utils out of Beta
  docs/source/models.rst
  torchvision/models/_api.py
Labels: enhancement, module: documentation, cla signed

#7153 enable get_params alias for transforms v2
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/transforms/_transform.py
Labels: module: transforms, cla signed, prototype

#7163 Deprecate CUDA 11.6 from CI, move to 11.7
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/unittest/windows/scripts/install.sh
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/test-linux-gpu.yml
Labels: cla signed

#7164 remove GTSRB from detection dataset list
  docs/source/datasets.rst
Labels: module: datasets, module: documentation, cla signed

#7161 fix docstring of CelebA regarding arrays
  torchvision/datasets/celeba.py
Labels: module: datasets, module: documentation, cla signed

#7100 Make WeightEnum and Weights public + cleanups
  test/test_extended_models.py
  torchvision/models/__init__.py
  torchvision/models/_api.py
Labels: cla signed

#7172 Fix resnet_fpn_backbone(pretrained=True)
  test/test_extended_models.py
  torchvision/models/_api.py
  torchvision/models/detection/backbone_utils.py
Labels: cla signed

#7178 Remove Excess Py3.8 Linux Wheels Builds
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#7183 Remove cu116 from circleci
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#7186 [CI] Add `nvjpeg` for Windows CUDA-11.8 builds
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#7181 fix gradle link
  .circleci/unittest/android/scripts/install_gradle.sh
Labels: module: ci, cla signed

#7176 remove functionality scheduled for 0.15 after deprecation
  test/test_functional_tensor.py
  test/test_prototype_transforms_consistency.py
  test/test_transforms.py
  torchvision/datasets/utils.py
  torchvision/models/alexnet.py
  torchvision/models/densenet.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/vgg.py
  torchvision/models/vision_transformer.py
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: module: models, module: transforms, cla signed, bc-breaking

#7177 make transforms v2 get_params a staticmethod
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/transforms/_transform.py
Labels: bug, module: transforms, cla signed, prototype

#7190 fix prototype consistency tests
  test/test_prototype_transforms_consistency.py
Labels: module: transforms, module: tests, cla signed, prototype

#7170 introduce heuristic for simple tensor handling of transforms v2
  test/test_prototype_transforms.py
  torchvision/prototype/transforms/_misc.py
  torchvision/prototype/transforms/_transform.py
Labels: module: transforms, cla signed, prototype

#7196 fix error message if v2 transform is not JIT scriptable
  torchvision/prototype/transforms/_transform.py
Labels: bug, module: transforms, cla signed, prototype

#7199 Windows Python 3.11 Support in CircleCI
  .circleci/config.yml
  .circleci/regenerate.py
Labels: cla signed

#7203 update usages of torch.testing internals
  test/prototype_common_utils.py
  test/test_prototype_datasets_builtin.py
Labels: module: tests, cla signed, prototype, core issue

#7202 Put back previous tolerance for test_classification and test_video
  test/test_models.py
Labels: cla signed

#7197 allow nn.ModuleList in RandomApply
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/transforms/_container.py
Labels: module: transforms, cla signed, prototype

#7204 Test some flaky detection models on float64 instead of float32
  test/test_models.py
Labels: cla signed

#7206 Increase tolerance fo resnet101 model test
  test/test_models.py
Labels: module: models, module: tests, cla signed

#7209 fix: use `inplace=None` as default in `ops.MLP`
  torchvision/ops/misc.py
Labels: bug, module: models, cla signed, bc-breaking

#6970 skip CPU tests on GPU GHA jobs
  test/common_utils.py
  test/conftest.py
Labels: module: tests, module: ci, cla signed

#7212 [CI] Tweak numpy constraints
  packaging/torchvision/meta.yaml
Labels: cla signed

#7216 remove videos from test for DatasetFolder
  test/test_datasets.py
Labels: enhancement, module: datasets, module: tests, cla signed

#6663 [PoC] compatibility layer between stable datasets and prototype transforms
  test/datasets_utils.py
  test/test_datasets.py
  torchvision/prototype/datapoints/__init__.py
  torchvision/prototype/datapoints/_dataset_wrapper.py
Labels: cla signed

#7154 remove datapoints compatibility for prototype datasets
  test/test_prototype_datasets_builtin.py
  torchvision/prototype/datapoints/_datapoint.py
  torchvision/prototype/datasets/_builtin/caltech.py
  torchvision/prototype/datasets/_builtin/celeba.py
  torchvision/prototype/datasets/_builtin/coco.py
  torchvision/prototype/datasets/_builtin/cub200.py
  torchvision/prototype/datasets/_builtin/sbd.py
Labels: module: datasets, cla signed, code quality, prototype, module: datapoints

#7218 Skip model test for vit_h_14
  test/test_models.py
Labels: cla signed

#7225 fix COCO box format in dataset wrapper
  torchvision/prototype/datapoints/_dataset_wrapper.py
Labels: module: datasets, module: transforms, cla signed, prototype

#7223 Add tests for transform presets, and various fixes
  test/test_prototype_transforms.py
  torchvision/prototype/transforms/_auto_augment.py
  torchvision/prototype/transforms/_color.py
  torchvision/prototype/transforms/_transform.py
Labels: cla signed

#7226 add tests for perspective start- / endpoints
  test/prototype_transforms_kernel_infos.py
  torchvision/prototype/datapoints/_bounding_box.py
Labels: bug, module: transforms, module: tests, cla signed, prototype

#7227 make clamp_bounding_box a kernel / dispatcher hybrid
  test/prototype_common_utils.py
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/_meta.py
  torchvision/prototype/transforms/functional/_meta.py
Labels: module: transforms, cla signed, prototype

#7228 make convert_format_bounding_box a hybrid kernel dispatcher
  test/prototype_common_utils.py
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/_meta.py
  torchvision/prototype/transforms/functional/_meta.py
Labels: module: transforms, cla signed, prototype

#7211 Fixed issues with dtype in geom functional transforms v2
  test/prototype_common_utils.py
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms_consistency.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/transforms/_misc.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/transforms.py
Labels: cla signed

#7229 fix {convert_format, clamp}_bounding_box
  torchvision/prototype/transforms/functional/_meta.py
Labels: bug, module: transforms, cla signed, prototype

#7230 only use plain tensors in kernel tests
  test/prototype_common_utils.py
  test/prototype_transforms_dispatcher_infos.py
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms_functional.py
Labels: module: transforms, module: tests, cla signed, prototype

#7232 unbatch image_id in CocoDetection wrapper
  torchvision/prototype/datapoints/_dataset_wrapper.py
Labels: module: datasets, module: transforms, cla signed, prototype

#7231 Image and Mask can accept PIL images
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_datapoints.py
  torchvision/prototype/datapoints/_dataset_wrapper.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_mask.py
Labels: cla signed

#7160 Change default of antialias parameter from None to 'warn'
  gallery/plot_optical_flow.py
  references/depth/stereo/transforms.py
  references/optical_flow/transforms.py
  references/video_classification/presets.py
  test/test_functional_tensor.py
  test/test_models.py
  test/test_prototype_transforms.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  torchvision/prototype/datapoints/_bounding_box.py
  torchvision/prototype/datapoints/_datapoint.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_mask.py
  torchvision/prototype/datapoints/_video.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_presets.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/_presets.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_tensor.py
  torchvision/transforms/transforms.py
Labels: cla signed

#7241 Undeprecate int constants for interpolation
  test/test_functional_tensor.py
  test/test_onnx.py
  test/test_transforms.py
  test/test_transforms_tensor.py
  torchvision/transforms/_pil_constants.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/transforms.py
Labels: module: transforms, cla signed, deprecation, revert(ed)

#7236 allow subclasses in dataset wrappers
  test/datasets_utils.py
  test/test_prototype_datapoints.py
  torchvision/prototype/datapoints/_dataset_wrapper.py
Labels: module: datasets, module: transforms, cla signed, prototype

#7234 Use `is False` for some antialias checks
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/functional.py
Labels: module: transforms, cla signed, code quality

#7244 Let LinearTransformation return datapoints instead of tensors
  torchvision/prototype/transforms/_misc.py
Labels: module: transforms, cla signed, prototype

#7243 Remove usage of torch._six
  torchvision/datasets/utils.py
  torchvision/datasets/vision.py
Labels: code quality

#7238 add proper smoke test for prototype transforms
  test/test_prototype_transforms.py
Labels: module: transforms, module: tests, cla signed, prototype

#7245 Remove unused import
  torchvision/datasets/vision.py
Labels: module: datasets, code quality

#7215 clamp bounding boxes in some geometry kernels
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/datapoints/_bounding_box.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_meta.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/prototype/transforms/functional/_meta.py
Labels: module: transforms, cla signed, prototype

#7237 Adding RC trigger to Build Workflows
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-conda-macos.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/build-wheels-macos.yml
Labels: cla signed

#7252 Fix some annotations in transforms v2 for JIT v1 compatibility
  test/prototype_transforms_dispatcher_infos.py
  test/prototype_transforms_kernel_infos.py
  torchvision/prototype/datapoints/_bounding_box.py
  torchvision/prototype/datapoints/_datapoint.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_mask.py
  torchvision/prototype/datapoints/_video.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_utils.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#7056 [ONNX] Fix dtype for NonMaxSuppression
  torchvision/ops/_register_onnx_ops.py
Labels: cla signed

#7248 Support integer values for interpolation in the prototype transforms
  test/test_prototype_transforms.py
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/datapoints/_bounding_box.py
  torchvision/prototype/datapoints/_datapoint.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_mask.py
  torchvision/prototype/datapoints/_video.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_auto_augment.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_presets.py
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#7253 add error for max_size with size sequence in resize
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#7246 Add SanitizeBoundingBoxes transform
  test/test_prototype_transforms.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_misc.py
Labels: cla signed

#7255 allow integer parameters in ColorJitter
  torchvision/prototype/transforms/_color.py
Labels: module: transforms, cla signed, prototype

#7254 Ten crop annotation
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: module: transforms, cla signed, prototype

#7256 Make RandomApply torchscriptable in V2
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/transforms/_container.py
  torchvision/prototype/transforms/_transform.py
Labels: cla signed

#7259 Copy paste prototype.datapoints and prototype.transforms out of prototype area
  torchvision/datapoints/__init__.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_dataset_wrapper.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_label.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_container.py
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_presets.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/_transform.py
  torchvision/transforms/v2/_type_conversion.py
  torchvision/transforms/v2/_utils.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_deprecated.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
  torchvision/transforms/v2/functional/_type_conversion.py
  torchvision/transforms/v2/functional/_utils.py
  torchvision/transforms/v2/utils.py
Labels: cla signed

#7249 [ONNX] misc improvements
  test/test_onnx.py
  torchvision/ops/_register_onnx_ops.py
Labels: cla signed

#7260 fix ten_crop datapoint return
  torchvision/prototype/transforms/functional/_geometry.py
Labels: module: transforms, cla signed, prototype

#7269 Deprecate functional_pil and functional_tensor and make them private
  test/prototype_common_utils.py
  test/prototype_transforms_kernel_infos.py
  test/test_functional_tensor.py
  test/test_transforms.py
  torchvision/transforms/_functional_pil.py
  torchvision/transforms/_functional_tensor.py
  torchvision/transforms/functional.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/functional_tensor.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
Labels: cla signed

#7224 Fix dropout issue in swin transformers
  torchvision/models/swin_transformer.py
  torchvision/models/video/swin_transformer.py
Labels: cla signed

#7266 make type alias private
  torchvision/datapoints/__init__.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_datapoint.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_misc.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/_utils.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_deprecated.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
Labels: module: transforms, cla signed, code quality, prototype

#7268 Make RandomIoUCrop compatible with SanitizeBoundingBoxes
  test/test_prototype_transforms.py
  test/test_prototype_transforms_consistency.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_misc.py
Labels: cla signed

#7258 make fill defaultdict an implementation detail
  torchvision/prototype/transforms/_geometry.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_transform.py
Labels: module: transforms, cla signed, prototype

#7263 Vision 3.11 Windows Conda Builds
  .circleci/config.yml
  .circleci/regenerate.py
  packaging/build_conda.sh
Labels: cla signed

#7273 Remove nit comment
  .circleci/regenerate.py
Labels: cla signed

#7270 Add a removable warning in torchvision.transforms.v2 and torchvision.datapoints
  test/conftest.py
  torchvision/__init__.py
  torchvision/datapoints/__init__.py
  torchvision/transforms/v2/__init__.py
Labels: cla signed

#7275 convert all bounding boxes to XYXY in dataset wrapper
  torchvision/datapoints/_dataset_wrapper.py
Labels: module: datasets, module: transforms, cla signed, prototype

#7277 Remove old TODO about using `_log_api_usage_once()`
  torchvision/transforms/v2/functional/__init__.py
Labels: module: transforms, cla signed, code quality

#7276 Add more tests for bounding boxes
  test/test_prototype_transforms.py
  test/test_prototype_transforms_functional.py
Labels: module: transforms, module: tests, cla signed, prototype

#7279 Added wrap_dataset_for_transforms_v2 into datasets and handled beta w…
  .github/workflows/test-linux-cpu.yml
  test/check_v2_dataset_warnings.py
  test/datasets_utils.py
  test/test_datasets.py
  test/test_prototype_datapoints.py
  torchvision/datapoints/__init__.py
  torchvision/datasets/__init__.py
Labels: cla signed

#7278 Split tests for transforms v2 and prototype
  .circleci/unittest/linux/scripts/run_test.sh
  test/builtin_dataset_mocks.py
  test/common_utils.py
  test/datasets_utils.py
  test/prototype_common_utils.py
  test/test_datapoints.py
  test/test_datasets.py
  test/test_prototype_datapoints.py
  test/test_prototype_transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_utils.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
Labels: module: datasets, module: transforms, module: tests, cla signed, prototype

#7280 Remove check_v2_dataset_warnings.py which is failing
  .github/workflows/test-linux-cpu.yml
  test/check_v2_dataset_warnings.py
Labels: cla signed

#7286 Channel=test for build matrix generation
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-conda-macos.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/build-wheels-macos.yml
Labels: cla signed

#7284 [Release 2.0] Release only changes
  .circleci/config.yml
  .circleci/config.yml.in
  packaging/pkg_helpers.bash
Labels: cla signed

#7288 Add warnings checks for v2 namespaces
  test/common_utils.py
  test/conftest.py
  test/test_transforms.py
  test/test_transforms_v2.py
Labels: cla signed

#7295 add ffmpeg to Linux CPU and GPU unittest workflows
  .github/workflows/test-linux-cpu.yml
  .github/workflows/test-linux-gpu.yml
Labels: module: video, module: ci, cla signed

#7291 Update transforms docs sub-structure
  docs/source/transforms.rst
Labels: cla signed

#7297 Added docs for v2 transforms (part 1)
  docs/source/conf.py
  docs/source/transforms.rst
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_container.py
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_type_conversion.py
Labels: cla signed

#7298 [Cherry-pick] Add warnings checks for v2 namespaces
  test/common_utils.py
  test/conftest.py
  test/test_transforms.py
  test/test_transforms_v2.py
Labels: cla signed

#7267 reduce GHA log output
  .github/workflows/test-linux-cpu.yml
  .github/workflows/test-linux-gpu.yml
Labels: module: ci, cla signed

#7301 align transforms v2 signatures with v1
  test/test_transforms_v2_consistency.py
  torchvision/transforms/v2/_container.py
  torchvision/transforms/v2/_geometry.py
Labels: module: transforms, module: tests, cla signed, prototype

#7304 Extend default heuristic of SanitizeBoundingBoxes to support tuples
  test/test_transforms_v2.py
  torchvision/transforms/v2/_misc.py
Labels: cla signed

#7302 add end-to-end example gallery for transforms v2
  docs/requirements.txt
  gallery/assets/coco/images/000000000001.jpg
  gallery/assets/coco/images/000000000002.jpg
  gallery/assets/coco/instances.json
  gallery/plot_transforms_v2_e2e.py
Labels: module: transforms, module: documentation, cla signed, prototype

#7310 Add v2 docs for color transforms
  docs/source/transforms.rst
  torchvision/transforms/v2/_color.py
Labels: cla signed

#7303 Updated geometric transforms v2 docstring
  docs/source/transforms.rst
  torchvision/transforms/v2/_geometry.py
Labels: cla signed

#7318 Cleanup for e2e gallery example for transforms v2
  docs/source/conf.py
  gallery/plot_transforms_v2_e2e.py
Labels: module: transforms, module: documentation, cla signed

#7316 Singular Sanitize BoundingBox
  gallery/plot_transforms_v2_e2e.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_misc.py
Labels: cla signed

#7314 Misc docs
  docs/source/transforms.rst
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_misc.py
Labels: cla signed

#7317 Minor updates in autoaugment, augment docstring v2
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
Labels: cla signed

#7315 Fixed broken test_random_choice
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  torchvision/transforms/v2/_container.py
Labels: cla signed

#7320 Updated _meta.py docstrings
  docs/source/transforms.rst
  torchvision/transforms/v2/_meta.py
Labels: cla signed

#7322 remove strEnum from BoundingBoxFormat
  test/test_datapoints.py
  torchvision/datapoints/_bounding_box.py
Labels: cla signed

#7324 Updated _type_conversion.py docs
  docs/source/transforms.rst
  torchvision/transforms/v2/_type_conversion.py
Labels: cla signed

#7312 add docs for datapoints
  docs/source/datapoints.rst
  docs/source/index.rst
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
Labels: module: documentation, cla signed, module: datapoints

#7326 Various doc enhancements
  docs/source/conf.py
  docs/source/datapoints.rst
  docs/source/index.rst
  docs/source/transforms.rst
  torchvision/transforms/transforms.py
  torchvision/transforms/v2/_container.py
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_type_conversion.py
Labels: cla signed

#7327 fix BoundingBox.wrap_like
  torchvision/datapoints/_bounding_box.py
Labels: cla signed, module: datapoints

#7328 Add docs for functionals v2
  docs/source/transforms.rst
Labels: cla signed

#7321 add gallery example for datapoints
  gallery/plot_datapoints.py
Labels: module: documentation, cla signed, module: datapoints

#7329 Change betastatus doc warning and v2 import warning
  docs/source/beta_status.py
  docs/source/transforms.rst
  torchvision/__init__.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_container.py
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/_type_conversion.py
Labels: cla signed

#7331 add gallery for transforms v2
  gallery/plot_transforms_v2.py
Labels: module: transforms, module: documentation, cla signed

#7330 Fixed uncaught warnings in tests v2
  test/test_transforms_v2.py
Labels: cla signed

#7334 [Cherry-pick] Bunch of doc and fixes cherry-picks for release/0.15
  .github/workflows/test-linux-cpu.yml
  .github/workflows/test-linux-gpu.yml
  docs/requirements.txt
  docs/source/beta_status.py
  docs/source/conf.py
  docs/source/datapoints.rst
  docs/source/index.rst
  docs/source/transforms.rst
  gallery/assets/coco/images/000000000001.jpg
  gallery/assets/coco/images/000000000002.jpg
  gallery/assets/coco/instances.json
  gallery/plot_datapoints.py
  gallery/plot_transforms_v2.py
  gallery/plot_transforms_v2_e2e.py
  test/test_datapoints.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  torchvision/__init__.py
  torchvision/datapoints/_bounding_box.py
  torchvision/datapoints/_image.py
  torchvision/datapoints/_mask.py
  torchvision/datapoints/_video.py
  torchvision/transforms/transforms.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_container.py
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/_type_conversion.py
Labels: cla signed

#7333 add docstring for dataset wrapper
  docs/source/datasets.rst
  torchvision/datapoints/_dataset_wrapper.py
Labels: module: datasets, module: transforms, module: documentation, cla signed

#7344 [Cherry-pick for 0.15] add docstring for dataset wrapper (#7333)
  docs/source/datasets.rst
  torchvision/datapoints/_dataset_wrapper.py
Labels: cla signed

#7343 [Cherry-pick for 0.15] Bump SoLoader version to 0.10.5
  android/build.gradle
Labels: cla signed

#7342 [FBcode->GH] Bump SoLoader and Allow building torchvision operators statically
  android/build.gradle
  torchvision/csrc/macros.h
Labels: cla signed

#7332 Fix vision unit tests infra failures
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/linux/scripts/setup_env.sh
  .circleci/unittest/windows/scripts/setup_env.sh
Labels: cla signed

#7347 skip flaky adjust_contrast kernel tests
  test/transforms_v2_kernel_infos.py
Labels: module: transforms, module: tests, cla signed

#7351 skip tests that use assert_run_python_script on windows
  test/test_transforms.py
  test/test_transforms_v2.py
Labels: module: transforms, module: tests, cla signed

#7350 Skip test_schema_meta_validation[maskrcnn_resnet50_fpn_v2]
  test/test_extended_models.py
Labels: cla signed

#7348 skip flaky adjust_saturation kernel tests
  test/transforms_v2_kernel_infos.py
Labels: module: transforms, module: tests, cla signed

#7352 [Cherry-picks for 0.15] Various unit test fixes
  test/test_extended_models.py
  test/test_transforms.py
  test/test_transforms_v2.py
  test/transforms_v2_kernel_infos.py
Labels: cla signed

#7353 [Cherry-pick for 0.15]
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/linux/scripts/setup_env.sh
  .circleci/unittest/windows/scripts/setup_env.sh
Labels: cla signed

#7357 Fix cpu instals in circleci
  .circleci/unittest/linux/scripts/install.sh
Labels: cla signed

#7358 [Cherry-pick for 0.15] Ci fixes
  .circleci/unittest/linux/scripts/install.sh
Labels: cla signed

#7346 fix assert_run_python_script on Windows
  test/common_utils.py
  test/test_transforms.py
  test/test_transforms_v2.py
Labels: cla signed

#7363 [Release only fixes] Fix unit test to run on test channel rather then nightly
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/test-linux-cpu.yml
  .github/workflows/test-linux-gpu.yml
  .github/workflows/test-m1.yml
Labels: cla signed
