Repository pytorch/vision, pull requests merged in 2023-11, with the labels that each got.

#8100 temporarily add packaging as CI requirement
  .github/scripts/setup-env.sh
Labels: module: ci, cla signed, core issue

#8102 Remove limitation for torch.compile and python 3.11
  test/smoke_test.py
Labels: cla signed

#8097 refactor to_pil_image and align array with tensor inputs
  test/test_transforms.py
  torchvision/transforms/functional.py
Labels: bug, module: transforms, cla signed

#8113 Fixed mypy issue in VideoClips
  torchvision/datasets/video_utils.py
Labels: cla signed

#8110 Added support for tv tensors in torch compile for func ops
  torchvision/tv_tensors/__init__.py
Labels: cla signed

#8111 Remove BETA status for v2 transforms
  docs/source/beta_status.py
  docs/source/transforms.rst
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_container.py
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_temporal.py
  torchvision/transforms/v2/_type_conversion.py
  torchvision/transforms/v2/functional/_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_deprecated.py
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
  torchvision/transforms/v2/functional/_temporal.py
  torchvision/transforms/v2/functional/_type_conversion.py
  torchvision/transforms/v2/functional/_utils.py
  torchvision/tv_tensors/__init__.py
  torchvision/tv_tensors/_bounding_boxes.py
  torchvision/tv_tensors/_dataset_wrapper.py
  torchvision/tv_tensors/_image.py
  torchvision/tv_tensors/_mask.py
  torchvision/tv_tensors/_torch_function_helpers.py
  torchvision/tv_tensors/_tv_tensor.py
  torchvision/tv_tensors/_video.py
Labels: enhancement, module: transforms, cla signed

#7953 [FBcode->GH] Remove deprecated functional modules
  test/test_transforms.py
  torchvision/transforms/functional_pil.py
  torchvision/transforms/functional_tensor.py
Labels: cla signed

#8114 Add note about improvements only happening on v2 now
  docs/source/transforms.rst
Labels: enhancement, module: documentation, cla signed

#8117 Add missing bracket
  torchvision/transforms/v2/_color.py
Labels: cla signed

#8121 Fix Kinetics dataset docstring
  torchvision/datasets/kinetics.py
  torchvision/datasets/video_utils.py
Labels: enhancement, module: datasets, module: documentation, cla signed

#8125 Remove deprecated path parameter to VideoReader and made src mandatory
  test/test_videoapi.py
  torchvision/io/video_reader.py
Labels: cla signed

#8108 Reduced number of graphs for compiled resize
  torchvision/transforms/v2/functional/_geometry.py
Labels: cla signed

#8130 [release only] Bump torchvision to 0.16.2
  version.txt
Labels: cla signed

#8131 Revert "temporarily add packaging as CI requirement (#8100)"
  .github/scripts/setup-env.sh
Labels: cla signed, revert(ed)

#8134 fix mypy on `VisionDataset`
  torchvision/datasets/fakedata.py
  torchvision/datasets/vision.py
Labels: bug, module: datasets, cla signed

#8132 fix error test for F.pad_mask
  test/test_transforms_v2.py
Labels: bug, module: transforms, module: tests, cla signed

#8133 fix atol in resize_image kernel test
  test/test_transforms_v2.py
Labels: bug, module: transforms, module: tests, cla signed
