Repository pytorch/vision, pull requests merged in 2023-07, with the labels that each got.

#7715 remove center unsetting if expand=True
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, cla signed

#7716 fix PIL version check
  test/test_transforms.py
Labels: module: tests, dependency issue, cla signed

#7713 port rotate
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
Labels: module: transforms, module: tests, cla signed

#7718 Add filter parameters to `list_models()`
  test/test_extended_models.py
  torchvision/models/_api.py
Labels: enhancement, module: models, cla signed

#7717 extract make_* functions out of make_*_loader
  test/common_utils.py
  test/test_prototype_transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_kernel_infos.py
Labels: module: tests, cla signed, code quality

#7724 Add --use-v2 support to classification references
  references/classification/presets.py
  references/classification/train.py
Labels: cla signed

#7730 Fix the confusing example of `gt_pred_pairs_of_highest_quality`
  torchvision/models/detection/_utils.py
Labels: cla signed

#7755 Add status notice in README of prototype datasets
  torchvision/prototype/datasets/README.md
Labels: cla signed

#7758 improve UX for v2 Compose
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/_container.py
Labels: enhancement, module: transforms, cla signed

#7759 Add scale option to ToDtype. Remove ConvertDtype.
  docs/source/transforms.rst
  gallery/plot_transforms_v2_e2e.py
  test/common_utils.py
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_functional.py
  test/test_transforms_v2_refactored.py
  test/transforms_v2_dispatcher_infos.py
  test/transforms_v2_kernel_infos.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_meta.py
Labels: cla signed

#7742 Properly handle maskrcnn and keypoints w.r.t. V2 in detection references
  references/detection/coco_utils.py
  references/detection/train.py
Labels: cla signed

#7743 Add --backend and --use-v2 support for segmentation references
  references/detection/coco_utils.py
  references/segmentation/coco_utils.py
  references/segmentation/presets.py
  references/segmentation/train.py
  references/segmentation/transforms.py
  references/segmentation/utils.py
  references/segmentation/v2_extras.py
Labels: cla signed

#7768 fix make_image
  test/common_utils.py
Labels: bug, module: tests, cla signed

#7731 promote Mixup and Cutmix from prototype to transforms v2
  docs/source/transforms.rst
  gallery/plot_cutmix_mixup.py
  references/classification/train.py
  references/classification/transforms.py
  test/test_transforms_v2.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_utils.py
Labels: module: transforms, cla signed

#7770 Put all dtype conversion stuff into the _misc namespaces
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/transforms/v2/functional/_misc.py
Labels: cla signed, code quality, other

#7771 Update deprecation warning to not mention ConvertImageDtype
  torchvision/transforms/v2/_deprecated.py
  torchvision/transforms/v2/functional/_deprecated.py
Labels: cla signed

#7777 Fix RandomZoomOut doc string
  torchvision/transforms/v2/_geometry.py
Labels: cla signed

#7781 Add new entry to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: cla signed

#7772 Add gallery example for MixUp and CutMix
  docs/source/transforms.rst
  gallery/plot_cutmix_mixup.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/_augment.py
Labels: enhancement, module: documentation, cla signed

#7239 add support for instance checks on dataset wrappers
  references/detection/coco_utils.py
  references/detection/group_by_aspect_ratio.py
  test/datasets_utils.py
  torchvision/datapoints/_dataset_wrapper.py
Labels: module: datasets, module: transforms, cla signed, prototype
