Repository pytorch/vision, pull requests merged in 2023-01, with the labels that each got.

#7042 Add MovingMNIST dataset
  docs/source/datasets.rst
  test/test_datasets.py
  test/test_datasets_download.py
  torchvision/datasets/__init__.py
  torchvision/datasets/moving_mnist.py
Labels: cla signed

#7058 Update to cuda 118
  .circleci/config.yml
  .circleci/regenerate.py
  packaging/pkg_helpers.bash
  packaging/windows/internal/cuda_install.bat
Labels: cla signed

#7062 [FBcode->GH] [reland] rename DisableTorchFunction to DisableTorchFunctionSubclass (#88218)
  torchvision/prototype/datapoints/_datapoint.py
Labels: cla signed

#7059 Remove deprecated np.int usages
  test/test_transforms.py
Labels: module: tests, dependency issue, cla signed

#7069 Remove torch.jit.fuser("fuser2") in test
  test/test_ops.py
Labels: cla signed

#7060 pin python version for cmake workflows
  .circleci/config.yml
  .circleci/config.yml.in
Labels: module: ci, cla signed

#7074 Cleanup weight docs
  docs/source/conf.py
  test/common_extended_utils.py
  test/test_extended_models.py
  torchvision/models/alexnet.py
  torchvision/models/convnext.py
  torchvision/models/densenet.py
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
  torchvision/models/detection/ssd.py
  torchvision/models/detection/ssdlite.py
  torchvision/models/efficientnet.py
  torchvision/models/googlenet.py
  torchvision/models/inception.py
  torchvision/models/maxvit.py
  torchvision/models/mnasnet.py
  torchvision/models/mobilenetv2.py
  torchvision/models/mobilenetv3.py
  torchvision/models/optical_flow/raft.py
  torchvision/models/quantization/googlenet.py
  torchvision/models/quantization/inception.py
  torchvision/models/quantization/mobilenetv2.py
  torchvision/models/quantization/mobilenetv3.py
  torchvision/models/quantization/resnet.py
  torchvision/models/quantization/shufflenetv2.py
  torchvision/models/regnet.py
  torchvision/models/resnet.py
  torchvision/models/segmentation/deeplabv3.py
  torchvision/models/segmentation/fcn.py
  torchvision/models/segmentation/lraspp.py
  torchvision/models/shufflenetv2.py
  torchvision/models/squeezenet.py
  torchvision/models/swin_transformer.py
  torchvision/models/vgg.py
  torchvision/models/video/mvit.py
  torchvision/models/video/resnet.py
  torchvision/models/video/s3d.py
  torchvision/models/video/swin_transformer.py
  torchvision/models/vision_transformer.py
Labels: cla signed

#7077 Fix license file deprecation warning
  setup.cfg
Labels: cla signed

#7078 Adds max_vit and swin_v2 models to torch.hub
  hubconf.py
Labels: cla signed

#7081 fix MNIST byte flipping
  test/test_datasets_utils.py
  torchvision/datasets/mnist.py
  torchvision/datasets/utils.py
Labels: bug, module: datasets, cla signed

#7083 Add video models to hub
  hubconf.py
Labels: cla signed

#7088 reinstate Places365 download tests
  test/test_datasets_download.py
Labels: module: datasets, module: ci, cla signed

#7084 simplify dispatcher if-elif
  mypy.ini
  torchvision/prototype/transforms/_type_conversion.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_augment.py
  torchvision/prototype/transforms/functional/_color.py
  torchvision/prototype/transforms/functional/_deprecated.py
  torchvision/prototype/transforms/functional/_geometry.py
  torchvision/prototype/transforms/functional/_meta.py
  torchvision/prototype/transforms/functional/_misc.py
  torchvision/prototype/transforms/functional/_temporal.py
  torchvision/prototype/transforms/functional/_utils.py
  torchvision/prototype/transforms/utils.py
Labels: module: transforms, cla signed, code quality, prototype

#7087 Add missing type hints to ColorJitter constructor
  torchvision/transforms/transforms.py
Labels: cla signed

#7107 properly support deepcopying and serialization of model weights
  test/test_extended_models.py
  torchvision/models/_api.py
Labels: cla signed

#7113 Let Normalize() and RandomPhotometricDistort return datapoints instead of tensors
  test/prototype_transforms_dispatcher_infos.py
  test/test_prototype_transforms_functional.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_video.py
  torchvision/prototype/transforms/_color.py
  torchvision/prototype/transforms/functional/_misc.py
Labels: cla signed

#7117 update naming feature -> datapoint in prototype test suite
  test/prototype_transforms_dispatcher_infos.py
  test/test_prototype_datapoints.py
  test/test_prototype_transforms.py
  test/test_prototype_transforms_consistency.py
  test/test_prototype_transforms_functional.py
Labels: module: tests, cla signed, code quality

#7118 add tests for the output types of prototype functional dispatchers
  test/prototype_transforms_dispatcher_infos.py
  test/test_prototype_transforms_functional.py
Labels: module: transforms, module: tests, cla signed, prototype

#7119 add reference test for normalize_image_tensor
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms_functional.py
Labels: module: transforms, module: tests, cla signed, prototype

#7120 Remove `color_space` metadata and `ConvertColorSpace()` transform
  test/prototype_common_utils.py
  test/prototype_transforms_kernel_infos.py
  test/test_prototype_transforms.py
  test/test_prototype_transforms_consistency.py
  test/test_prototype_transforms_functional.py
  test/test_prototype_transforms_utils.py
  torchvision/prototype/datapoints/__init__.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_video.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_deprecated.py
  torchvision/prototype/transforms/_meta.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_deprecated.py
  torchvision/prototype/transforms/functional/_meta.py
  torchvision/transforms/functional.py
Labels: cla signed, prototype

#7122 Undeprecate ToGrayScale transforms and functionals
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/datapoints/_datapoint.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_video.py
  torchvision/prototype/transforms/__init__.py
  torchvision/prototype/transforms/_color.py
  torchvision/prototype/transforms/_deprecated.py
  torchvision/prototype/transforms/functional/__init__.py
  torchvision/prototype/transforms/functional/_color.py
  torchvision/prototype/transforms/functional/_deprecated.py
  torchvision/prototype/transforms/functional/_meta.py
Labels: cla signed, prototype

#7133 perform out of bounds check for single values and two tuples in ColorJitter
  test/test_prototype_transforms_consistency.py
  test/test_transforms.py
  torchvision/prototype/transforms/_color.py
  torchvision/transforms/transforms.py
Labels: enhancement, module: transforms, cla signed

#7136 DataPoint.to_grayscale() -> DataPoint.rgb_to_grayscale
  torchvision/prototype/datapoints/_datapoint.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_video.py
  torchvision/prototype/transforms/functional/_color.py
Labels: cla signed, code quality, prototype

#7139 fix Resize for JIT single value sequences
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/transforms/_geometry.py
Labels: module: transforms, cla signed, prototype

#7138 fix requires_grad passthrough
  test/test_prototype_datapoints.py
  torchvision/prototype/datapoints/_bounding_box.py
  torchvision/prototype/datapoints/_datapoint.py
  torchvision/prototype/datapoints/_image.py
  torchvision/prototype/datapoints/_label.py
  torchvision/prototype/datapoints/_mask.py
  torchvision/prototype/datapoints/_video.py
Labels: cla signed, prototype, module: datapoints

#7141 add sequence fill support for ElasticTransform
  test/test_transforms_tensor.py
  torchvision/transforms/functional.py
  torchvision/transforms/transforms.py
Labels: bug, enhancement, module: transforms, cla signed

#7110 drop support for Python 3.7
  .circleci/config.yml
  .circleci/config.yml.in
  .circleci/regenerate.py
  .circleci/unittest/ios/scripts/binary_ios_build.sh
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/test-linux-cpu.yml
  .github/workflows/tests-schedule.yml
  README.rst
  packaging/pkg_helpers.bash
  packaging/torchvision/conda_build_config.yaml
  packaging/vs2017/conda_build_config.yaml
  packaging/vs2019/conda_build_config.yaml
  pyproject.toml
  setup.py
  torchvision/prototype/datasets/utils/_resource.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_utils.py
  torchvision/transforms/functional_pil.py
Labels: module: ci, cla signed

#7109 Add torchvision maintainers guide
  maintainer_guide.md
Labels: cla signed

#7116 switch to C++17 following the core library
  CMakeLists.txt
Labels: cla signed

#7150 improve warning message for missing image extension
  torchvision/io/image.py
Labels: enhancement, module: io, cla signed

#7080 raise kernel launch errors instead of just print
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
Labels: cla signed

#7135 make transforms v2 JIT scriptable
  test/test_prototype_transforms_consistency.py
  torchvision/prototype/transforms/_augment.py
  torchvision/prototype/transforms/_auto_augment.py
  torchvision/prototype/transforms/_color.py
  torchvision/prototype/transforms/_geometry.py
  torchvision/prototype/transforms/_meta.py
  torchvision/prototype/transforms/_misc.py
  torchvision/prototype/transforms/_transform.py
Labels: module: transforms, cla signed, prototype
