Repository pytorch/vision, pull requests merged in 2023-10, with the labels that each got.

#8004 cleanup affine grid image kernels
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, cla signed, code quality

#8003 port tests for type conversion transforms
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_refactored.py
  torchvision/transforms/v2/functional/_type_conversion.py
Labels: module: transforms, module: tests, cla signed

#8007 Fixed markup in functional.py
  torchvision/transforms/functional.py
Labels: cla signed

#8011 port tests for transforms.Lambda
  test/test_transforms_v2.py
  test/test_transforms_v2_consistency.py
  test/test_transforms_v2_refactored.py
Labels: module: transforms, module: tests, cla signed

#7994 [Cherry pick] fix weight docs (#7993)
  docs/source/conf.py
Labels: cla signed

#8022 port prototype tests to new utilities
  test/prototype_common_utils.py
  test/test_prototype_transforms.py
  test/transforms_v2_legacy_utils.py
Labels: module: transforms, module: tests, cla signed, prototype

#8023 Remove reference consistency tests
  test/test_transforms_v2_consistency.py
  test/transforms_v2_legacy_utils.py
Labels: module: transforms, module: tests, cla signed

#8032 Put pytestmark at top of file
  test/test_transforms_v2.py
Labels: module: transforms, module: tests

#8033 Temporarily disable 'error on warnings' pytest filter
  test/test_transforms_v2.py
Labels: module: transforms, module: tests

#8036 Fix hashes of efficientnet weights
  torchvision/models/efficientnet.py
Labels: bug, module: models, cla signed

#8019 fix: atrous_rates for deeplabv3_mobilenet_v3_large (fixes #7956)
  torchvision/models/segmentation/deeplabv3.py
Labels: cla signed

#8040 [Cherry-pick] Fix hashes of efficientnet weights (#8036)
  torchvision/models/efficientnet.py
Labels: bug, module: models, cla signed

#8043 [Release-Only] Bump minor version to 0.16.1
  version.txt
Labels: cla signed

#8045 [Release only] Pin test-infra repo for 2.1 release
  .github/workflows/build-cmake.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#8046 Specify test-infra branch to main
  .github/workflows/build-cmake.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#8052 update draw_boxes reference image
  test/assets/fakedata/draw_boxes_util.png
  test/test_utils.py
Labels: dependency issue, cla signed

#7961 Add opcheck testing for nms
  .github/scripts/unittest.sh
  test/conftest.py
  test/optests_failures_dict.json
  test/test_models.py
  test/test_ops.py
Labels: cla signed

#8057 Add opchecks for RoiAlign
  test/optests_failures_dict.json
  test/test_ops.py
Labels: enhancement, module: ops, module: tests, cla signed

#8070 [ROCm] remove HCC references
  torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu
Labels: module: rocm, cla signed, ciflow/rocm

#8073 Fix quantized references
  references/classification/README.md
  references/classification/train_quantization.py
Labels: bug, module: reference scripts, cla signed

#8067 Fix v2 transforms in spawn mp context
  test/datasets_utils.py
  test/test_datasets.py
  torchvision/tv_tensors/_dataset_wrapper.py
Labels: bug, module: transforms, cla signed

#8049 Add autocast for nms, roi_align on CPU
  setup.py
  test/test_ops.py
  torchvision/csrc/ops/autocast/nms_kernel.cpp
  torchvision/csrc/ops/autocast/roi_align_kernel.cpp
Labels: cla signed

#8058 PSRoiAlign: SymInt support + meta-implem
  torchvision/_meta_registrations.py
  torchvision/csrc/ops/autograd/ps_roi_align_kernel.cpp
  torchvision/csrc/ops/ps_roi_align.cpp
  torchvision/csrc/ops/ps_roi_align.h
Labels: enhancement, module: ops, module: tests, cla signed

#8076 [Cherry-pick] update draw_boxes reference image #8052
  test/assets/fakedata/draw_boxes_util.png
  test/test_utils.py
Labels: module: tests, dependency issue, cla signed

#8074 [Cherry-pick] Fix v2 transforms in spawn mp context (#8067)
  test/datasets_utils.py
  test/test_datasets.py
  torchvision/tv_tensors/_dataset_wrapper.py
Labels: bug, module: datasets, module: transforms, cla signed

#8061 RoIPool: SymInt support + meta-implem
  torchvision/_meta_registrations.py
  torchvision/csrc/ops/autograd/roi_pool_kernel.cpp
  torchvision/csrc/ops/roi_pool.cpp
  torchvision/csrc/ops/roi_pool.h
Labels: cla signed

#8062 PSRoiPool: SymInt support + meta-implem
  torchvision/_meta_registrations.py
  torchvision/csrc/ops/autograd/ps_roi_pool_kernel.cpp
  torchvision/csrc/ops/ps_roi_pool.cpp
  torchvision/csrc/ops/ps_roi_pool.h
Labels: cla signed

#8063 DeformConv2d: SymInt support + meta-implem + opchecks
  test/test_ops.py
  torchvision/_meta_registrations.py
  torchvision/csrc/ops/autograd/deform_conv2d_kernel.cpp
  torchvision/csrc/ops/deform_conv2d.cpp
  torchvision/csrc/ops/deform_conv2d.h
Labels: cla signed

#8077 Remove unnecessary dependency from macOS/Conda binaries
  packaging/torchvision/meta.yaml
Labels: topic: binaries, cla signed, code quality
