Repository pytorch/vision, pull requests merged in 2024-02, with the labels that each got.

#8253 Migrate the macOS runners label from macos-m1-12 to macos-m1-stable
  .github/workflows/build-cmake.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/tests.yml
Labels: cla signed

#8256 Allow 2D numpy arrays as inputs for `to_image`
  test/test_transforms_v2.py
  torchvision/transforms/v2/functional/_type_conversion.py
Labels: cla signed

#8225 Add visibility parameter to draw_keypoints()
  gallery/others/plot_visualization_utils.py
  test/assets/fakedata/draw_keypoints_visibility.png
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#8249 Make _get_perspective_coeffs more numerically stable
  torchvision/transforms/functional.py
Labels: cla signed

#8237 add gdown as optional requirement for dataset GDrive download
  .github/workflows/tests-schedule.yml
  mypy.ini
  setup.py
  torchvision/datasets/caltech.py
  torchvision/datasets/celeba.py
  torchvision/datasets/pcam.py
  torchvision/datasets/utils.py
  torchvision/datasets/widerface.py
Labels: cla signed

#8251 Add parameter type to `to_tensor`
  torchvision/transforms/functional.py
Labels: cla signed

#8264 [Cherry-pick for 0.17.1] add gdown as optional requirement for dataset GDrive download
  .github/workflows/tests-schedule.yml
  mypy.ini
  setup.py
  torchvision/datasets/caltech.py
  torchvision/datasets/celeba.py
  torchvision/datasets/pcam.py
  torchvision/datasets/utils.py
  torchvision/datasets/widerface.py
Labels: cla signed

#8265 Fix convert_bounding_box_format when passing strings
  test/test_transforms_v2.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/functional/_meta.py
Labels: cla signed

#8267 [Cherry-pick for 0.17.1] Fix convert_bounding_box_format when passing strings
  test/test_transforms_v2.py
  torchvision/transforms/v2/_meta.py
  torchvision/transforms/v2/functional/_meta.py
Labels: cla signed

#8271 Bump version for release 0.17.1
  version.txt
Labels: cla signed

#8272 fix pr-labels workflow
  .github/workflows/pr-labels.yml
Labels: module: ci, cla signed

#8273 cleanup download utils
  torchvision/datasets/utils.py
Labels: module: datasets, cla signed, code quality

#8282 Remove macos x86 nightly builds
  .github/workflows/build-conda-macos.yml
  .github/workflows/build-wheels-macos.yml
Labels: cla signed
