Repository pytorch/vision, pull requests merged in 2024-03, with the labels that each got.

#8287 Fix CutMix and MixUp arguments in transforms.py
  references/classification/train.py
  references/classification/transforms.py
Labels: cla signed

#8291 Pin 'mpmath<1.4' in CI
  .github/scripts/setup-env.sh
Labels: cla signed

#8276 draw_keypoints() float support
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#8279 Added support for EXIF orientation transform in read_image for JPEG
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/cpu/decode_image.h
  torchvision/csrc/io/image/cpu/decode_jpeg.cpp
  torchvision/csrc/io/image/cpu/decode_jpeg.h
  torchvision/csrc/io/image/cpu/exif.h
  torchvision/csrc/io/image/image.cpp
  torchvision/io/image.py
Labels: cla signed

#8302 Improved jpeg decoding code with exif
  torchvision/csrc/io/image/cpu/decode_jpeg.cpp
  torchvision/csrc/io/image/cpu/exif.h
Labels: cla signed

#8280 Remove deprecated distutils usage for Python 3.12
  test/test_datasets_download.py
Labels: cla signed

#8309 Disable download for StanfordCars dataset
  test/test_datasets_download.py
  torchvision/datasets/stanford_cars.py
Labels: bug, module: datasets, cla signed

#8246 Mentioning the padding policy in transforms.GaussianBlur docs
  torchvision/transforms/functional.py
  torchvision/transforms/v2/_misc.py
Labels: cla signed

#8303 Added support for EXIF orientation transform in read_image for PNG
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/cpu/decode_jpeg.cpp
  torchvision/csrc/io/image/cpu/decode_png.cpp
  torchvision/csrc/io/image/cpu/decode_png.h
  torchvision/csrc/io/image/cpu/exif.h
  torchvision/csrc/io/image/image.cpp
  torchvision/io/image.py
Labels: enhancement, module: io, cla signed

#8300 Add minor comment about ToTensor
  torchvision/transforms/v2/_deprecated.py
Labels: enhancement, module: transforms, cla signed

#8119 Help make test dependent on randint compatible with python 3.12
  test/test_transforms.py
  test/test_transforms_video.py
Labels: cla signed

#8311 Add allow_empty parameter to ImageFolder and related utils
  test/test_datasets.py
  torchvision/datasets/folder.py
Labels: enhancement, module: datasets, cla signed

#8312 Fix default momentum value of BatchNorm2d in MaxViT from 0.99 to 0.01
  torchvision/models/maxvit.py
Labels: bug, module: models, cla signed

#8227 Added Type Check for cocodetection dataset
  test/test_datasets.py
  torchvision/datasets/coco.py
Labels: cla signed

#8299 Add 3.12 to unittest CI jobs
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests.yml
  test/test_transforms_v2.py
Labels: cla signed

#8313 Add torchscript test for io image stuff
  test/test_image.py
Labels: module: tests, module: io, cla signed

#8318 fix ssdlite model class link in doc
  docs/source/models/ssdlite.rst
Labels: cla signed

#8308 Add `sanitize_bounding_boxes` kernel/functional
  docs/source/transforms.rst
  test/test_transforms_v2.py
  torchvision/prototype/transforms/_augment.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_misc.py
Labels: enhancement, module: transforms, cla signed

#8319 Allow SanitizeBoundingBoxes to sanitize more labels
  test/test_transforms_v2.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/_utils.py
Labels: enhancement, module: transforms, cla signed

#8247 Add a GrayscaleToRgb transform that can expand channels to 3
  docs/source/transforms.rst
  test/test_transforms_v2.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_color.py
Labels: cla signed

#8314 Add pathlib.Path support for image IO utils
  test/test_image.py
  torchvision/io/image.py
Labels: enhancement, module: io, cla signed

#8324 Put back StanfordCars.download (the function, NOT the feature)
  torchvision/datasets/stanford_cars.py
Labels: cla signed

#8310 Fix test_download_datasets... hopefully
  .github/workflows/tests-schedule.yml
Labels: cla signed

#8321 Document that datasets support pathlib.Path
  torchvision/datasets/_optical_flow.py
  torchvision/datasets/_stereo_matching.py
  torchvision/datasets/caltech.py
  torchvision/datasets/celeba.py
  torchvision/datasets/cifar.py
  torchvision/datasets/cityscapes.py
  torchvision/datasets/clevr.py
  torchvision/datasets/coco.py
  torchvision/datasets/country211.py
  torchvision/datasets/dtd.py
  torchvision/datasets/eurosat.py
  torchvision/datasets/fer2013.py
  torchvision/datasets/fgvc_aircraft.py
  torchvision/datasets/flickr.py
  torchvision/datasets/flowers102.py
  torchvision/datasets/folder.py
  torchvision/datasets/food101.py
  torchvision/datasets/gtsrb.py
  torchvision/datasets/hmdb51.py
  torchvision/datasets/imagenet.py
  torchvision/datasets/imagenette.py
  torchvision/datasets/inaturalist.py
  torchvision/datasets/kinetics.py
  torchvision/datasets/kitti.py
  torchvision/datasets/lfw.py
  torchvision/datasets/lsun.py
  torchvision/datasets/mnist.py
  torchvision/datasets/moving_mnist.py
  torchvision/datasets/omniglot.py
  torchvision/datasets/oxford_iiit_pet.py
  torchvision/datasets/pcam.py
  torchvision/datasets/phototour.py
  torchvision/datasets/places365.py
  torchvision/datasets/rendered_sst2.py
  torchvision/datasets/sbd.py
  torchvision/datasets/sbu.py
  torchvision/datasets/semeion.py
  torchvision/datasets/stanford_cars.py
  torchvision/datasets/stl10.py
  torchvision/datasets/sun397.py
  torchvision/datasets/svhn.py
  torchvision/datasets/ucf101.py
  torchvision/datasets/usps.py
  torchvision/datasets/vision.py
  torchvision/datasets/voc.py
  torchvision/datasets/widerface.py
Labels: module: datasets, module: documentation, cla signed

#8316 Add JPEG augmentation
  docs/source/transforms.rst
  gallery/transforms/plot_transforms_illustrations.py
  test/test_transforms_v2.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_augment.py
Labels: module: transforms, new feature, cla signed

#8329 Remove private PIL kernels from __init__.py
  test/test_transforms_v2.py
  torchvision/transforms/v2/functional/__init__.py
Labels: module: transforms, cla signed, code quality

#8330 Use @release/2.3 instead of @main for CI jobs
  .github/workflows/build-cmake.yml
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-conda-windows.yml
  .github/workflows/build-wheels-aarch64-linux.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/build-wheels-windows.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests.yml
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#8332 yet another ssdlite link fix
  torchvision/models/detection/ssdlite.py
Labels: cla signed

#8337 Update version.txt for release 0.19
  version.txt
Labels: cla signed

#8335 [FBcode->GH] [codemod] Use `nullptr` intead of NULL
  torchvision/csrc/io/decoder/gpu/decoder.cpp
  torchvision/csrc/io/image/cpu/encode_png.cpp
  torchvision/csrc/io/image/cpu/read_write_file.cpp
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/video_reader/video_reader.cpp
  torchvision/csrc/vision.cpp
Labels: module: io, cla signed, code quality

#8346 Migrate the macOS runners label from macos-m1-12 to macos-m1-stable
  .github/workflows/build-cmake.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/tests.yml
Labels: cla signed

#8347 [Release only] Use release/2.3 instead of main for test-infra-ref
  .github/workflows/build-cmake.yml
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-conda-windows.yml
  .github/workflows/build-wheels-aarch64-linux.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/build-wheels-windows.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#8342 Fix compilation error when there is no libjpeg
  torchvision/csrc/io/image/cpu/exif.h
Labels: module: io, cla signed

#8341 Just a typo
  gallery/transforms/plot_transforms_e2e.py
Labels: cla signed

#8352 [Cherry-pick for 0.18] yet another ssdlite link fix #8332
  torchvision/models/detection/ssdlite.py
Labels: cla signed

#8355 [Cherry-pick for 0.18] Just a typo (#8341)
  gallery/transforms/plot_transforms_e2e.py
Labels: cla signed

#8345 [FBcode -> GH] Fix fetch_png_exif_orientation
  torchvision/csrc/io/image/cpu/exif.h
Labels: module: io, cla signed, code quality

#8356 [Cherry-pick for 0.18] [FBcode -> GH] Fix fetch_png_exif_orientation #8345
  torchvision/csrc/io/image/cpu/exif.h
Labels: cla signed
