Repository pytorch/vision, pull requests merged in 2024-07, with the labels that each got.

#8506 Update plot_repurposing_annotations.py
  gallery/others/plot_repurposing_annotations.py
Labels: cla signed

#8507 Update plot_transforms_getting_started.py: fix typos
  gallery/transforms/plot_transforms_getting_started.py
Labels: cla signed

#8512 Typo fix: collab -> Colab
  .github/workflows/docs.yml
  docs/source/conf.py
  gallery/others/plot_optical_flow.py
  gallery/others/plot_scripted_tensor_transforms.py
  gallery/others/plot_video_api.py
  gallery/others/plot_visualization_utils.py
  gallery/transforms/plot_custom_transforms.py
  gallery/transforms/plot_custom_tv_tensors.py
  gallery/transforms/plot_cutmix_mixup.py
  gallery/transforms/plot_transforms_e2e.py
  gallery/transforms/plot_transforms_illustrations.py
  gallery/transforms/plot_tv_tensors.py
Labels: enhancement, module: documentation

#8513 Correcting a link bracket in Classification README.md
  references/classification/README.md
Labels: cla signed

#8516 Ignore some mypy issues
  torchvision/datasets/_optical_flow.py
  torchvision/datasets/_stereo_matching.py
  torchvision/datasets/widerface.py
  torchvision/utils.py
Labels: cla signed, code quality

#8518 Ignore pickle warning for some v2 tests
  test/test_transforms_v2.py
Labels: cla signed

#8523 Remove warning filter in transforms test
  test/test_transforms_v2.py
Labels: enhancement, module: tests, cla signed

#8526 Add Path type annotation for ImageFolder
  torchvision/datasets/folder.py
Labels: cla signed

#8524 Add support for decoding 16bits png
  test/test_image.py
  test/test_transforms_v2.py
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/cpu/decode_png.cpp
  torchvision/csrc/io/image/cpu/decode_png.h
  torchvision/csrc/io/image/image.cpp
  torchvision/datasets/_optical_flow.py
  torchvision/io/image.py
  torchvision/transforms/_functional_tensor.py
  torchvision/transforms/v2/functional/_misc.py
Labels: cla signed

#8530 Pin numpy dep to `numpy<2` for windows
  setup.py
Labels: cla signed

#8528 Revamp setup.py and C++ extension build
  setup.py
Labels: cla signed

#8532 Remove useless stuff from pre_build_script
  packaging/pre_build_script.sh
Labels: cla signed

#8535 More debugging info to setup.py
  setup.py
Labels: cla signed

#8539 Remove redundant line in example
  torchvision/models/detection/keypoint_rcnn.py
Labels: cla signed

#8545 [Release 2.4] Update compatibility matrix
  README.md
Labels: cla signed

#8537 Allow io.write_video to work with video_arrays on different devices
  test/test_io.py
  torchvision/io/video.py
Labels: cla signed

#8542 Add xpu linux wheel build into torchvision build matrix
  .github/workflows/build-wheels-linux.yml
Labels: cla signed

#8551 Update URL of SBDataset train_noval
  torchvision/datasets/sbd.py
Labels: cla signed

#8486 Support v2.functional.gaussian_blur backprop
  torchvision/transforms/v2/functional/_misc.py
Labels: cla signed

#8548 Check average_rate availability in video reader
  torchvision/io/video_reader.py
Labels: cla signed

#8553 Fix test_write_video_with_audio
  test/test_io.py
Labels: enhancement, module: tests

#8555 Fix Mypy
  torchvision/datasets/kinetics.py
  torchvision/transforms/_presets.py
Labels: cla signed

#8556 Better progress bar for file downloading
  torchvision/datasets/utils.py
Labels: cla signed

#8558 Fix test_write_video_with_audio.. again
  test/test_io.py
  torchvision/datasets/kinetics.py
  torchvision/io/video.py
Labels: cla signed

#8562 Restrict ffmpeg to 4.2+.X versions to resolve linux conda build failures
  packaging/torchvision/meta.yaml
Labels: cla signed
