Repository pytorch/vision, pull requests merged in 2024-05, with the labels that each got.

#8402 Deactivate mypy for `_functional_pil.py` and `video_reader.py`
  mypy.ini
Labels: cla signed, code quality

#8403 Ignore mypy for `prototype.transforms.*`
  mypy.ini
Labels: cla signed, code quality, prototype

#8404 Ignore some mypy errors
  torchvision/datasets/cityscapes.py
  torchvision/prototype/utils/_internal.py
Labels: cla signed, code quality

#8412 More mypy fixes/ignores
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/functional/_color.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, cla signed, code quality

#8411 Cleanup C++ model example and cmake CI job
  .github/scripts/cmake.sh
  README.md
  examples/cpp/CMakeLists.txt
  examples/cpp/README.rst
  examples/cpp/hello_world/CMakeLists.txt
  examples/cpp/hello_world/README.rst
  examples/cpp/hello_world/main.cpp
  examples/cpp/hello_world/trace_model.py
  examples/cpp/run_model.cpp
  examples/cpp/script_model.py
  packaging/windows/internal/build_cpp_example.bat
  packaging/windows/internal/build_frcnn.bat
  test/tracing/frcnn/CMakeLists.txt
  test/tracing/frcnn/test_frcnn_tracing.cpp
  test/tracing/frcnn/trace_model.py
Labels: cla signed

#8406 Add GIF decoder
  .github/scripts/unittest.sh
  .github/workflows/lint.yml
  CMakeLists.txt
  CONTRIBUTING.md
  docs/source/io.rst
  setup.py
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_gif.cpp
  torchvision/csrc/io/image/cpu/decode_gif.h
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/cpu/giflib/README
  torchvision/csrc/io/image/cpu/giflib/dgif_lib.c
  torchvision/csrc/io/image/cpu/giflib/gif_hash.c
  torchvision/csrc/io/image/cpu/giflib/gif_hash.h
  torchvision/csrc/io/image/cpu/giflib/gif_lib.h
  torchvision/csrc/io/image/cpu/giflib/gif_lib_private.h
  torchvision/csrc/io/image/cpu/giflib/gifalloc.c
  torchvision/csrc/io/image/cpu/giflib/openbsd-reallocarray.c
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/image/image.h
  torchvision/io/__init__.py
  torchvision/io/image.py
Labels: cla signed

#8413 Remove include Python.h
  CMakeLists.txt
  cmake/TorchVisionConfig.cmake.in
  examples/cpp/README.rst
  setup.py
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/video_reader/video_reader.cpp
  torchvision/csrc/vision.cpp
Labels: cla signed

#8414 Remove `#pragma comment(linker, "/include:_register_ops")`
  torchvision/csrc/macros.h
  torchvision/csrc/vision.h
Labels: module: ops, cla signed, code quality

#8416 Remove VISION_INLINE_VARIABLE
  torchvision/csrc/macros.h
  torchvision/csrc/vision.h
Labels: cla signed

#8418 Add torchscript test for decode_gif
  test/test_image.py
Labels: cla signed

#8385 Update docstrings of detection models regarding resizing strategy
  torchvision/models/detection/faster_rcnn.py
  torchvision/models/detection/fcos.py
  torchvision/models/detection/keypoint_rcnn.py
  torchvision/models/detection/mask_rcnn.py
  torchvision/models/detection/retinanet.py
Labels: enhancement, module: models, module: documentation, cla signed

#8429 Fix typo at `permutate_channels`
  torchvision/transforms/v2/functional/_color.py
Labels: cla signed

#8430 Add extra to install gdown
  setup.py
Labels: enhancement, dependency issue, cla signed

#8431 bump version to remove old prerelease status
  version.txt
Labels: cla signed

#8419 decode_gif: add transparency support and image offsets
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_gif.cpp
Labels: cla signed

#8439 Allow K=1 in `draw_keypoints`
  test/test_utils.py
  torchvision/utils.py
Labels: bug, module: utils, cla signed

#8446 Remove x86 MacOS jobs and use M1 instead
  .github/scripts/setup-env.sh
  .github/workflows/build-cmake.yml
  .github/workflows/tests.yml
Labels: cla signed

#8427 Enable one-hot-encoded labels in MixUp and CutMix
  test/test_transforms_v2.py
  torchvision/transforms/v2/_augment.py
Labels: cla signed

#8448 Fix use of `cutmix_alpha` in classification training references
  references/classification/transforms.py
Labels: bug, module: reference scripts, cla signed

#8436 Force use of torch.compile on deterministic roi_align implementation
  test/test_ops.py
  torchvision/ops/roi_align.py
Labels: enhancement, module: ops, cla signed

#8426 Create kernel on-device for `transforms.functional.gaussian_blur`
  torchvision/transforms/_functional_tensor.py
Labels: enhancement, module: transforms, cla signed

#8442 read_video: accept BytesIO on pyav backend
  torchvision/io/video.py
Labels: enhancement, module: video, cla signed

#8454 Skip v1 compat check on M1 for LinearTransform
  test/test_transforms_v2.py
Labels: enhancement, module: transforms, module: tests, cla signed

#8455 Use compiler.is_compiling() instead of deprecated _dynamo.is_compiling()
  torchvision/transforms/v2/functional/_geometry.py
Labels: module: transforms, module: tests, cla signed, code quality

#8381 Add GaussianNoise
  docs/source/transforms.rst
  test/test_transforms_v2.py
  torchvision/transforms/v2/__init__.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/__init__.py
  torchvision/transforms/v2/functional/_misc.py
Labels: module: transforms, new feature, cla signed
