Repository pytorch/vision, pull requests merged in 2024-06, with the labels that each got.

#8463 Make adjust_hue() work with numpy 2.0
  torchvision/transforms/_functional_pil.py
Labels: enhancement, module: transforms, cla signed

#8452 Return labels for FER2013 if possible
  test/test_datasets.py
  torchvision/datasets/fer2013.py
Labels: cla signed

#8466 Disable prototype tests
  .github/workflows/prototype-tests-linux-gpu.yml
Labels: module: tests, cla signed, prototype, other

#8387 Support encoded RLE format in for COCO segmentations
  test/test_datasets.py
  torchvision/tv_tensors/_dataset_wrapper.py
Labels: enhancement, module: datasets, cla signed

#7735 `SanitizeBoundingBox` based on minimum area
  test/test_transforms_v2.py
  torchvision/transforms/v2/_misc.py
  torchvision/transforms/v2/functional/_misc.py
Labels: cla signed

#8459 Allow v2 Resize to resize longer edge exactly to `max_size`
  test/test_transforms_v2.py
  torchvision/transforms/functional.py
  torchvision/transforms/v2/_geometry.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: enhancement, module: transforms, cla signed

#8467 Rename cpp example README.rst to README.md
  examples/cpp/README.md
Labels: enhancement, module: documentation, cla signed

#8474 Skip MPS tests
  test/conftest.py
Labels: cla signed

#8384 Update usages of torch.library APIs
  torchvision/_meta_registrations.py
  torchvision/csrc/ops/nms.cpp
Labels: cla signed

#8475 SBDataset: Only download noval file when image_set='train_noval'
  torchvision/datasets/sbd.py
Labels: bug, module: datasets, cla signed

#8470 Load _C ops before registering meta implementations
  torchvision/__init__.py
Labels: cla signed

#8408 Add compatibility with FFMPEG 7.0
  torchvision/csrc/io/decoder/audio_sampler.cpp
  torchvision/csrc/io/decoder/audio_stream.cpp
Labels: cla signed

#8451 Remove unused dynamo import
  torchvision/ops/roi_align.py
Labels: module: ops, cla signed, code quality

#8480 Skip flaky earth gif test on OSS CI
  test/test_image.py
Labels: cla signed

#8481 [FBcode->GH] Fix using namespace in pytorch/vision/torchvision/csrc/io/video/video…
  torchvision/csrc/io/video/video.h
Labels: module: io, cla signed, code quality

#8485 Re-enable vision MPS builds
  .github/workflows/build-cmake.yml
  .github/workflows/tests.yml
  setup.py
  test/conftest.py
Labels: cla signed

#8391 Adding GPU acceleration to encode_jpeg
  benchmarks/encoding.py
  test/test_image.py
  torchvision/csrc/io/image/cuda/decode_jpeg_cuda.cpp
  torchvision/csrc/io/image/cuda/encode_decode_jpegs_cuda.h
  torchvision/csrc/io/image/cuda/encode_jpegs_cuda.cpp
  torchvision/csrc/io/image/cuda/encode_jpegs_cuda.h
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/image/image.h
  torchvision/io/image.py
  torchvision/transforms/v2/functional/_augment.py
Labels: cla signed

#8490 Use @release/2.4 instead of @main for CI jobs
  .github/workflows/build-cmake.yml
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-conda-m1.yml
  .github/workflows/build-conda-windows.yml
  .github/workflows/build-wheels-aarch64-linux.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-m1.yml
  .github/workflows/build-wheels-windows.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests.yml
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#8494 Update version on main branch
  version.txt
Labels: cla signed
