Repository pytorch/vision, pull requests merged in 2024-10, with the labels that each got.

#8633 Revamp decoding docs
  docs/source/io.rst
  torchvision/io/image.py
  torchvision/io/video.py
  torchvision/io/video_reader.py
Labels: enhancement, module: documentation, module: io, cla signed

#8666 [Cherry-Pick for 0.20] Revamp decoding docs (#8633)
  docs/source/io.rst
  torchvision/io/image.py
  torchvision/io/video.py
  torchvision/io/video_reader.py
Labels: enhancement, module: documentation, module: io, cla signed

#8659 Allow custom package name for CI builds of torchvision
  setup.py
Labels: cla signed

#8673 [Cherry-pick for 0.20] Expose transforms.v2 utils for writing custom transforms
  test/test_transforms_v2.py
  torchvision/transforms/v2/__init__.py
Labels: enhancement, module: transforms, cla signed

#8674 Remove lint job for release 0.20
  .github/workflows/lint.yml
Labels: cla signed

#8676 Remove viable strict workflow
  .github/workflows/update-viablestrict.yml
Labels: cla signed

#8576 Draft for better `write_video` documentation
  torchvision/io/video.py
Labels: cla signed

#8620 Update stanford-cars docs with more elaborate instructions for `download=False`
  torchvision/datasets/stanford_cars.py
Labels: cla signed

#8618 Fix adjust_hue on ARM
  torchvision/transforms/_functional_pil.py
Labels: bug, module: transforms, cla signed

#8681 Don't print when dataset is already downloaded
  torchvision/datasets/caltech.py
  torchvision/datasets/celeba.py
  torchvision/datasets/cifar.py
  torchvision/datasets/imagenette.py
  torchvision/datasets/lfw.py
  torchvision/datasets/omniglot.py
  torchvision/datasets/sbu.py
  torchvision/datasets/semeion.py
  torchvision/datasets/stl10.py
  torchvision/datasets/widerface.py
Labels: enhancement, module: datasets

#8683 remove printing info in datasets
  torchvision/datasets/_stereo_matching.py
  torchvision/datasets/celeba.py
  torchvision/datasets/cityscapes.py
  torchvision/datasets/inaturalist.py
  torchvision/datasets/kinetics.py
  torchvision/datasets/mnist.py
  torchvision/datasets/phototour.py
  torchvision/datasets/utils.py
Labels: cla signed

#8690 0.20 docs
  stable
  versions.html
Labels: cla signed

#8692 fix CUDA build with NVCC_FLAGS in env
  setup.py
Labels: cla signed

#8694 Update version.txt to 0.20.1
  version.txt
Labels: cla signed
