Repository pytorch/vision, pull requests merged in 2024-08, with the labels that each got.

#8563 EuroSAT: fix SSL certificate issues
  torchvision/datasets/eurosat.py
Labels: bug, module: datasets, cla signed

#8496 GPU jpeg decoder: add batch support and hardware decoding
  benchmarks/encoding.py
  benchmarks/encoding_decoding.py
  test/test_image.py
  torchvision/csrc/io/image/cuda/decode_jpeg_cuda.cpp
  torchvision/csrc/io/image/cuda/decode_jpegs_cuda.cpp
  torchvision/csrc/io/image/cuda/decode_jpegs_cuda.h
  torchvision/csrc/io/image/cuda/encode_decode_jpegs_cuda.h
  torchvision/csrc/io/image/image.cpp
  torchvision/io/image.py
  torchvision/transforms/v2/functional/_augment.py
Labels: cla signed

#8579 Only run 'extended' test if `run-extended` label is set
  .github/workflows/tests.yml
Labels: cla signed, run-extended

#8580 Skip flaky test_autocast_cpu test
  test/test_ops.py
Labels: cla signed

#8581 Remove vs2019 folder
  packaging/vs2019/activate.bat
  packaging/vs2019/conda_build_config.yaml
  packaging/vs2019/install_activate.bat
  packaging/vs2019/meta.yaml
Labels: cla signed

#8582 Revert "Remove vs2019 folder (#8581)"
  packaging/vs2019/activate.bat
  packaging/vs2019/conda_build_config.yaml
  packaging/vs2019/install_activate.bat
  packaging/vs2019/meta.yaml
Labels: cla signed

#8583 Fix doc build for Python 3.11+
  docs/source/conf.py
Labels: enhancement, module: documentation, cla signed

#8552 Remove 3.8 support
  .github/workflows/build-cmake.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests-schedule.yml
  .github/workflows/tests.yml
  README.md
  test/test_ops.py
  torchvision/csrc/io/decoder/gpu/decoder.cpp
Labels: cla signed

#8590 Remove pre_build_script from windows conda build
  .github/workflows/build-conda-windows.yml
Labels: cla signed

#8592 Pin setuptools to 72.1.0
  .github/scripts/setup-env.sh
  packaging/pre_build_script.sh
Labels: cla signed

#8594 Remove numpy<2.0 windows pin
  setup.py
Labels: cla signed

#8527 Add webp decoder
  .github/scripts/export_IS_M1_CONDA_BUILD_JOB.sh
  .github/scripts/setup-env.sh
  .github/workflows/build-conda-m1.yml
  CMakeLists.txt
  docs/source/io.rst
  packaging/pre_build_script.sh
  packaging/torchvision/meta.yaml
  setup.py
  test/assets/fakedata/logos/rgb_pytorch.webp
  test/smoke_test.py
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/cpu/decode_webp.cpp
  torchvision/csrc/io/image/cpu/decode_webp.h
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/image/image.h
  torchvision/io/__init__.py
  torchvision/io/image.py
Labels: cla signed

#8602 Cleanup video decoder build stuff
  setup.py
  test/test_io.py
  test/test_video_reader.py
  test/test_videoapi.py
  torchvision/__init__.py
  torchvision/io/__init__.py
  torchvision/io/_load_gpu_decoder.py
  torchvision/io/_video_opt.py
  torchvision/io/video_reader.py
Labels: cla signed

#8596 Add AVIF decoder (Part 1- this is not public or available yet)
  CMakeLists.txt
  setup.py
  test/assets/fakedata/logos/rgb_pytorch.avif
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_avif.cpp
  torchvision/csrc/io/image/cpu/decode_avif.h
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/image/image.h
  torchvision/io/__init__.py
  torchvision/io/image.py
Labels: cla signed

#8606 Cherry-Pick Pin setuptools to 72.1.0
  .github/scripts/setup-env.sh
  packaging/pre_build_script.sh
Labels: cla signed

#8607 [cherry-pick] Restrict ffmpeg to 4.2+.X versions to resolve linux conda build failures
  packaging/torchvision/meta.yaml
Labels: cla signed

#8605 Fix parameter name in docstring
  torchvision/datasets/moving_mnist.py
Labels: cla signed

#8610 Add transparency support to webp decoder
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/cpu/decode_webp.cpp
  torchvision/csrc/io/image/cpu/decode_webp.h
  torchvision/csrc/io/image/image.cpp
  torchvision/io/image.py
Labels: cla signed

#8611 Fix link to v2.RGB in docs
  torchvision/transforms/v2/functional/_color.py
Labels: enhancement, module: documentation, cla signed

#8612 Minor cleanup of webp decoding mode logic
  torchvision/csrc/io/image/cpu/decode_webp.cpp
Labels: enhancement, module: io, cla signed, code quality

#8613 Add transparency and >8bits images support to AVIF decoder
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_avif.cpp
  torchvision/csrc/io/image/cpu/decode_avif.h
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/image.cpp
  torchvision/io/image.py
Labels: enhancement, module: io, cla signed

#8597 Add HEIC decoder
  setup.py
  test/assets/fakedata/logos/rgb_pytorch_incorrectly_encoded_but_who_cares.heic
  test/test_image.py
  torchvision/csrc/io/image/cpu/decode_heic.cpp
  torchvision/csrc/io/image/cpu/decode_heic.h
  torchvision/csrc/io/image/cpu/decode_image.cpp
  torchvision/csrc/io/image/image.cpp
  torchvision/csrc/io/image/image.h
  torchvision/io/__init__.py
  torchvision/io/image.py
Labels: cla signed

#8615 use_sequence_param_check
  torchvision/transforms/transforms.py
  torchvision/transforms/v2/_augment.py
Labels: cla signed

#8617 Cleanup/refactor of decoders and related tests
  test/test_image.py
  torchvision/csrc/io/image/common.cpp
  torchvision/csrc/io/image/common.h
  torchvision/csrc/io/image/cpu/decode_avif.cpp
  torchvision/csrc/io/image/cpu/decode_avif.h
  torchvision/csrc/io/image/cpu/decode_gif.cpp
  torchvision/csrc/io/image/cpu/decode_heic.cpp
  torchvision/csrc/io/image/cpu/decode_heic.h
  torchvision/csrc/io/image/cpu/decode_image.h
  torchvision/csrc/io/image/cpu/decode_jpeg.cpp
  torchvision/csrc/io/image/cpu/decode_jpeg.h
  torchvision/csrc/io/image/cpu/decode_png.cpp
  torchvision/csrc/io/image/cpu/decode_png.h
  torchvision/csrc/io/image/cpu/decode_webp.cpp
  torchvision/csrc/io/image/cpu/decode_webp.h
  torchvision/csrc/io/image/cuda/decode_jpegs_cuda.cpp
  torchvision/csrc/io/image/cuda/decode_jpegs_cuda.h
  torchvision/csrc/io/image/cuda/encode_decode_jpegs_cuda.h
Labels: cla signed
