Repository pytorch/vision, pull requests merged in 2024-11, with the labels that each got.

#8705 Add MovingMNIST to __all__ list in datasets
  torchvision/datasets/__init__.py
Labels: enhancement, module: datasets

#8712 Fix memory leak in decode_webp
  torchvision/csrc/io/image/cpu/decode_webp.cpp
Labels: bug, module: io, cla signed

#8691 Don't error when dataset is already downloaded
  test/test_datasets.py
  torchvision/datasets/inaturalist.py
  torchvision/datasets/kinetics.py
  torchvision/datasets/places365.py
Labels: enhancement, module: datasets, cla signed

#8709 Warning for dataset download & extract race condition
  docs/source/datasets.rst
Labels: cla signed

#8719 [MPS] Lift MSL version to 3.0+ and use relevant helpers
  torchvision/csrc/ops/mps/mps_kernels.h
  torchvision/csrc/ops/mps/ps_roi_pool_kernel.mm
Labels: topic: build, cla signed

#8723 Revert "Fix memory leak in decode_webp (#8712)"
  torchvision/csrc/io/image/cpu/decode_webp.cpp
Labels: cla signed

#8725 Migrate towards linux_job_v2.yml
  .github/scripts/cmake.sh
  .github/workflows/build-cmake.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests.yml
Labels: cla signed

#8754 Fix clang-format
  torchvision/csrc/io/decoder/memory_buffer.cpp
  torchvision/csrc/io/decoder/sync_decoder_test.cpp
  torchvision/csrc/io/image/cpu/encode_jpeg.cpp
Labels: cla signed

#8757 Update .gitignore
  .gitignore
Labels: cla signed

#8758 Fix lsun link
  torchvision/datasets/lsun.py
Labels: module: datasets, module: documentation, cla signed

#8743 Fixed a bug in googlenet.py
  torchvision/models/googlenet.py
Labels: bug, module: models, cla signed

#8689 Fix warning raised by torch.meshgrid on missing indexing
  references/depth/stereo/utils/losses.py
  torchvision/models/maxvit.py
Labels: cla signed

#8578 Add `label_colors` argument to `draw_bounding_boxes`
  test/assets/fakedata/draw_boxes_different_label_colors.png
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#8763 Update smoke_test.py - temporary disable torch.compile tests
  test/smoke_test.py
Labels: cla signed

#8708 __deepcopy__ for DualGraphModule
  test/test_backbone_utils.py
  torchvision/models/feature_extraction.py
Labels: cla signed

#8765 Revert "Update smoke_test.py - temporary disable torch.compile tests"
  test/smoke_test.py
Labels: cla signed

#8761 Switch unit test back to Manylinux2014
  .github/workflows/prototype-tests-linux-gpu.yml
  .github/workflows/tests.yml
Labels: cla signed, with-ssh
