Repository pytorch/vision, pull requests merged in 2025-03, with the labels that each got.

#8950 Remove quiet option from pre_build_script. Install libjpeg-turbo and ffmpeg in 2 separate steps
  packaging/pre_build_script.sh
Labels: cla signed

#8970 Add an OS-independent script for updating the workflow files
  release/README.md
  release/apply-release-changes.py
Labels: cla signed

#8964 Disable Feature Extraction tests
  .github/scripts/unittest.sh
Labels: cla signed

#8973 Ignore onnx tests
  .github/scripts/unittest.sh
Labels: cla signed

#8974 Skip onnx AGAIN
  .github/scripts/unittest.sh
Labels: cla signed

#8975 Disable onnx test job again
  .github/workflows/tests.yml
Labels: cla signed

#8963 Install torchvision-extra-decoders from nightly channel
  .github/scripts/setup-env.sh
  packaging/post_build_script.sh
Labels: cla signed

#8978 Deactivate Windows GPU unittest job
  .github/workflows/tests.yml
Labels: cla signed

#8977 Disable M1 3.11 unittests
  .github/workflows/tests.yml
Labels: cla signed

#8976 Skip libavif/libheic tests
  test/test_image.py
Labels: cla signed

#8982 Fix post-build-script
  packaging/post_build_script.sh
  packaging/pre_build_script.sh
  packaging/wheel/relocate.py
Labels: cla signed

#8843 Use brackets instead of parenthesis for interval
  torchvision/transforms/v2/_geometry.py
Labels: enhancement, module: transforms, module: documentation, cla signed

#8925 Update threshold for batched NMS
  torchvision/ops/boxes.py
Labels: cla signed

#8983 0.22 Cherry-picks
  .github/scripts/setup-env.sh
  .github/scripts/unittest.sh
  .github/workflows/tests.yml
  packaging/post_build_script.sh
  packaging/pre_build_script.sh
  packaging/wheel/relocate.py
  release/README.md
  release/apply-release-changes.py
  test/test_image.py
  torchvision/models/optical_flow/raft.py
  torchvision/ops/boxes.py
  torchvision/transforms/v2/_color.py
  torchvision/transforms/v2/_geometry.py
Labels: cla signed

#8996 [SmokeTest] Test antialias on MPS device
  test/smoke_test.py
Labels: cla signed

#8998 Deactivate clang format
  .github/workflows/lint.yml
Labels: cla signed

#8997 Deprecate video decoding and encoding
  docs/source/io.rst
  gallery/others/plot_video_api.py
  torchvision/io/_video_deprecation_warning.py
  torchvision/io/_video_opt.py
  torchvision/io/video.py
  torchvision/io/video_reader.py
Labels: cla signed

#8999 Deactivate bc linter
  .github/workflows/lint.yml
Labels: cla signed

#8993 fix: Add type checking in `posterize_image`.
  test/test_transforms_v2.py
  torchvision/transforms/v2/functional/_color.py
Labels: enhancement, module: transforms, cla signed

#8995 fix: forbid bool value from `JPEG`'s quality argument type.
  test/test_transforms_v2.py
  torchvision/transforms/v2/_augment.py
Labels: cla signed

#8959 fix: add appropriate error message when validating padding argument.
  test/test_transforms_v2.py
  torchvision/transforms/v2/_utils.py
Labels: cla signed

#8972 feat: expose `loader` parameter in `FlowDataset` type, except `Flying…
  test/test_datasets.py
  torchvision/datasets/_optical_flow.py
Labels: cla signed

#9000 Revert rotated bboxes
  test/common_utils.py
  test/test_ops.py
  test/test_transforms_v2.py
  torchvision/ops/_box_convert.py
  torchvision/ops/boxes.py
  torchvision/transforms/v2/functional/_meta.py
  torchvision/tv_tensors/_bounding_boxes.py
Labels: cla signed

#8945 feat: add loader to `Omniglot` and `INaturalist`'s argument.
  test/test_datasets.py
  torchvision/datasets/inaturalist.py
  torchvision/datasets/omniglot.py
Labels: cla signed

#9004 0.22 Cherry-picks continued
  .github/workflows/lint.yml
  docs/source/io.rst
  gallery/others/plot_video_api.py
  test/test_datasets.py
  test/test_transforms_v2.py
  torchvision/datasets/_optical_flow.py
  torchvision/datasets/inaturalist.py
  torchvision/datasets/omniglot.py
  torchvision/io/_video_deprecation_warning.py
  torchvision/io/_video_opt.py
  torchvision/io/video.py
  torchvision/io/video_reader.py
  torchvision/transforms/v2/_augment.py
  torchvision/transforms/v2/_auto_augment.py
  torchvision/transforms/v2/_utils.py
  torchvision/transforms/v2/functional/_color.py
Labels: cla signed
