Repository pytorch/vision, pull requests merged in 2025-05, with the labels that each got.

#9061 [release-only] Bump version to 0.22.1
  version.txt
Labels: cla signed

#9080 Add dependency installation script for windows arm64 builds
  packaging/pre_build_script_arm64.sh
Labels: cla signed

#9081 fix anti-pattern for cudagraph
  torchvision/models/detection/anchor_utils.py
Labels: cla signed

#9088 Revert "fix anti-pattern for cudagraph (#9081)"
  torchvision/models/detection/anchor_utils.py
Labels: cla signed, ci-no-td

#9063 Removing Conda references.
  docs/source/training_references.rst
Labels: module: documentation, cla signed

#9083 Update docstrings of MaskRCNN
  torchvision/models/detection/mask_rcnn.py
Labels: cla signed

#9089 Update version to 0.23.0 in nightly
  version.txt
Labels: cla signed
