Repository pytorch/vision, pull requests merged in 2025-02, with the labels that each got.

#8900 Revert "Add 3.13t wheel builds "
  packaging/pre_build_script.sh
Labels: cla signed

#8901 Clean up reference to VS2019
  .github/scripts/setup-env.sh
  .github/workflows/tests.yml
  packaging/windows/internal/vc_env_helper.bat
Labels: cla signed

#8838 Add `classes` to the `Flowers102` dataset
  torchvision/datasets/flowers102.py
Labels: cla signed

#8914 Port vision to AIX
  setup.py
  torchvision/datasets/mnist.py
Labels: cla signed

#8792 fix saving versions on windows
  setup.py
Labels: cla signed

#8882 feat: Raise ValueError for alpha > 1 in sigmoid_focal_loss
  torchvision/ops/focal_loss.py
Labels: cla signed

#8897 [ROCm][Windows] Fix compile torchvision image for ROCm
  torchvision/csrc/io/image/common.cpp
  torchvision/csrc/io/image/image.cpp
Labels: module: rocm, cla signed

#8924 Fix C linter
  torchvision/csrc/io/image/common.cpp
Labels: cla signed

#8921 Fix: pin_memory() preserves TVTensor class and metadata
  test/test_tv_tensors.py
  torchvision/tv_tensors/_torch_function_helpers.py
Labels: cla signed

#8926 Fix non-rotated format to rotated format conversion logic
  torchvision/transforms/v2/functional/_meta.py
  torchvision/tv_tensors/_bounding_boxes.py
Labels: cla signed

#8929 Encode jpeg cuda sync
  test/test_image.py
  torchvision/csrc/io/image/cuda/encode_jpegs_cuda.cpp
  torchvision/csrc/io/image/cuda/encode_jpegs_cuda.h
Labels: bug, module: io, cla signed

#8932 Docs: update `pycocotools` url in `CocoDetection` and `CocoCaptions`.
  torchvision/datasets/coco.py
Labels: cla signed

#8935 Fix lint
  setup.py
Labels: cla signed

#8922 feat: expose loader argument in Country211 and EuroSAT.
  test/datasets_utils.py
  test/test_datasets.py
  torchvision/datasets/country211.py
  torchvision/datasets/eurosat.py
  torchvision/datasets/imagenet.py
Labels: cla signed

#8928 Added 'test' split support for Places365 dataset
  torchvision/datasets/places365.py
Labels: cla signed

#8931 Add `roi_align` nondeterministic support for XPU
  torchvision/ops/roi_align.py
Labels: cla signed

#8936 Support specifying a torch range
  setup.py
Labels: enhancement, topic: build, cla signed

#8939 feats: add loader in classification task datasets.
  test/test_datasets.py
  torchvision/datasets/clevr.py
  torchvision/datasets/country211.py
  torchvision/datasets/dtd.py
  torchvision/datasets/eurosat.py
  torchvision/datasets/fgvc_aircraft.py
  torchvision/datasets/flickr.py
  torchvision/datasets/flowers102.py
  torchvision/datasets/folder.py
  torchvision/datasets/food101.py
  torchvision/datasets/imagenet.py
  torchvision/datasets/imagenette.py
  torchvision/datasets/lfw.py
  torchvision/datasets/rendered_sst2.py
  torchvision/datasets/sbu.py
  torchvision/datasets/stanford_cars.py
  torchvision/datasets/sun397.py
Labels: cla signed

#8944 Fix `RandomResizedCrop` `scale` & `ratio` argument.
  test/test_transforms_v2.py
  torchvision/transforms/v2/_geometry.py
Labels: cla signed
