Repository pytorch/vision, pull requests merged in 2025-08, with the labels that each got.

#9058 Batched Box Ops
  test/test_ops.py
  torchvision/ops/boxes.py
Labels: module: ops, cla signed

#9175 Upcast rotated box transforms
  torchvision/transforms/v2/functional/_geometry.py
  torchvision/transforms/v2/functional/_meta.py
Labels: bug, cla signed

#9181 Fix `_parallelogram_to_bounding_boxes`
  test/test_transforms_v2.py
  torchvision/transforms/v2/functional/_geometry.py
Labels: bug, cla signed

#9191 Resolve torchvision + opencv version issues
  torchvision/csrc/io/decoder/audio_sampler.cpp
Labels: fb-exported, cla signed

#9193 fix: typo in find_package for webp and remove avif from CMake
  CMakeLists.txt
Labels: cla signed
