Repository pytorch/vision, pull requests merged in 2025-04, with the labels that each got.

#9007 A temporary fix to windows unittests failing in `INaturalistTestCase`.
  test/common_utils.py
  test/test_datasets.py
  torchvision/datasets/inaturalist.py
Labels: cla signed

#9012 Remove stanford cars download instructions
  torchvision/datasets/stanford_cars.py
Labels: cla signed

#9013 [Cherry-pick for 0.22 release] Remove stanford cars download instructions (#9012)
  torchvision/datasets/stanford_cars.py
Labels: cla signed

#9014 [docs] correct docs of `decode_heic`
  torchvision/io/image.py
Labels: cla signed

#9015 Put back docs of decode_png
  docs/source/io.rst
Labels: cla signed

#9016 [Cherry-pick for 0.22] Put back docs of decode_png
  docs/source/io.rst
Labels: cla signed

#9019 Fix rotated box format conversion from XYXYXYXY to XYWHR
  test/test_ops.py
  torchvision/ops/_box_convert.py
  torchvision/transforms/v2/functional/_meta.py
Labels: cla signed

#9018 Add label background
  test/assets/fakedata/draw_boxes_different_label_fill_colors.png
  test/test_utils.py
  torchvision/utils.py
Labels: cla signed

#9024 [Manylinux_2_28] Modify relocate script for linux builds: fix wheel_name
  packaging/wheel/relocate.py
Labels: cla signed

#9027 [Build] Add `homebrew` as library search location
  setup.py
Labels: topic: build, cla signed

#9032 Revert "[Manylinux_2_28] Modify relocate script for linux builds: fix…
  packaging/wheel/relocate.py
Labels: cla signed, ci-no-td

#9035 Update .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: cla signed
